stackrox/acs-fleet-manager

- dev/config/dataplane-cluster-configuration-minikube.yaml
- internal/dinosaur/pkg/presenters/data_plane_cluster_status.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
Testing state transition for clusters in fleet manager from `cluster_provisioned` to `waiting_for_fleetshard_operator` to `ready`. Cluster starts at `cluster_provisioned` state and should transition to `waiting_for_fleetshard_operator` with the reconcilation of the `cluster_provisioned` state. This step was commented out and reactivated in this PR. Skipping operator/addon installation for now. The transition from `waiting_for_fleetshard_operator` to `ready` was tested and works with a PUT request to `/api/rhacs/v1/agent-clusters/<id>/status`.
Also added a presenter implementation for the response for `GET /api/rhacs/v1/agent-cluster/<id>`.
- ~[ ] Documentation added if necessary~
Manual Testing:
```yaml
clusters:
- name: docker-desktop
cluster_id: …
```
> enabling cluster state transition provisioned, waiting, ready

- Makefile
- go.mod
- go.sum
- internal/dinosaur/pkg/clusters/clusterbuilder_moq.go
- internal/dinosaur/pkg/services/clusterservice_moq.go
- pkg/client/keycloak/client.go
- pkg/client/keycloak/client_moq.go
- pkg/client/keycloak/client_test.go
- pkg/client/keycloak/gocloak_moq.go
- pkg/server/api_server.go
- pkg/services/keycloak.go
- pkg/services/keycloak_test.go
Old versions of gocloak and jwt-go contain vulnerabilities.
See https://github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pull/847/files and https://github.com/bf2fc6cc711aee1a0c2a/ffm-fleet-manager-go-template/commit/95d15df01566d900658b8ce506770d30557bf107 for context.
This PR bumps gocloak, go-jwt-middleware, removes github.com/dgrijalva/jwt-go in favour of the newer https://github.com/golang-jwt/jwt.
Mostly this PR consists of updating generated moq files. The actual diff is pretty small (after filtering out `*_moq.go` and `go.sum`).
```
```
> Bump gocloak, jwt and go-jwt-middleware

- .github/workflows/ci.yaml
- build_deploy.sh
`build_deploy.sh` should rely on `QUAY_USER` and `QUAY_TOKEN`.
Also, image tag should be 7 chars long.
Not relevant
> Drop quay creds overrides in build_deploy.sh

- dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
- dev/config/dataplane-cluster-configuration-infractl-osd.yaml
- dev/config/dataplane-cluster-configuration-minikube.yaml
- internal/dinosaur/pkg/api/dbapi/data_plane_cluster_status.go
- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/pkg/config/dataplane_cluster_config_test.go
- internal/dinosaur/pkg/presenters/data_plane_cluster_status.go
- internal/dinosaur/pkg/services/clusters.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/pkg/workers/dinosaur_mgrs/accepted_dinosaurs_mgr.go
- internal/dinosaur/test/helper.go
- pkg/api/cluster_types.go
- pkg/api/cluster_types_test.go
In order to get a central resource in fleet manager to transition from `accepted` to `provisioning` you have to set available operator version for a cluster. Until now it was expected that this would be done by fleet shard components with a PUT request to `/api/rhacs/v1/<cluster-id>/status` when they are deployed and ready on the data plane cluster. Since we're bringing the clusters in manually, it makes sense to also allow setting this configuration with the `dataplane-cluster-configuration.yaml` file. When using the new introduced configuration:
```
...
available_central_operator_versions:
- version: "0.1.0"
ready: true
central_versions:
- version: "0.1.0"
```
The cluster will be in `ready` state and have an operator version available, thus there is no further preparation necessary to …
> enable setting operator versions in dataplane config file

- build_deploy.sh
Should not affect developers unless they happen to also have a go install at this exact path.
If this proves to work, will change to be applied in a less hacky way.
cc @kurlov
> Quick hack needed to get build working on jenkins

- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/pkg/config/dinosaur.go
- templates/service-template.yml
Drop redundant configMaps `fleet-manager-dinosaur-sre-user-list` and `fleet-manager-dinosaur-capacity-config`. We do not need it atm. This will make deploy on Jenkins a bit cleaner for appSRE.
I think it makes sense to drop related code in the separate PR. I added todos for that.
> Drop redundant configMaps

- BUILD_IMAGE_VERSION
- Dockerfile
- Makefile
- README.md
- secrets/db.host.internal-docker
> Add fleetshard-sync to images, support building images in containers

- fleetshard/config/config.go
- fleetshard/main.go
- fleetshard/pkg/runtime/runtime.go
- go.mod
- go.sum
Currently these values are hard-coded. Make them configurable using environment variables.
```
```
> Retrieve fleet-manager endpoint and cluster ID from environment

- .gitignore
- fleetshard/pkg/centralreconciler/reconciler.go
- fleetshard/pkg/fleetmanager/client.go
- fleetshard/pkg/fleetmanager/client_test.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/handlers/data_plane_cluster.go
Handle fleet manager API errors correctly. 
- Run Fleet-Manager + Fleetshard-sync with an invalid OCM token, should write errors into the log
> Handle fleet manager REST api errors

- templates/service-template.yml
Temporary hack to figure out the simplest content of configuration files to keep the containers up and running.
Figuring out viable values using a real secret would take an AppSRE approval round for every iteration.
Once we know which values are OK we will go back to using a secret.
> Temporarily use a configmap in place of the service secret.

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-rbac.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Add full permissions for fleet shard synchronizer. Also added a TODO to only give minimal permissions when it is clear which API operations we want to do.
Manual testing against staging dataplane cluster "acs-dp-1":
```bash
helm -n rhacs delete rhacs-terraform
helm -n rhacs install rhacs-terraform dp-terraform/helm/rhacs-terraform/ \
--set fleetshardSync.ocmToken=$(ocm token) \
--set fleetshardSync.fleetManagerEndpoint=${NGROK_PREFIX} \
--set fleetshardSync.clusterId=${cluster_id}
jrodrig-mac:acs-fleet-manager jrodrig$ helm -n rhacs list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
rhacs-terraform rhacs           1               2022-06-06 12:17:09.670204 +0200 CEST   deployed …
```
> Add full permissions for fleet shard synchronizer

- Makefile
- config/dataplane-cluster-configuration.yaml
- e2e/README.md
- e2e/cleanup.sh
- e2e/e2e_suite_test.go
- e2e/e2e_test.go
- fleetshard/README.md
- fleetshard/config/config.go
- fleetshard/pkg/fleetmanager/client.go
- fleetshard/pkg/runtime/runtime.go
- go.mod
- scripts/setup-dev-env.sh
Add a simple e2e testing suite to run locally. See `e2e/README.md` for instructions.
```
```
> Add e2e tests

- dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
Optionally install ACS operator on terraform. This is mostly useful as a temporary dev tool, until the fleetshard sync installs the ACS operator.
NOTE: deleting the subscrition does not delete the ClusterServiceVersion properly. This seems to be a problem of OLM. The definitive implementation of fleet shard synchronizer should do something about it.
```bash
FM_ENDPOINT=... https://bfdc-83-33-206-69.eu.ngrok.io
oc delete namespace rhacs
oc create namespace rhacs
helm -n rhacs install rhacs-terraform dp-terraform/helm/rhacs-terraform/ \
--set fleetshardSync.ocmToken=$(ocm token) \
--set fleetshardSync.fleetManagerEndpoint=${FM_ENDPOINT} \
--set fleetshardSync.clusterId=${cluster_id}
helm -n rhacs list
oc -n rhacs get deployment
oc get OperatorGroup -A | grep rhacs
oc get subscriptions -A | …
```
> Optionally install ACS operator on terraform

- templates/service-template.yml
livenessProbe failes with `Liveness probe failed: HTTP probe failed with statuscode: 401` so use `/healthcheck` temporarily until 401 is resolved
> Temporarily use readiness probe as liveness

- templates/service-template.yml
This is a one-time hack to prepare for an incompatible schema change #82 
The procedure will be:
- merge this one (should not affect developers' environments)
- wait for the rollback to be applied in staging env (should cause the service container to crash due to missing tables)
- merge #82 
- (at this point a rollout to staging can happen but will not have much impact since there is still no real migration container)
- roll back this one (at this point the new schema will be applied)
@johannes94 and I have established that the `rollback-all` command deletes all tables, including the migrations table.
> WARNING WARNING Temporarily replace migration init container with DB wipe

- templates/service-template.yml
Reverts stackrox/acs-fleet-manager#114
Database on staging was wiped (mostly) successfully.
The only caveat is that compared to the plan enumerated in #114 we mixed up the order of PR merges, which resulted in an orphaned dinosaurs table. We're leaving it as is because such empty table is not an issue.
> Revert "WARNING WARNING Temporarily replace migration init container with DB wipe"

- dev/config/dataplane-cluster-configuration-staging.yaml
```bash
KUBECONFIG=${HOME}/.kube/config
DATAPLANE_CLUSTER_CONF="$(pwd)/dev/config/dataplane-cluster-configuration-staging.yaml"
make binary
./fleet-manager serve    --dataplane-cluster-config-file=${DATAPLANE_CLUSTER_CONF}    --providers-config-file=$(pwd)/dev/config/provider-configuration-infractl-osd.yaml    --kubeconfig=${KUBECONFIG}    2>&1 | tee fleet-manager-serve.log
```
Fleet manager starts fine, and it is able to do resolve leader election after a while
> Update dev dataplane config for new staging cluster

- templates/service-template.yml
Fixed indentation:
```
[2022-06-14 10:54:51] [ERROR] [saasherder.py:_process_template:697] - [https://github.com/stackrox/acs-fleet-manager//templates/service-template.yml:main] error fetching template: while parsing a block mapping
in "<byte string>", line 522, column 7:
main.yaml: |
^
expected <block end>, but found '<block mapping start>'
in "<byte string>", line 595, column 11:
listeners:
^
```
Tested with `yq '.objects[10].data."main.yaml"' service-template.yml | yq -`
> Fix envoy config comment indents.

- docs/test-locally-claims.md
It seems that Markdown formatting for `docs/test-locally-claims.md` is broken. This PR should fix that.
- ~[ ] Documentation added if necessary~
- ~[ ] CI and all relevant tests are passing~ - changes should not affect CI and tests
Check the preview of the file in GitHub UI.
> Fix: test-locally-claims.md formatting

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-rbac.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
Add values to specify RHSSO user and password for fleetshard sync. Those are stored in a secret mounted on the fleetshard synchronizer container, so it can use it to get credentials to authenticate to make requests to the private API. 
This also make a change in the handling of cluster role and cluster role binding for the fleet shard synchronizer, so the cluster terraforming helm chart can be deployed in more than 1 Helm release in the same cluster, so we can share development clusters.
Launch local fleet manager and ngrok proxy
```bash
make osd/setup redhatsso/setup # if secrets/redhatsso-service.clientId and so it's missing
KUBECONFIG=${HOME}/.kube/config
DATAPLANE_CLUSTER_CONF="$(pwd)/dev/config/dataplane-cluster-configuration-staging.yaml"
make …
```
> Add values to specify RHSSO user and password for fleetshard sync

- pkg/server/logging/writer.go
fleet-manager logs currently include all requests including authentication tokens. Tokens should not be logged!
This PR takes care of removing them prior to logging.
This also makes fleet-manager logs much easier to read.
```
```
> Redact request logs to make them less noisy and leaky

- .openshift-ci/tests/e2e.sh
This will be referenced from within the ci-operator configuration so that whatever is in this file will be executed in a test environment with an OpenShift cluster available.
```
```
> Add entrypoint for e2e testing in OpenShift CI

- dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Add randomly generated UID to the grafana dashboard. It is required filed and was not generated in the grafana playground so I missed it in the previous PR.
Also add a separate folder for ACS related dashboards. Most likely we will have a separate dashboard for SLOs
> ROX-11514: Add UID to the Grafana dashboard

- e2e/README.md
- e2e/e2e_suite_test.go
- e2e/e2e_test.go
This change adds env vars for configuring the cloud provider and region of central request in e2e tests, so tests can be run against the staging data plane OSD cluster. If not specific the previously hardcoded values are used as defaults. 
Some other minor changes:
- Add a nil check to avoid a panic if the first test fails
- Disable tests that are failing, due to the new namespace that fleet manager assigns to centrals. Added TODO to fix that eventually
- Add env var to specify test timeout
Run tests against staging data plane OSD cluster. First test `It("created a central"` fails with "API error (HTTP status 403) occured RHACS-MGMT-24: only one eval instance is allowed", but fixing that issue is out of the scope of this change
```bash
make osd/setup …
```
> Allow configuring cloud provider and region of central request in e2e tests

- docs/feature-flags.md
- internal/dinosaur/pkg/config/dinosaur.go
- templates/service-template.yml
This PR adds sso.redhat.com OIDC client secret to fleet-manager. This secret is used by Central instances to integrate with sso.redhat.com. 
This PR is done as part of prototyping for [ROX-11063](https://issues.redhat.com/browse/ROX-11063)
Corresponding secret is added to the staging cluster here: [gitlab](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/41397)
1. Deployed fleet-manager using `--rhsso-client-secret-file` parameter
> Add RHSSO central OIDC secret to configuration and service-template.yml

- e2e/README.md
- e2e/e2e_test.go
- fleetshard/pkg/fleetmanager/client.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/util.go
- internal/dinosaur/pkg/services/util_test.go
- scripts/setup-dev-env.sh
Add e2e test to remove Central. It checks for CR and Namespace deletion.
Run e2e-tests and make sure Central was created and deleted by observing central_requests database and fleetshard-sync logs.
> ROX-11467 - Add Central deletion e2e test

- fleetshard/pkg/centralreconciler/reconciler.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_endpoint.go
- internal/dinosaur/pkg/presenters/manageddinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- openapi/fleet-manager-private.yaml
Add certificate data to ManagedCentral response of fleet manager and use it to configure reencrypt route.
```
```
> pass through cert data to route

- .pre-commit-config.yaml
- .secrets.baseline
- CONTRIBUTING.md
- Makefile
See https://pre-commit.com/index.html.
This is an extensible mechanism for integrating pre-commit hooks.
I suggest to use the `detect-secrets` plugin. I have tried out `ripsecrets` but for some reason it did not catch some example secrets (high entropy secrets) I have added into the codebase for testing.
Installation instructions are behind the above link.
```
```
> Integrate pre-commit plugin detect-secrets

- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/handlers/validation.go
- internal/dinosaur/pkg/migrations/20220114114500_add_centrals.go
- internal/dinosaur/pkg/migrations/20220630220500_add_owner_userid_to_centrals.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/manageddinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
- pkg/auth/acs_claims.go
- pkg/auth/context_config.go
This PR passes auth provider config for `sso.redhat.com` from `acs-fleet-manager` to `fleetshard-sync`.
`sub` needed to be extracted from the token passed to `acs-fleet-manager`
This should close the work on [ROX-11063](https://issues.redhat.com/browse/ROX-11063) as well as help make progress on [ROX-11428](https://issues.redhat.com/browse/ROX-11428)
Manual test: 
1. Added logging to `fleetshard-sync`
2. Created central and looked into the central request sent to fleetshard-sync
> Pass auth config to fleetshard

- dp-terraform/helm/rhacs-terraform/README.md
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/README.md
- fleetshard/config/config.go
- fleetshard/config/config_test.go
- fleetshard/main.go
- fleetshard/pkg/fleetmanager/auth.go
- fleetshard/pkg/fleetmanager/auth_ocm.go
- fleetshard/pkg/fleetmanager/auth_rhsso.go
This is the second PR in a series of PRs to add additional authentication types to the fleetshard synchronizer.
This will include the following authentication options:
- OCM authentication using the refresh token instead of short-lived access tokens.
- RH SSO authentication using the client_credentials grant with client ID / secret to retrieve access tokens.
- Static token authentication for development using a non-expiring static token valid for the fleet manager's API.
This PR will do a couple of things:
- Conditionally adding the [token-refresher](https://gitlab.cee.redhat.com/mk-ci-cd/mk-token-refresher) (which is also used for the observatorium access token) to the Helm deployment. It will write a valid access token to a file within a shared volume of fleetshard sync and the token …
> Add RH SSO authentication within fleetshard sync.

- templates/service-template.yml
The wrong filename was used within the item of the configmap, leading to
```
E0704 15:38:18.408903 1 server.go:31] Unable to create authentication handler: keys file '/config/authentication/jwks-file-static.json' doesn't exist: stat /config/authentication/jwks-file-static.json: no such file or directory
```
> Use correct file name.

- templates/service-template.yml
The additional item's identation was not correctly formatted. 
This lead to the rendered config map to only contain a single item.
> Fix identation within the configmap

- e2e/e2e_test.go
- fleetshard/pkg/centralreconciler/reconciler.go
- fleetshard/pkg/centralreconciler/reconciler_test.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central.go
- internal/dinosaur/pkg/presenters/manageddinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- openapi/fleet-manager-private.yaml
- pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
The transition of central requests to `ready` does not work because of the cache implementation in fleetshard-sync skipping the second ready request required for state transition. It was fixed by only using the cache if central is not in ready state.
- Run operator, fleet-manager and fleetshard-sync
- Create central
- make sure it transitions to `ready`
- Reset your env (shutdown and delete everything you created)
- run e2e tests like documented in `e2e/README.md`
```
```
> fix central request transition to ready and add e2e for it

- dp-terraform/helm/rhacs-terraform/README.md
- dp-terraform/helm/rhacs-terraform/charts/observability/README.md
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
This PR provides two small tweaks:
1. Image from terraforming helm template is moved to `values.yaml` - this will help us define different images on staging/production/dev environments
2. Improved README to use helm upgrade command with `--create-namespace` - this helps when the OSD cluster is new and we do not have the required namespace created. This option will simply create it.
- ~[ ] Unit and integration tests added~ - this is not important for this PR
1. You can execute the following commands to test it:
```
cd dp-terraform/helm/rhacs-terraform
helm template rhacs-terraform \
--debug \
--namespace rhacs \
--values ./values.yaml \
--set fleetshardSync.image="test-image" .
```
After that check output and search for Deployment with the name `fleetshard-sync`. Check that the specified …
> Move image to values and improve README

- .github/workflows/ci.yaml
- Makefile
- internal/dinosaur/pkg/environments/development.go
- internal/dinosaur/pkg/environments/integration.go
- internal/dinosaur/pkg/handlers/authentication.go
- internal/dinosaur/pkg/routes/route_loader.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/test/integration/admin_dinosaur_test.go
- pkg/client/iam/config.go
- pkg/providers/core.go
- pkg/services/sso/iam_service.go
- pkg/services/sso/keycloak_service_builder.go
- pkg/services/sso/keycloak_service_proxy.go
- templates/secrets-template.yml
- templates/service-template.yml
This is the second PR in a series of PR to finalize refactorings on the SSO packages and related code.
The overall goal of this is to removed unused code and complexity that initially was used to support both MAS-SSO as well as RH SSO.
Here's an overview of changes done within the series of PRs:
- Rename `KeycloakService` to `IAMService`.
- Remove the `OSDService`.
- Remove every non-internal service account API on the `IAM Service`.
- Remove the `KeycloakBuilder` and `KeycloakProxy`.
For additional context and overview, see [the ticket](https://issues.redhat.com/browse/ROX-11287) as well as [the notes made together with
Kafkanians](https://docs.google.com/document/d/1nlEM15eC48PhK8ieleMAfIlPivvh-enp6aN2M7dyDLo/edit?usp=sharing).
Within the second PR, the `OSDKeycloakService` and its …
> ROX-11287: Remove OSDKeycloakService.

- .secrets.baseline
- README.md
When running the pre-commit against all files via:
```shell
$ pre-commit run --all-files
```
The `detect-secrets` had issues regarding undetected secrets.
Updated the `.secrets.baseline` file + audited it once more to make the pre-commit hook pass:
```shell
$ detect-secrets scan > .secrets.baseline
$ detect-secrets audit .secrets.baseline
```
```shell
$ pre-commit run --all-files
```
> Fix detect-secrets pre-commit hook.

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-rbac.yaml
Drop fleetshard-sync RBAC role lookup in the helm chart. With such check only every second deployment will create correct RBAC role for fleet.
Thanks @mtodor for spotting it
> Drop check for fleetshard-sync rbac existence

- .pre-commit-config.yaml
- README.md
Add [check-json](https://github.com/pre-commit/pre-commit-hooks#check-json) to the pre-commit configuration. As we use JSON files for configuration, it would be best to check for their syntax to avoid potential issues when 
deploying i.e. fleet manager.
```
pre-commit run --all-files
```
> Add check-json pre-commit plugin

- config/fleetshard-authz-org-ids-development.yaml
- internal/dinosaur/pkg/config/dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/util.go
- internal/dinosaur/pkg/services/util_test.go
This PR changes fleet-manager to use the external domain name scheme specified in this [ADR](https://github.com/stackrox/architecture-decision-records/blob/main/managed_service/ADR-0008-central-dns-name-scheme.md). I also tested that CNAME creation in Route53 works as expected. 
Manual testing:
```
make binary
make secrets/touch
cp dev/config/dataplane-cluster-configuration-minikube.yaml ./config/dataplane-cluster-configuration.yaml 
./fleet-manager serve --enable-dinosaur-external-certificate --dinosaur-domain-name "rhacs-dev.com"
export cluster_id=1234567890abcdef1234567890abcdef
fmcurl "rhacs/v1/agent-clusters/$cluster_id/centrals/status" -XPUT -d '{
"$central_id": {
"conditions": [
{
"type": "Ready",
"reason": …
```
> fix host name generation in fleet-manager

- Makefile
- build_deploy.sh
There were changes to the image tagging in the makefile. The script for appSRE deployment should be adjust accordingly. This should fix pipelines failures on stage env.
> ROX-11809: Fix app-interface deployment

- .golangci.yml
- .secrets.baseline
- internal/dinosaur/pkg/cmd/cloudprovider/providerlist.go
- internal/dinosaur/pkg/cmd/cloudprovider/regionlist.go
- internal/dinosaur/pkg/cmd/errors/list.go
- internal/dinosaur/pkg/converters/cluster.go
- internal/dinosaur/pkg/handlers/cloud_providers.go
- internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
- internal/dinosaur/pkg/presenters/metric.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- pkg/client/observatorium/api.go
The changes are workarounds so that gosec does not warn about
G601: Implicit memory aliasing in for loop.
```
```
> ROX-10835: enable gosec linter, add fixes to suppress warnings

- Makefile
- e2e/run_e2e_stage.sh
Add dedicated script for using on app-interface to make e2e flow more concise and manageable in the original repo.
Manually worked
```
$ e2e/run_e2e_stage.sh
...
plate.openshift.io/v1?timeout=32s
••••
------------------------------
• [SLOW TEST] [30.726 seconds]
Central should be created and deployed to k8s should transition central's state to ready
/Users/akurlov/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:95
------------------------------
••
------------------------------
• [SLOW TEST] [37.416 seconds]
Central should be created and deployed to k8s should remove central namespace
/Users/akurlov/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_test.go:119
------------------------------
Ran 8 of 8 Specs in 76.703 seconds
SUCCESS! -- 8 Passed | 0 Failed | 0 Pending | 0 …
```
> ROX-11469: Add dedicated script for running e2e on stage

- .openshift-ci/tests/e2e-test.sh
- .openshift-ci/tests/e2e.sh
- .secrets.baseline
Until now the bootstrapping was executed directly from within `e2e.sh` before any loggers are started, which means that if the bootstrapping fails then we don't see why it failed.
This PR shuffles the order so that `e2e.sh` takes care of starting loggers before bootstrapping (which is executed as part of the inner `e2e-test.sh` script).
```
```
> Don't swallow bootstrapping error logs

- dev/env/defaults/02-infra.env
- dev/env/scripts/lib.sh
The auto-sensing for infra clusters uses `kubectl` unconditionally. This produces (harmless) error messages on OSCI:
```
/go/src/github.com/stackrox/acs-fleet-manager/dev/env/defaults/02-infra.env: line 5: kubectl: command not found
```
This PR includes a fix, making sure that `kubectl` or `oc` will be used, depending on what is available.
```
```
> CI: Use oc instead of kubectl for auto-sensing for infra clusters

- .openshift-ci/build-root/Dockerfile
This extends the build root Dockerfile, which is used in CI as base image for all other pipeline images.
* Installs gotestsum, which can produce output looking good in CI.
* Download StackRox CRDs in order to reduce code duplication.
```
```
> Extend build root Dockerfile

- .secrets.baseline
- dev/env/defaults/00-defaults.env
- dev/env/defaults/cluster-type-infra-openshift/env
- dev/env/defaults/cluster-type-openshift/env
- dev/env/manifests/shared/03-configmap-config.yaml
- dev/env/scripts/lib.sh
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/client.go
- fleetshard/pkg/k8s/constants.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/runtime/runtime.go
- fleetshard/pkg/testutils/k8s.go
- go.mod
- go.sum
- internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
- internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
This PR adds route statuses reporting from the fleetshard sync to the Fleet Manager.
```
```
> ROX-11414: Send routes statuses

- dev/env/scripts/lib.sh
Seen a CI e2e failure, which was most likely be caused by a slow container startup.
```
```
> Increase wait timeout for CI e2e tests

- dev/env/scripts/lib.sh
If a container is slow to start, the kubectl command for retrieving that pod will fail. If that is not protected by `|| true`, then the whole bootstrapping will terminate with failure early.
```
```
> [CI] Fix container waiting logic

- .openshift-ci/build-root/Dockerfile
Again there were multiple HTTP 429 failures while fetching something from GitHub with curl.
I hope that this PR mitigates the problem.
```
```
> Use curl --retry when downloading from GitHub during image building

- .openshift-ci/build-root/Dockerfile
Add the `ocm` CLI to the Dockerfile, as it is required for E2E tests with the OCM auth type.
> Add ocm to Dockerfile.

- fleetshard/pkg/central/reconciler/reconciler.go
> Bugfix: Do not return nil in case namespace creation failed

- .secrets.baseline
- e2e/README.md
- e2e/e2e_auth_test.go
- fleetshard/config/config.go
- fleetshard/config/config_test.go
- fleetshard/main.go
- fleetshard/pkg/fleetmanager/auth_ocm.go
- fleetshard/pkg/fleetmanager/auth_rhsso.go
- fleetshard/pkg/fleetmanager/auth_static_token.go
- fleetshard/pkg/fleetmanager/client.go
- pkg/client/redhatsso/client.go
This PR will introduce the following:
- small refactor of the config within fleetshard, switchin from Singleton to non-singleton.
- added a E2E test suite for authN/Z tests.
The change of the config singleton was required within the test setup, as changes to i.e. the environment variable configuration was not propagated within the client.
This should generally be cheap and not too big of a disadvantage, as we only rely on the configuration when initially creating the Auth interface during startup of the fleetshard-synchronizer, but will
make our lifes definitely easier when using the client within tests.
The tests themselves cover the following:
- Use all three different auth types (RH SSO, static token, personalized OCM token).
- Check for the three API groups of fleet-manager whether …
> Add E2E test suite for authN/Z.

- .openshift-ci/build-root/Dockerfile
Need to use a later version of the OCM CLI, as the current version is failing when trying to run auth E2E tests within #201 .
Tested locally with this version and logging in with `client-id/client-secret` flags without any issues.
> Update OCM version used within CI Dockerfile

- templates/service-template.yml
typo, causing the maxUnavailable to not be set in the PDB and forbidding any pod deletion
None
> fix PodDisruptionBudget maxUnavailable typo

- .secrets.baseline
- fleetshard/pkg/central/reconciler/init_auth.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
- internal/dinosaur/pkg/config/dinosaur.go
- internal/dinosaur/pkg/environments/development.go
- internal/dinosaur/pkg/environments/stage.go
- internal/dinosaur/pkg/presenters/manageddinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- openapi/fleet-manager-private.yaml
- pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
Instead of hard-coding the issuer value of the auth provider, conditionally use either `sso.stage.redhat.com/sso.redhat.com` depending on the environment in which fleet manager is deployed.
By default, `sso.redhat.com` will be assumed. In dev / staging environments, `sso.stage.redhat.com` will be used.
Additionally, the flag `rhsso-issuer` can be used to manually set the issuer for i.e. testing purposes.
Besides that, there's a small QoL change: Based on the issuer, the auth provider is either named `Red Hat SSO` (for `sso.redhat.com`) or `Red Hat SSO (Stage)` (for `sso.stage.redhat.com`).
```
./fleet-manager serve --dataplane-cluster-config-file=<your-config> --rhsso-client-secret-file=<client secret>
CREATE_AUTH_PROVIDER=true CLUSTER_ID=1234567890abcdef1234567890abcdef OCM_TOKEN=$(ocm …
```
> ROX-11619: Make issuer configurable

- dev/env/defaults/cluster-type-colima/env
- dev/env/defaults/cluster-type-infra-openshift/env
- dev/env/defaults/cluster-type-openshift/env
Fix colima E2E test setup with docker runtime + fixes from the [previous review](https://github.com/stackrox/acs-fleet-manager/pull/197#discussion_r925264484)
```
```
> Fix colima test environment and review leftovers

- .openshift-ci/tests/e2e-test.sh
- dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
- pkg/server/server_config.go
- pkg/workers/leader_election_mgr.go
I was quite annoyed by the leader election so I implemented a switch to disable it for test environments.
```
```
> Allow for disabling leader election for test environments

- e2e/run_e2e_stage.sh
`STATIC_OCM_TOKEN` was added to the app-interface Vault CI mappings so we can use it in e2e staging tests instead of regular ocm token
> Use STATIC_OCM_TOKEN instead of regular one in e2e staging tests

- .openshift-ci/build-root/Dockerfile
- .openshift-ci/build-root/centos.repo
Looking at the failure here https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_acs-fleet-manager/230/pull-ci-stackrox-acs-fleet-manager-main-images/1554101901472043008 I have the feeling that OpenShift CI doesn't like `COPY` directives for Dockerfiles referenced from within `openshift/release`.
```
```
> Embed centos repo configuration in Dockerfile

- .openshift-ci/build-root/Dockerfile
> Remove heredoc from Dockerfile

- .openshift-ci/build-root/Dockerfile
According to https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_acs-fleet-manager/230/pull-ci-stackrox-acs-fleet-manager-main-images/1554115653571448832 we need git installed in the root image.
```
```
> Install git in custom root image

- .openshift-ci/build-root/Dockerfile
Apparently gcc is required during execution of `go test`, which uses `cgo` under the hood. See https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_acs-fleet-manager/230/pull-ci-stackrox-acs-fleet-manager-main-e2e/1554160585518616576.
```
```
> CentOS root image: Install gcc

- Makefile
- dev/env/defaults/cluster-type-openshift-ci/env
Use `gotestsum` in CI instead of plain `go test`, because the former can be configured to use an output formatter suitable for CI use (no color escape codes -> easier to read).
The `Makefile` has already some support for `gotestsum` built-in, I am only modifying is such that it can *also* use a system-wide installed `/usr/local/bin/gotestsum` (we have this in our CI root image) instead of a locally built one.
```
```
> Use gotestsum in CI

- .secrets.baseline
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/testutils/k8s.go
- internal/dinosaur/constants/cluster.go
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
- internal/dinosaur/pkg/api/private/model_data_plane_central_status_routes.go
- internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
- internal/dinosaur/pkg/presenters/dinosaur.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/services/data_plane_dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/util.go
- openapi/fleet-manager-private.yaml
This PR aligns the routes creation implementation with URI scheme we decided to use in the ADR.
Previously there was a heuristic approach to determine a hostname using a prefix and subdomain. After this change, UI and data hostnames can be set separately on the fleetmanager with any pattern we want.
Tested manually on a dedicated OSD cluster
```
```
> ROX-11862: Match DNS name to the ADR

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/route.go
This PR adds an ability to create and delete an additional passthrough route from the fleetshard sync. The intension is to set a custom hostname. This is currently not possible on the SRox operator side
Tested manually on the dedicated OCM cluster
```
```
> ROX-11917: Create passthrough route from the fleetshard sync

- .openshift-ci/tests/e2e.sh
- .secrets.baseline
If it is not set in the environment the e2e script will abort with an error.
I noticed some linter complaints (shellcheck) and have fixed the issues in one go.
And I have removed a secrets from the baseline and added the pragma annotation in the shell script directly to reduce merge conflicts in the future.
```
```
> CI E2E Tests: Make sure that RUN_AUTH_E2E variable is initialized

- e2e/e2e_auth_test.go
We have the issue that **all** e2e tests are skipped if RUN_AUTH_E2E was not set, but it should only skip **auth** e2e tests. For more context see:
https://issues.redhat.com/browse/ROX-12073
```
```
> do not skip all tests if RUN_AUTH_E2E not set

- docs/development/setup-developer-osd-cluster.md
Small fixes discovered during testing of the guide:
1. fixed usage of the `RHACS_OPERATOR_CATALOG_NAME` variable in the execution of helm terraform template. This is required to support ACS Operator installed via RH Marketplace and custom deployed ACS operator
2. fixed issues with swapped Linux and macOS commands for extending the lifetime of the OSD cluster
1. This can be tested by following the guide where the custom ACS Operator is not installed (skip steps 6. and 7.).
2. Can be simply tested by running commands in macOS and/or Linux
> Small fixes for setup dev OSD cluster guide

- .secrets.baseline
- internal/dinosaur/pkg/services/dinosaur.go
Set `deletion_timestamp` for special cases when centrals are deprovisioned during the fleet manager reconciliation.
~- [ ] Documentation added if necessary~
Tested on a local cluster
```
```
> ROX-11934: Fix DB status for Central stays on deprovision

- .openshift-ci/tests/e2e.sh
1. There was an access to an uninitialized variable in case `RUN_AUTH_E2E=true` and `OCM_OFFLINE_TOKEN` is unset.
```
$ ./.openshift-ci/tests/e2e.sh 
** Entrypoint for ACS MS E2E Tests **
Cluster type: infra-openshift
Cluster name: mc-test
Image: quay.io/rhacs-eng/fleet-manager:v0.0.0-178-ge60a311383
Log directory: (none)
Executing Auth E2E tests: true
Setting up authentication related environment variables for auth E2E tests
./.openshift-ci/tests/e2e.sh: line 64: OCM_OFFLINE_TOKEN: unbound variable
```
2. It seems to me that some lines related to the (re-)exporting of `STATIC_TOKEN` were not required: In case we are running in CI this export has already been done at the top of the script. And if we are not running on CI the expectation is that the user has the environment set up properly …
> [CI Test Env] Prevent access to uninitialized variable and simplify propagation of static token

- dp-terraform/helm/rhacs-terraform/README.md
- dp-terraform/helm/rhacs-terraform/charts/logging/.helmignore
- dp-terraform/helm/rhacs-terraform/charts/logging/Chart.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/README.md
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-01-subscription.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-02-secret-cloudwatch.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-logging.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/README.md
- dp-terraform/helm/rhacs-terraform/values.yaml
This PR adds a logging stack to the terraforming helm template for the data plane.
**Notes**
- We have added post-install/update hooks to avoid the problem of missing custom resource definitions. The problem here is that custom resource definitions are installed after the Subscription is applied for the logging operator. Usually, it takes some time for it to be applied. And that can cause problems that custom resource definition does not exist when the helm is creating custom resource. With helm post hook, custom resources will be created after everything else is successfully deployed. *still to be properly tested*
- All logging stack is deployed into the `openshift-logging` namespace. This is a namespace defined for it.
- Some resources have predefined names. i.e. `instance` - please …
> ROX-12046: Add logging helm chart for data plane logging stack

- dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Use manual install approval plan to control operator upgrades. Fleetshard-sync later will approve manual upgrades for the operator after an API trigger.
> ROX-12215 - ACS operator use manual install approval plan

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-pagerduty.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
[ROX-11614](https://issues.redhat.com/browse/ROX-11614) - Setup ACS PagerDuty as backend for alerting rules.
```sh
$ helm template . --namespace rhacs --set "pagerduty.key=abcdef" | grep -A2 -B9 KEY
apiVersion: v1
kind: Secret
metadata:
name: rhacs-pagerduty
namespace: rhacs-observability
labels:
configures: observability-operator
stringData:
PAGERDUTY_KEY: "abcdef"
type: Opaque
---
```
> ROX-11614: Add PagerDuty secret to the observability helm chart

- dev/env/scripts/bootstrap.sh
I once stumbled upon the problem that the bootstrap script terminated due to this without any error output.
```
```
> Improve error output in bootstrap script in case K8s cannot be reached

- templates/service-template.yml
- Map dataplane cert from from the appSRE Vault
- Drop redundant fake dataplane cert configmap
> Use vault secret for dataplane certificate

- dev/env/defaults/cluster-type-openshift-ci/env
This PR makes e2e test output more verbose. Currently it is not clear which steps were passed and which were skipped.
Since we have only one test - the output with the `testname` format is very short.
```
```
> Make e2e test output more verbose

- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
This allows updating the cluster_dns column in the `clusters` table in the DB.
```
```
> Reconcile ClusterDNS

- e2e/run_e2e_stage.sh
Use env based  data plane `cluster_id` in e2e staging tests. This env is mapped from `acs-fleet-manager-ci/e2e/data-plane-cluster-id` appSRE vault secret
`
> Read data plane cluster id for staging e2e from env

- .openshift-ci/build-root/Dockerfile
Tried building locally and it failed with:
```
Step 3/22 : RUN dnf update && dnf -y install make which git gettext jq gcc
---> Running in bf3af5cc1930
CentOS Stream 9 - BaseOS                        5.3 MB/s | 5.8 MB     00:01    
CentOS Stream  - AppStream                      4.0 MB/s |  15 MB     00:03    
Last metadata expiration check: 0:00:01 ago on Wed Aug 24 07:42:08 2022.
Dependencies resolved.
================================================================================
Package                   Arch     Version                      Repo      Size
================================================================================
Upgrading:
crypto-policies           noarch   20220815-1.git0fbe86f.el9    baseos    81 k
crypto-policies-scripts   noarch   20220815-1.git0fbe86f.el9 …
```
> CI build root image: Change dnf update command

- templates/service-template.yml
Fix the secret reference for aws credentials in stage fleet-manager deployment
```
```
> fix secret reference for aws stage

- docs/development/test-locally-route-hosts.md
- scripts/ingress-router.sh
This change simplifies routes configuration on vanilla k8s. With new script commands you can easily and interactivally add and remove exposed hosts locally  
```
```
> ROX-12052: Add script commands for quickly adding/removing hostnames locally

- fleetshard/pkg/central/reconciler/reconciler.go
The reconcile cache should be set after all steps were successfully completed. Here it was set before the SSO provider was initiliazed.
This can lead to skipped reconciles if the SSO registration fails, the reconciler returns. On the next reconcile the Central CR is still the same and the SSO config is never created.
Fixable by restarting fleetshard-sync.
> Fix reconcile cache

- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/testutils/k8s.go
This PR adds a few unit tests to ensure that there is no inconsistent state when the routes are sent to the fleet manager
Build is green
```
```
> ROX-11729: Add unit tests to ensure that routes are sent at once

- .openshift-ci/tests/e2e.sh
- Makefile
- go.mod
- go.sum
Use ginkgo instead of gotestsum for e2e test suite.
Executed `go get github.com/onsi/ginkgo/v2/ginkgo`.
```
```
> Use ginkgo instead of gotestsum for e2e test suite

- Makefile
- pkg/client/iam/client.go
- pkg/client/iam/gocloak_moq.go
I think we're currently misusing the vendor directory concept. It is used only to mock *one* interface. Each dependency update requires `go mod vendor` because of that.
```
```
> Get rid of vendor directory

- fleetshard/pkg/central/reconciler/errors.go
- fleetshard/pkg/central/reconciler/init_auth.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/runtime/runtime.go
This change adds a few optimizations dedicated to reduce a number of status reports back to the fleet manager. The changes are:
1. Skip sending an update when central is **ready** and not changed (revert to the previous state)
2. Skip sending an update when central is **installing** and not changed.
3. Do not return and print errors when central is not ready (secrets, deployments) not created.
4. Return "skippable" error instead of `nil` to indicate that deletion is in progress
5. Minor fixes to cache and pointer reference
```
```
> ROX-12072: Route update optimizations

- dev/env/scripts/down.sh
When debugging issues in the e2e test suite it happens easily that we have to cleanup leftovers. In my opinion it makes sense to integrate this into `down.sh`.
```
```
> Delete leftover namespaces in down script

- dev/env/scripts/bootstrap.sh
- dev/env/scripts/lib.sh
- dev/env/scripts/up.sh
Yesterday I wanted to setup a test environment for testing purposes, but `docker.io` was having stability issues. Since the test env scripts unconditionally try to `docker login` and `docker pull`, I was blocked by the `docker.io` outage.
With these modifications the test environment setting up skips `docker login` and `docker pull` if not necessary.
```
```
> Work around docker.io outages

- README.md
- go.mod
- go.sum
- openapi/fleet-manager-private-admin.yaml
- tools.go
What worked previously -- executing `go run github.com/onsi/ginkgo/v2/ginkgo` -- doesn't work anymore:
```
$ go run github.com/onsi/ginkgo/v2/ginkgo
../../../../pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/ginkgo/generators/bootstrap_command.go:9:2: missing go.sum entry for module providing package github.com/go-task/slim-sprig (imported by github.com/onsi/ginkgo/v2/ginkgo/generators); to add:
go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.1.4
../../../../pkg/mod/github.com/onsi/ginkgo/v2@v2.1.4/ginkgo/internal/profiles_and_reports.go:12:2: missing go.sum entry for module providing package github.com/google/pprof/profile (imported by github.com/onsi/ginkgo/v2/ginkgo/internal); to add:
go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.1.4
$
```
Reading the [Ginkgo …
> Make sure Ginkgo CLI dependencies exist

- dev/env/scripts/up.sh
Default to `quay.io/rhacs-eng/fleet-manager` repo, when `FLEET_MANAGER_IMAGE` does not seem to be a full image reference.
```
```
> Support setting FLEET_MANAGER_IMAGE to a simply image tag instead of a complete image reference

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Fetch PagerDuty integration key from BitWarden and pass it to helm.
Tested locally by running the `terraform_cluster.sh`.
> ROX-11614: Pass pagerduty key value to helm

- docs/legacy/feature-flags.md
- fleetshard/pkg/central/reconciler/init_auth.go
- internal/dinosaur/pkg/config/central.go
- internal/dinosaur/pkg/environments/development.go
- internal/dinosaur/pkg/environments/integration.go
- internal/dinosaur/pkg/environments/stage.go
- internal/dinosaur/pkg/presenters/managedcentral.go
Currently, RH SSO `client_id` which is passed to Central to configure SSO is hard coded. This PR makes it configurable.
In addition, a doc entry for `rhsso-issuer` config param is added and SSO name deduction supports more than just stage or prod RH SSO.
```
```
> ROX-11593: Made RH SSO client_id configurable

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
`observability.gateway` -> `observability.observatorium.gateway`.
This misconfiguration led to Prometheus remote write failures on the
stage cluster.
`observability.enabled=true` is already the default, therefore removed
it from the values.
> Fix and clean up observatorium settings

- templates/service-template.yml
`fleet-manager-credentials` is more precise name for credentials Vault secret.
`fleet-manager-credentials` [mapping is already created on app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/namespaces/acs-fleet-manager-stage.yml#L35)
> ROX-12451: Rename fleet-manager to fleet-manager-credentials vault secret name

- dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
- dev/env/manifests/rhacs-operator/quay/03-subscription.yaml
- e2e/e2e_test.go
- fleetshard/pkg/central/charts/data/tenant-resources/config/squid.conf
- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
- fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
- fleetshard/pkg/central/reconciler/proxy.go
- fleetshard/pkg/central/reconciler/proxy_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/testutils/k8s.go
This creates 2 replicas of a squid web proxy as egress proxies alongside Central, as described in the [design doc](https://docs.google.com/document/d/1LJwDx8P-Xx9mpmej__QWqUrbjJh_gtGJbKiMFvAoA1w/edit#heading=h.1h3ev6pf6wey).
- Deployed manually
- E2E test added and verified that it passes.
> ROX-12468: Deploy and configure egress proxies for each tenant

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Explicitly expose the metrics port for fleetshard-sync in the deployment description with name "monitoring". This way prometheus should be able to scrape the endpoint.
```
```
> expose fleetshard-sync metrics port with name monitoring

- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/presenters/managedcentral.go
fleetshard-sync hold a map in memory with instances of a Reconciler for each central. When a central gets deleted and no longer appears in the response from fleet-manager's API the Reconciler instance is not deleted. This leads to a growing Map of Reconciler instances and potential out of memory issues if many central instances are created and deleted 
```
```
> fix memory leak in reconciler map of fleetshard-sync

- dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Replace fixed interval with dynamic one to make. 
Any peak or dip would be "smeared" in fixed 10 minutes interval. So the fixed interval might hide any sudden activity on charts.
In addition, there is a small visual tune with filled capacity
> Replace fixed interval with dynamic one

- .secrets.baseline
- Makefile
- docs/legacy/feature-flags.md
- internal/dinosaur/pkg/config/central.go
- internal/dinosaur/pkg/environments/development.go
- internal/dinosaur/pkg/environments/integration.go
- internal/dinosaur/pkg/environments/stage.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- templates/secrets-template.yml
- templates/service-template.yml
Fleet manager config has several knobs mentioning "sso", "client secret", or alike in their names:
* `--observability-red-hat-sso-logs-client-id-file`
* `--redhat-sso-client-secret-file`
* `--ocm-client-secret-file`
* `--rhsso-client-secret-file`
`--redhat-sso-client-secret-file` and `--rhsso-client-secret-file` look particularly confusing. To avoid that, this PR aims to rename the latter (and those from the same `--rhsso-*` family) to `--central-idp-client-secret-file` (`--central-idp-*`).
Also mount entry for `rhsso-client-secret` in "templates/service-template.yml" is replaced by a different location ([stage Vault](https://vault.devshift.net/ui/vault/secrets/app-interface/show/acs-fleet-manager/stage/service/credentials) has been updated accordingly).
CI run.
> Avoid RHSSO in Central auth config for clarity

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
The operator subscription was not installed successfully because the catalog source was `rhacs-operators` instead of `redhat-operators`.
- Manual provisioning
> ROX-12499 - Fix operator subscription to `redhat-operators`

- .secrets.baseline
- Makefile
- templates/service-template.yml
This change is created to help us choose the correct clientId in [app-interface](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/cicd/saas.yaml) repo.
This PR should not be merged until `CENTRAL_RHSSO_CLIENT_ID` variable is set up in app-interface repo, otherwise staging and prod will provide incorrect auth provider in Central creation.
-
> Add CENTRAL_RHSSO_CLIENT_ID variable to service-template.yml

- fleetshard/pkg/central/reconciler/proxy.go
- fleetshard/pkg/central/reconciler/proxy_test.go
Because `NO_PROXY` is assembled by ranging over a map, it might be non-deterministic. This causes the pods to be recreated on every reconcile, which is bad.
Sort the list of `NO_PROXY` targets to ensure a deterministic output.
Ran unit test
> Make NO_PROXY value deterministic

- .secrets.baseline
- cmd/fleet-manager/main_test.go
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/config/central.go
- internal/dinosaur/pkg/environments/integration.go
- internal/dinosaur/pkg/migrations/20220826000000_add_auth_config_to_centrals.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
- internal/dinosaur/providers.go
Prior to this PR, only "static" RHSSO setup for Central is possible, hence `CentralRequest` is augmented right upon being presented to fleetshard. This will not be possible once RHSSO setup becomes more involved, e.g., talking to some API.
In preparation to supporting such involved RHSSO setup, this PR moves augmentation code into a separate "worker", which configures RHSSO in a non-blocking way.
**Note**: it's unclear how to add an E2E test using currently available testing framework. What we probably need to add in follow-up PRs is an ability to query a deployed Central to be able to at least check if an auth provider has been configured as expected (without checking the configuration allows logging in).
Verified in the CI run status transitions of Central request up to Provisioning.
> ROX-12155: Move Central's IdP setup to a worker

- fleetshard/pkg/fleetmanager/client.go
- fleetshard/pkg/fleetshardmetrics/metrics.go
- fleetshard/pkg/fleetshardmetrics/metrics_test.go
- fleetshard/pkg/fleetshardmetrics/server_test.go
- fleetshard/pkg/runtime/runtime.go
Added more metrics to the initial implementation of the metrics server for fleetshard-sync component.
```
```
> ROX-12406: add more metrics to fleetshard-sync

- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
Specify `command` explicitly for the `egress-proxy` container overrides the entrypoint script. This ensures the egress proxy works with both the `ubuntu/squid` and the `ose-egress-http-proxy` image.
- CI
- Tested in "prod"
> ROX-12571: Use explicit egress proxy command to override entrypoint

- dp-terraform/osd-cluster-idp-setup.sh
Add a script that will automate the creation of the IdP for OSD clusters and configure the allowed users that will be granted administrative rights.
The IdP will use (for staging) auth.redhat.com.
The reason there needs to be a list of allowed users comparatively to a rover group is due to non-support of OCM for group syncing (Kafka does it in the same way but with a sync set, which periodically syncs the access for this 
:-)). This should be enough for us though.
For production, the same OIDC client sadly cannot be re-used. That's due to the redirect_uri not allowing wildcards. For this, we need to order another one and update this script afterwards (for now, I also added the HTPasswd 
creation automation).
```
./dp-terraform/osd-cluster-idp-setup.sh stage acs-stage-dp-01
```
> ROX-12251: Create IdP for OSD cluster

- .gitignore
- internal/dinosaur/pkg/migrations/202209141000_add_central_auth_lease_type.go
- internal/dinosaur/pkg/migrations/migrations.go
Witihin [pull/334](https://github.com/stackrox/acs-fleet-manager/pull/334) we've added a new worker type `central_auth_config`, which is responsible later on for creating the dynamic OIDC client for central's auth provider.
When starting the fleet manager, you will receive the following error message within the logs:
```
I0914 03:20:12.406221   24111 leader_election_mgr.go:127] failed to acquire leader lease: expected to find a lease entry, found none for :central_auth_config
```
Diving deeper into the code of leader_election_mgr, we see the following lines that are the culprit of the error ([code 
ref](https://github.com/stackrox/acs-fleet-manager/blob/a0d43f031545373c2fe7c774619260c26decb4fc/pkg/workers/leader_election_mgr.go#L151-L154):
```go
// we failed to read the current lease, we …
```
> Fix acquiring lease for central_auth_config worker

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
This is a follow-up from [pull/3024](https://github.com/stackrox/stackrox/pull/3024) which introduced a new setting within the helm chart speficially for managed services: `._rox.env.managedServices`.
The operator will set this setting to true if the annoation `platform.stackrox.io/managed-services` is set to true on the central CR.
This will lead to the following:
- OpenShift Auth will be disabled (we don't want customers to get information about the infrastructure their managed central is running on).
- the ROX_MANAGED_CENTRAL variable will be set within central. This leads to certain features being disabled (i.e. basic password login will not be shown within UI and other administrative features will be removed).
```
make ocm/setup …
```
> ROX-12182: Set managed service annotation on central CR

- scripts/openshift-router.sh
This pull request fixes the openshift route deployment. The YAML manifests are pinned to the latest version, now our pin to 4.11.
- Manual testing running `make deploy/openshift-router`
> Fix OpenShift router deployment for k8s clusters

- docs/development/setup-developer-osd-cluster.md
This PR is adding a few small improvements to documentation for the setup of a development OSD cluster.
The following things are changed:
- improved step for login via `ocm` command to help with fetching of token
- bumped version of Central operator and improved that only one place is required to be updated in the future
- bumped OSD version to 4.11
- added persisting admin password to a local file. Can be useful if someone closes the shell with env var.
I didn't test it directly, but this was a list of improvements collected on a few occasions where I helped other team members to set up …
> Improve setup development OSD docs

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This PR changes Prod Fleet-Manager endpoint to use API gateway URL.
- ~[ ] Documentation added if necessary~
We have tested that API exists and it's accessable. You can run the following command:
```
curl --header "Authorization: Bearer $(ocm token)" https://api.openshift.com/api/rhacs/v1/centrals --silent | jq
```
If everything works can really be tested after production is re-terraformed.
> Change prod fleet-manager endpoint URL to use API gateway

- fleetshard/pkg/central/reconciler/init_auth.go
Following up on https://issues.redhat.com/browse/ROX-11017 to make auth provider and groups created by `fleetshard-sync` immutable
None
> ROX-12179: Immutable auth provider and groups

- dev/env/scripts/lib.sh
QoL change that will ensure we error out within the `init` function that is called when running `.openshift-ci/tests/e2e-test.sh` if `CENTRAL_IDP_CLIENT_SECRET` is not set.
If the variable is not set, central will be unable to start.
> Fail if CENTRAL_IDP_CLIENT_SECRET is not set

- docs/development/setup-developer-osd-cluster.md
- dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
This adds preparation to deploy an upstream version of the operator to a dataplane cluster using the `dp-terraform/helm/terraform-cluster.sh` script.
It's not set in stone whether we want to do it _exactly_ in this way, but at the very least this works in a rough state and we can remove it once we have found a better way to deploy the operator.
In detail, the following has been done based on [the existing documentation of adding an upstream operator](https://github.com/stackrox/acs-fleet-manager/blob/main/docs/development/setup-developer-osd-cluster.md#prepare-cluster-for-rhacs-operator):
- Add scripts for adding the pull secret for `quay.io/rhacs-eng` to the global pull secret of the OSD cluster (using the credentials within BitWarden).
- Expose a new helm setting …
> Deploy a non-released operator version with Helm

- .openshift-ci/build-root/Dockerfile
- dev/env/scripts/lib.sh
Update yq in root Dockerfile (also: turn version numbers into ARGs to separate them from the Dockerfile RUN commands).
Use the newer invocation style for yq, getting rid of warnings like: Flag --tojson has been deprecated, please use -o=json instead.
CI e2e run should fail, since the change in `yq` is already taking effect but the build-root Dockerfile is taken from the main branch.
```
```
> Test Env: Update yq to get rid of annoying deprecation warnings.

- dev/env/scripts/lib.sh
Central is stuck in provisioning in e2e Tests if external certificate is enabled without route53 credentials. So this changes set it to false in case no credentials for route53 were provided.
```
```
> enable central external certificate only if route53 credentials are set

- dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
- dev/env/scripts/up.sh
Currently fleet-manager within the TestEnv can only be deployed by using the `up.sh` script. But, this script is doing a lot of initialization and sometimes, during development, it would be sufficient to do quickly do something like:
```
dev/env/scripts/delete dev/env/manifests/fleet-manager/deployment.yaml
make image/build/local
dev/env/scripts/up dev/env/manifests/fleet-manager/deployment.yaml
```
But this flow currently doesn't work anymore, since the deployment YAML references a mandatory variable `FLEET_MANAGER_COMMAND`, which is not initialized as part of the `lib.sh:init` initialization, but only in `up.sh`.
I don't remember the exact rationale behind this, @johannes94 am I overlooking something here?
This PR simply get rids of the variable -- I am assuming that it's value is …
> TestEnv: Fix standalone deployment of fleet-manager

- docs/auth/admin-api.md
Add documentation for how to access the admin API, including pre-reqs on the required groups as well as how to retrieve an auth token from internal SSO.
> Add documentation for admin API access

- e2e/e2e_test.go
The test for updating central resource usage through the admin API, was broken. Requested CPU was higher than the limit CPU after sending the update request. We didn't see the test failing because it only tests that the central CR had it's resource requirements updated. Not that also the deployment created by the operator was updated.
```
```
> set limits greater than requests for admin e2e test

- internal/dinosaur/pkg/cmd/cloudprovider/regionlist.go
- internal/dinosaur/pkg/cmd/observatorium/get.go
- internal/dinosaur/pkg/cmd/observatorium/query.go
- internal/dinosaur/pkg/cmd/observatorium/query_range.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/metrics.go
- internal/dinosaur/pkg/handlers/service_status.go
- internal/dinosaur/pkg/handlers/validation_test.go
- internal/dinosaur/pkg/services/clusters.go
- internal/dinosaur/pkg/services/data_plane_cluster.go
- internal/dinosaur/pkg/services/data_plane_dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/observatorium_service.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
- internal/dinosaur/test/common/dinosaur_pollers.go
- pkg/errors/errors.go
I went through all the string literals in the codebase that contain "dinosaur", and changed them to "central" (or "Central", or "centrals") in the following cases:
- they are part of error messages
- they are part of log messages
- are outputted by CLI tools
Left everything else untouched.
~~- [ ] Documentation added if necessary~~
~~- [ ] CI and all relevant tests are passing~~
> ROX-12742: rename "dinosaur" to "central" in error messages and logs

- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/pkg/migrations/20220916000000_add_skip_scheduling_to_clusters.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/services/cluster_placement_strategy.go
- internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
- internal/dinosaur/pkg/services/clusters.go
- internal/dinosaur/pkg/services/clusterservice_moq.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- pkg/api/cluster_types.go
Implemented 2 cluster placement strategies for central:
- DefaultClusterPlacementStrategy
- first cluster in Ready state that has SkipScheduling set to false for central
- is enabled by default
- TargetClusterPlacementStrategy
- allows to specify a command line flag `-dataplane-cluster-target`, if that flag is set centrals are placed 
```
```
> new cluster placement strategies

- e2e/admin_client_api.go
- e2e/e2e_test.go
- internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
- internal/dinosaur/pkg/api/admin/private/api_default.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/routes/route_loader.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
- openapi/fleet-manager-private-admin.yaml
See https://issues.redhat.com/browse/ROX-12743. This PR implements a new DELETE endpoint as `/api/rhacs/v1/admin/dinosaurs/db/{CENTRAL ID}`.
```
```
> ROX-12743: Provide fleet-manager endpoint for manually deleting tenants in the database

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
Update dataplane terraforming to deploy rhacs operator v3.72 and pin the fleetshard-sync deployment to a specific commit hash. 
```
```
> fix fleetshard version on stage and upgrade to v3.72

- fleetshard/pkg/central/reconciler/init_auth.go
Within [pull/397](https://github.com/stackrox/acs-fleet-manager/pull/397), the default group (the group which only has the auth provider ID set), was incorrectly declared as immutable.
When developing the feature of adding immutability to groups within [pull/2663](https://github.com/stackrox/stackrox/pull/2663), the expection was done for default groups to **not** be immutable ([see here](https://github.com/stackrox/stackrox/pull/2663/files#diff-dcb0ff277bf5c2b44fe253a6f5dcbf331b017ee6c8594ddce08f47f48c069e65R44-R47)).
The reasoning for a default group to not be immutable is that customers shall have the possiblity to change the default group for non-administrative users from `None` to a role of their choice.
If the group would be immutable, this wouldn't be the case and only the …
> Do not make the default group immutable

- fleetshard/pkg/central/reconciler/init_auth.go
Addendum to https://github.com/stackrox/acs-fleet-manager/pull/446.
By default, an auth provider is activated upon first user log in. This activation modifies auth provider via [`WithValidateCallback()`](https://github.com/stackrox/stackrox/blob/65e557c81746314df201508a1f37576ebdc3060a/pkg/auth/authproviders/provider_options.go#L101) which in turn calls [`UpdateAuthProvider()`](https://github.com/stackrox/stackrox/blob/5fca258dcedc15748bbd7957ea4d5fc7fbec2a48/central/authprovider/datastore/datastore_impl.go#L64) and breaks in `verifyExistsAndMutable()` because the auth provider is immutable.
This PR work arounds the problem by creating the auth provider already in the active state.
Long-term solution is moving from call ACS API to declarative configuration.
Tested by Daniel on a …
> ROX-12836: Ensure authprovider is created already active

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
We've pinned the deployed version of stage/prod to the image with first 7 letters of the commit hash in the AppSRE image repository. The version for prod was deployed during the debugging session for our Service Preview. The version for prod/stage are different because I updated stage today to the latest image used by fleet-manager in order to fix the SSO issue for stage. I didn't want to deploy prod with that version yet, since we're planning to put out another version today once https://issues.redhat.com/browse/ROX-12842 is done
~- [ ] Documentation added if necessary~
~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to …
> version bump for fleetshard-sync

- pkg/client/ocm/client.go
This log statement is added to debug a panic within the `Send` of the OCM sdk client library.
```
```
> Log OCM request to retrieve org id

- dev/env/defaults/00-defaults.env
- dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
- internal/dinosaur/pkg/services/cluster_placement_strategy.go
- internal/dinosaur/pkg/services/cluster_placement_strategy_moq.go
- internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
- internal/dinosaur/pkg/services/dinosaur_test.go
Added validation to the ClusterPlacementStrategies to not schedule central requests to clusters that don't support the instancetype of that request. This enables us to allow/block eval instance creation based on `dataplane-cluster-configuration.yaml`
```
```
> change ClusterPlacementStrategies to validate instance type

- docs/auth/admin-api.md
Fix the changed API path from `dinosaurs` to `centrals`.
> Fix the admin API path in docs

- Makefile
- e2e/e2e_suite_test.go
It seems that the recent flakes in CI e2e tests are caused by a timeout being configured to low for our e2e tests.
n/a
```
```
> CI Test Env: Fix timeout issue (hopefully)

- .golangci.yml
- Makefile
- dp-terraform/add-on/rhacs-terraform/Makefile
- dp-terraform/add-on/rhacs-terraform/config/rbac/role.yaml
- dp-terraform/add-on/rhacs-terraform/pkg/terraform/values/translation/translation.go
- dp-terraform/add-on/rhacs-terraform/pkg/values/translation/values_builder.go
- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/converters/resourceutil.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/services/cluster_placement_strategy.go
- internal/dinosaur/pkg/services/data_plane_cluster.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/test/integration/require_terms_acceptance_middleware_test.go
Revised all TODO(create-ticket) comments. Removed the (create-ticket) annotations on all TODOs on which we don't know if and when we need to work on them. For example for cluster terraforming and addon operator. That left us with only a few TODO(create-ticket) comments left. All of them are already addressed, and should be done in the next 1-2 weeks.
```
```
> cleanup TODO(create-ticket) comments

- .secrets.baseline
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
This PR augments central requests with Central IdP OIDC client data by using dynamic clients API provided to us by CIAM team.
Changes within this PR:
* call to RHSSO dynamic clients API to get OIDC client data
* GetIssuer() method in IAMService to avoid us depending on a config value
* Truncate name according to dynamic clients API limitation
* Limit client creation requests only to centrals with already set `host`
0. **Remove orgId check:** https://github.com/stackrox/acs-fleet-manager/blob/667ae5a81952f3508742e905a6f57b502e1fbcd9/fleetshard/pkg/central/reconciler/init_auth.go#L156-L161 
1. Deploy `fleetshard-sync` to OSD cluster with `sso.stage.redhat.com` service account auth:
```
helm -n $NAMESPACE install rhacs-terraform dp-terraform/helm/rhacs-terraform/ \ …
```
> ROX-12157: Implement augmentWithDynamicAuthConfig

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This PR will bring minor improvements to the terraform script:
- Skip with execution if CLUSTER_ID is empty. Previously, this was undetected and installed the chart, which lead to a CrashLoopBackOff from fleetshard-sync when an incorrect cluster name was provided (e.g. typo).
- Make sure the script is callable from a _different_ directory. Previously, it was only callable when navigating to `dp-terraform/helm/rhacs-terraform`.
~~- [ ] Documentation added if necessary~~
```
./dp-terraform/helm/rhacs-terraform/terraform_cluster.sh stage invalid-name …
```
> Minor improvements to terraform script

- templates/service-template.yml
Correct config values are located in `fleet-manager-credentials` secret.
CI should be enough
> ROX-12158: fix redhatsso clientId/clientSecret values

- templates/service-template.yml
- `topologyKey: "kubernetes.io/hostname"` will suggest the orchestrator to avoid deploying pods in the same host name
- drop `podAffinityTerm` because there is only one condition so specifying `weight` is redundant
Details https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
Will test stage deployment
> ROX-12640: Prefer schedule replicas on different nodes

- internal/dinosaur/pkg/config/central.go
1. Remove logging secret status as unnecessary: we either use static auth and fail if secret is empty, or we do not care.
2. Read secret only when it's needed - when static auth is enabled
1. `./fleet-manager serve` - doesn't log anything if secret is not-empty, fails if empty
2. `OCM_ENV=stage ./fleet-manager serve` - doesn't care if secret is empty or not
Note: `OCM_ENV=stage` doesn't have static client ID assigned, that's why it works that way
> Read central-idp-client-secret-file only when static auth is enabled

- fleetshard/pkg/central/reconciler/init_auth.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- openapi/fleet-manager-private.yaml
With dynamic client registration, there is no need for `org_id` check - we will get by with `aud` check instead.
1. Deploy fleet* without dynamic clients config, create Central
2. Log in into central and verify required attributes check is there 👍
> ROX-12946: Remove org_id requirement in Central IdP

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
Now that `image:` points at a more or less immutable tag, these are no longer needed.
Ref: discussion in https://github.com/stackrox/acs-fleet-manager/pull/406
Not applicable.
> Remove update-trigger-like annotations.

- e2e/e2e_suite_test.go
- fleetshard/pkg/k8s/client.go
- fleetshard/pkg/k8s/client_test.go
- fleetshard/pkg/runtime/runtime.go
Use the controller-runtime client instead of the default kubernetes clientset.
- Client is now injected 
- Client can be tested
- Client is not created hardcoded
- CI
- Automated tests (unit)
- Manual testing on k8s 
- run `fleet-manager` and `fleetshard-sync` on the same cluster
- Install openshift-router with `make install/openshift-router`
- Create Central instance
- Routes should be created
> Use controller-runtime client in `IsRoutesResourceEnabled` function

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This is the fix to the issue we found while running `terraform_cluster.sh` - bitwarden cli will not show new items until `bw sync` is run. We run `bw sync -f` as a solution to this issue in bw cli: https://github.com/bitwarden/cli/issues/234#issuecomment-800090397
1. Run `terraform_cluster.sh` and see a successful sync: 
```
rhacs-terraform % ./terraform_cluster.sh stage acs-meh-dp-01
You are logged in!
? Master password: [hidden]
Syncing complete.
```
> Sync bitwarden cli in terraform_cluster.sh

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
There is no need to use `Always` with an immutable image tag.
N/A
> Use IfNotPresent imagePullPolicy for fleetshard-sync.

- .openshift-ci/tests/e2e.sh
To make sure that we  generate output showing exactly which test specs have been executed, not just failing ones.
This has already been enabled in the `Makefile` in the form of a default `GINKGO_FLAGS` setting, but since CI overwrites this with a custom flags configuration we need the `-v` also in there.
```
```
> Enable verbose mode for Ginkgo

- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
This includes a version jump of the Prometheus operator from v0.45.0 to v0.56.3.
Tested on dev cluster.
```
```
> Update observability operator to v3.0.16

- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
In multiple places we have now logic for retrieving the set of all tenant namespaces by doing some grep-work on `kubectl get ns` output of some sort.
Would be nicer and more robust to have a dedicated label for this.
```
```
> Add Kubernetes Label to Tenant Namespaces

- .secrets.baseline
- templates/service-template.yml
This is part of https://issues.redhat.com/browse/ROX-12990.
Configure default central resources in service template. Can be easily adjusted in the future.
This is for *new* tenants. Currently effective defaults are in `internal/dinosaur/pkg/defaults`.
Essentially: new configuration reflects that current CPU usage is <= old defaults and current memory usage is >= old defaults.
Especially watch out for copy and paste bugs.
The new settings would be automatically deployed on staging, I believe.
```
```
> ROX-12990: Configure default Central resources

- internal/dinosaur/pkg/migrations/202210271100_change_central_client_origin.go
- internal/dinosaur/pkg/migrations/migrations.go
https://github.com/stackrox/acs-fleet-manager/pull/460 introduced a DB migration that adds `client_origin` and incorrectly sets its initial value to `shared_static_sso`. That prevented central entires with such `client_origin` from being deleted, as `fleet-manager` can only handle `shared_static_rhsso` `client_origin` value.
1. Run migrations without new migration, insert central request with `shared_static_sso` client origin:
```
<***>@<*****>-MacBook-Pro acs-fleet-manager % make db/setup
...
<***>@Ivans-MacBook-Pro acs-fleet-manager % make db/migrate
...
I1027 11:36:46.213705   54556 cmd.go:22] Database has 10 migrations applied
<***>@<*****>-MacBook-Pro acs-fleet-manager % make db/login
...
serviceapitests=# insert into central_requests (id, client_origin) values ('123', …
```
> Migrate shared_static_sso -> shared_static_rhsso

- .shellcheckrc
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Change the way of loading secrets in the Data Plane Terraforming script for **stage** and **prod** environments from BitWarden to the Parameter Store.
All necessary tools are installed automatically (implemented in #492).
1. Changed `helm upgrade` to `helm template`
2. Run the script and save the output. Enter AWS stage credentials when prompted:
```
./dp-terraform/helm/rhacs-terraform/terraform_cluster.sh stage acs-stage-[dp-01](https://issues.redhat.com//browse/dp-01) > ./tmp/resources-actual.yaml
```
4. Checkout `main` branch
5. Run the script and save the output:
```
./dp-terraform/helm/rhacs-terraform/terraform_cluster.sh stage acs-stage-[dp-01](https://issues.redhat.com//browse/dp-01) > ./tmp/resources-expected.yaml
```
6. Ensure that there …
> ROX-13098: Load config from Parameter Store for the Dataplane Terraforming

- .editorconfig
- README.md
To use a common indentation style in our Shell scripts.
1. Switch to this branch.
2. Make sure that your IDE has an EditorConfig plugin/extension enabled.
3. Save a shell script (with autoformatting on save enabled) and verify that the indentation in the shell script is changed according to the EditorConfig configuration.
> Integrate EditorConfig

- CHANGELOG.md
- docs/development/secret-management.md
- docs/development/setup-osd-cluster-idp.md
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/osd-cluster-idp-setup.sh
- scripts/lib/external_config.sh
This PR migrates secrets loading in `osd-cluster-idp-setup.sh` from BitWarden to Parameter Store
1. Add `echo` to `ocm` commands
2. Capture the output
3. Compare the `diff` between main and branch. 
```
```
> ROX-13098: Load secrets in IDP cluster creation script to Parameter Store

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/osd-cluster-idp-setup.sh
This approach relieves us from having to automate `ocm` login (unclear if this is even possible at all), at the cost of maintaining some (non-secret) per-cluster information in this script.
Tested by prepending the `helm` command with an `echo`, running the script, and checking for the expected post-login output from `oc` was there.
> ROX-12689: oc login automatically, drop need for ocm login

- dp-terraform/osd-cluster-idp-setup.sh
Ran the script after this change and it went fine (rather than fail with `error: not a valid URL: parse "https://api.acs-prod-dp-01.pnz3.p1.openshiftapps.com:6443 ": invalid port ":6443 " after host` like before).
> ROX-12689: Trim whitespace around URL

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Ran manually and this time the script just produced the following:
```
[mowsiany@mowsiany rhacs-terraform]$ ./terraform_cluster.sh stage acs-stage-dp-01
Logged into "https://api.acs-stage-dp-01.blbk.p1.openshiftapps.com:6443" as "system:serviceaccount:acscs-dataplane-cd:acscs-cd-robot" using the token provided.
You have access to 117 projects, the list has been suppressed. You can list all projects with 'oc projects'
Using project "default".
Release "rhacs-terraform" has been upgraded. Happy Helming!
NAME: rhacs-terraform
LAST DEPLOYED: Mon Nov  7 11:02:31 2022
NAMESPACE: rhacs
STATUS: deployed
REVISION: 27
TEST SUITE: None
[mowsiany@mowsiany rhacs-terraform]$
```
> ROX-13436: remove --debug to stop echoing secrets

- Makefile
- build_deploy.sh
This PR upgrades go version in the `build_deploy.sh` script, which is used in app-interface CI.
Main idea is to use the multi-stage build, introduced by @mtesseract instead of using go installation on the host node.
Current version of the multi-stage `Dockerfile` already has go version 1.18.
Run `build-and-deploy.sh` manually. I have no permission to push the images to app-sre quay, but at least the build was successful and I can run the images locally. I can also confirm that `standard` build image is used in the …
> Upgrade go version to 1.18 for app-interface CI

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This PR removes wrongly defined `CLUSTER_ID`s. They are now loaded from the Parameter Store.
Related Slack channel: https://srox.slack.com/archives/C04AGPG4GMN
Diff between yamls
```
```
> Move cluster params to the Parameter Store

- probe/pkg/runtime/runtime.go
- probe/pkg/runtime/runtime_test.go
This is a bug that sadly got introduced in my last iteration of #533. The cause is a simple typo (`ctx` vs `cleanupCtx`), however this leads to the cleanup not having its own context. While that would be more "golang native", the issue is that we actually want the a blocking clean up call in this case. Otherwise after a timeout or cancellation of the main context, the probe resources would not get cleaned up properly.
I used `NotContains` in the regression test because I didn't manage to find a clean way to introduce a typed error and propagate it correctly with the other wrapped errors of the main routine.
```
make verify lint binary test …
```
> probe service: use correct context when invoking the cleanup

- .openshift-ci/build-root/Dockerfile
Fix broken stern link in the openshift CI build image
Build CI image locally
```
build-root git:(yury/fix-stern-link) ✗ docker run test_stern stern -v
version: 1.22.0
commit: f6f4f640be851ccbd311b609d94a6fdab432d212
built at: 2022-09-27T13:34:04Z
```
> Fix stern dependency in the build image

- openapi/rh-sso-dynamic-client.yaml
- pkg/client/redhatsso/api/api/openapi.yaml
- pkg/client/redhatsso/api/api_acs_tenants.go
- pkg/client/redhatsso/api/model_acs_client_response_data.go
- pkg/client/redhatsso/dynamicclients/client.go
As discussed [here](https://chat.google.com/room/AAAAnbZRzRE/k7ObQN-Ybkk), `api.iam.acs` is made into the default scope. We can stop requesting it before we switch to `api.iam.clients`.
1. `POST https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token` - removed `api.iam.acs` in request, still in response
> ROX-13408: Remove api.iam.acs scope in token request

- internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
Currently, it's possible to run into an error within the deletion worker for centrals.
This is possible when the deletion will be triggered during provisioning of the central. At this specific point, no `ClientOrigin` will be associated with the central request.
Since the client origin will be unset, the deletion will currently fail.
Instead of being strict on the deletion of these central requests and erroring out, I've dediced to instead log the occurrence.
```
./fleet-manager serve ...
CLUSTER_ID=... ./fleetshard-sync
curl -H "Authorization: Bearer $(ocm token)" http://127.0.0.1:8000/api/rhacs/v1/centrals/<id>?async=true -X DELETE
```
> Fix removal of centrals that did not get assigned a client origin

- .github/workflows/ci.yaml
- Makefile
- build_deploy.sh
- probe/Dockerfile
Add support for building and pushing Docker images for the probe service.
The images are pushed to `rhacs-eng:blackbox-monitoring-probe-service`
inside the stackrox quay.io organization.
In contrast to fleetmanager and fleetshard-sync, which are bundled together
in the same image, a new image for the probe is created. Consequently, the
relevant Makefile commands have been split into `/fleetmanager` and `/probe`
components.
In addition, the probe Dockerfile has been updated to reflect the latest
changes to the fleetmanager/fleetshard-sync Dockerfile.
Pushed image to repo via Makefile.
> ROX-12076: docker image for probe service [5]

- probe/config/config.go
- probe/internal/cli/cli_test.go
- probe/pkg/probe/probe.go
- probe/pkg/probe/probe_test.go
- probe/pkg/runtime/runtime_test.go
I did not realize that the HOSTNAME env variable inside the pod already includes `probe-`. An additional prefix is therefore not necessary.
> ROX-12076: Remove probe name prefix [6]

- deploy/helm/probe/templates/01-operator-02-secret-ocm-token.yaml
- deploy/helm/probe/templates/01-operator-02-secret-rhsso-client-secret.yaml
- deploy/helm/probe/templates/01-operator-03-deployment.yaml
- deploy/helm/probe/values.yaml
- probe/config/config.go
- probe/config/config_test.go
- probe/internal/cli/cli.go
- probe/pkg/fleetmanager/client.go
- probe/pkg/probe/probe.go
- probe/pkg/probe/probe_test.go
Based on the learnings from e2e testing the probe on a dev cluster, I had to do some adjustments:
* Add OCM auth as a workaround. The reason behind this is that OCM does not seem to correctly support
RHSSO service accounts when they represent the user instead of the calling service.
* I also added some minor adjustments:
* Reduced clean up timeout to 5 minutes.
* Catch SIGTERM signal.
* Don't wait for deprovision in clean up.
Tested on dev cluster.
> ROX-12076: OCM auth [8]

- .github/workflows/ci.yaml
- build_push_fleet_manager.sh
- build_push_probe.sh
- build_push_with_probe.sh
This will fix stage deployment when [app-interface PR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52332) is merged 
- Split building script into two separate ones to avoid confusion. One is building main image and probe service and other one is running in app-interface and only builds fleet manager image for stage deployment
- Change script name so it reflects that it only build and pushes image
- Explicitly provide info in the script that it runs on AppSRE infra
> Split building image scripts

- CHANGELOG.md
- Makefile
To make it easier to get a release version string I added a Makefile target. I also updated the CHANGELOG.md to list the 2022-11-08.1.3060ea1 Release, since it wasn't done during release.
```
make release-version
```
> ROX-12871: add release-version to Makefile

- build_deploy.sh
[app-interface PR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52332) is merged so `build_deploy.sh` script is no longer needed because `build_push_fleet_manager.sh` will be used instead
> Drop temporary build and deploy script

- Makefile
Fix `release-version` makefile target
- Run `make release-version` with existing tag `2022-11-23.2.377f59e`
- Run `make release-version` without existing tag `2022-11-23.1.377f59e`
> Fix `release-version` makefile target

- scripts/lib/external_config.sh
This may help the script caller to troubleshoot the problem when some input is incorrect. For example:
1) Wrongly selected environment;
2) Wrongly selected cluster.
Currently in this case the script will fail with the message like:
```
./terraform_cluster.sh: line 62: CLUSTER_ROBOT_OC_TOKEN: unbound variable
```
Call terraform with non existing cluster 
```
$ ./terraform_cluster.sh stage acs-stage-dp-99
.... <truncated-output> ....
WARNING: external configuration is empty for service 'cluster-acs-stage-dp-99'
./terraform_cluster.sh: line 62: CLUSTER_ROBOT_OC_TOKEN: unbound variable
```
> ROX-13396: Add a warning message when there are no parameters for a service

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/osd-cluster-idp-setup.sh
This change brings more automation to the cluster terraforming workflow. There is no need to access Parameter store manually to save new cluster parameters anymore 
- tested manually
> ROX-13621 Write cluster params to Parameter Store on cluster IDP setup

- Makefile
Should fix staging e2e job
https://ci.ext.devshift.net/job/acs-fleet-manager-e2e-main/lastBuild/console
> Fix drop tty requirement from e2e staging run

- .dockerignore
- .openshift-ci/e2e-runtime/Dockerfile
- .openshift-ci/e2e-runtime/docker_run_e2e.sh
- .openshift-ci/e2e-runtime/e2e_dockerized.sh
- Dockerfile
- Makefile
- dev/env/scripts/bootstrap.sh
- dev/env/scripts/docker.sh
- dev/env/scripts/lib.sh
- dev/env/scripts/up.sh
- docs/development/setup-test-environment.md
This PR is intended for covering 2 problems:
1. `Dockerfile` changes made in the branch are not reflected in the CI build;
2. No way to reproduce CI builds locally inside the container (i.e. when image build is broken).
The main idea is to introduce a dedicated image for E2E. Instead of building the base image which Dockerfile is taken from the `main` branch, we're now building E2E specific image which Dockerfile is taken from the feature branch which is going to be merged to main.
Related Openshift CI change: openshift/release#34027
Further steps:
1. Merge this PR
2. Merge Openshift CI PR
3. Remove openshift CI [build root Dockerfile](https://github.com/stackrox/acs-fleet-manager/blob/82d893723c9b344c9f6d1f9f75d189eb2b61c1ed/.openshift-ci/build-root/Dockerfile)
~- [ ] Unit and …
> Make image for E2E tests instead of Base build image

- pkg/client/fleetmanager/auth.go
- pkg/client/fleetmanager/auth_ocm.go
- pkg/client/fleetmanager/auth_rhsso.go
- pkg/client/fleetmanager/auth_static_token.go
The changes made within #616 require an ID token, where the `aud` claim is set to be used in combination with the AWS libraries.
Currently, the RH SSO auth type does specify the `openid` scope, but returns a `Bearer token` without the `aud` claim set.
Instead, RH SSO returns an `id_token`, which has all the required claims (i.e. the `aud` claim).
This PR addresses the shortcoming, creating a new abstraction `RetrieveIDToken`, and explicitly returning the `id_token` for the RH SSO auth type.
```
```
> Allow retrieval of ID tokens within fleetmanager auth

- .openshift-ci/e2e-runtime/e2e_dockerized.sh
- dev/env/scripts/docker.sh
PR #603 broke `up.sh` script (`make deploy/dev`). When I execute it I'm receiving the following message:
```
/.../dev/env/scripts/lib.sh: line 77: /.../dev/env/defaults/cluster-type-default/*: No such file or directory
```
The reason is that `init` called after sourcing the `docker.sh` in the `bootstrap.sh`. It means that the `CLUSTER_TYPE` is always resolved as "default".
`make deploy/dev`
```
```
> Fix up.sh script

- CHANGELOG.md
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
The reason for not simply using `git rev-parse` is somewhat subtle, and laid out in detail in [the ticket](https://issues.redhat.com/browse/ROX-13648).
Ran the script manually and it correctly looked for the 7-char image tag
- based on current commit, when on this branch
- on the tip of *this* branch when ran from a temporary merge commit
> ROX-13648: Compute - rather than hardcode - the image tag.

- .github/workflows/deploy-stage.yaml
Use CD to terraform acs-stage-dp-02 (instead of acs-stage-dp-01, which will be turned down shortly).
- ~~[ ] Evaluated and added CHANGELOG.md entry if required~~
- ~~[ ] CI and all relevant tests are passing~~
Not possible with CD (confirmed by Marcin).
> ROX-13561: Change Stage environment terraform CD from acs-stage-dp-01 to acs-stage-dp-02, supporting multi-AZ change.

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Decouple the deployment of observability resources from the terraform script. The observability operator pulls the `production` branch, which is synced regularly with the `master` branch.
```
```
> Use production branch for observability resources

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/reconciler/reconciler.go
This addresses a [code review comment](https://github.com/stackrox/acs-fleet-manager/pull/542#discussion_r1034424909) from #542.
I thought that the Central-ID is not available in fleetshard, and has to be provided by fleet manager. Turns out I was wrong, and so it's a very easy fix.
Note that the names of the DB instance and cluster remain identical, the difference being that now they are formed based on the Central ID instead of the Central namespace (which currently contains the ID, but it's not guaranteed that it would remain so).
```
make …
```
> ROX-13693: Use Central-ID in database name

- README.md
Add an unprotected (exposes the badge to users having at least ViewStatus permission on the job) embeddable status for [build app-inteface CI job](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/acs-fleet-manager/cicd/jobs.yaml#L29)
Jenkins docs: https://ci.ext.devshift.net/job/stackrox-acs-fleet-manager-build-and-push-main/badge/
**Note:** embeddable status will be grey with text "not run" for anyone who does not auth in Red Hat SSO
> Add app-interface build CI embeddable status

- probe/config/config.go
Change the default `ProbeRunTimeout` to 30m. There is a known edge cases when ACSCS instance could take > 15 minutes to provision on production.
> Probe service: change default ProbeRunTimeout

- dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
- dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
- fleetshard/config/config.go
- fleetshard/config/config_test.go
- fleetshard/main.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
This PR adds AWS authorization for fleedshard-sync using RHSSO identity provider.
Fleetshard-sync uses RHSSO client credentials to get an ID token. Then it calls AWS STS to assume the fleetshard-sync-service role using the RH SSO ID token.
Tested on a local cluster.
1. Operator upgraded to 3.73.0
2. AWS account configured
1. `export MANAGED_DB_ENABLED=true`
3. `make deploy/dev`
4. Create Central
5. Ensure that create Aurora DB request is propagated to AWS
6. Wait until DB is provisioned
7. Delete Central Instance
8. Ensure that Aurora DB instance is deprovisioned.
Not tested: 
- Due to the lack of connectivity it is unable to test Central connection to DB. 
```
make verify lint …
```
> ROX-13262: Implement AWS auth for RDS

- CHANGELOG.md
- dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This is for making the operator catalog sources/versions same between CI, stage and prod.
CI green
> Use downstream version of the StackRox operator on stage

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
The tenant ID may be used to query tenant resources in scripts and tooling. In addition, the tenant ID identifies the Segment group for telemetry users.
I decided to opt for a k8s label instead of an annotation because I think it fits better semantically as it identifies the resource and is useful in k8s queries.
As far as I understand the reconciler, the label should be set for all existing and new tenants.
> ROX-13593: Add tenant ID as a k8s label

- e2e/e2e_test.go
- internal/dinosaur/pkg/presenters/dinosaur.go
Fixing negative DNS caching issue: Do not expose URLs until corresponding DNS records are created in Route53.
1. CI green
2. Test with UI
```
```
> ROX-13227: Fix negative DNS caching

- dp-terraform/helm/rhacs-terraform/check_image_exists.sh
Followup to #611 where during testing I did run the script in the failure case and it printed the correct message, **but I did not check the return code** :facepalm:
The script had happily always returned 0 eventually. So it did work as intended (delay for as long as necessary) _as long as the build eventually succeeded_.
This (combined with an unexpected shallow repo that resulted in wrong imagetag being used) is what caused a production outage during last release.
cc @kurlov 
Since we only push the image to `app-sre` org on merges, this is hard to integration-test properly. Following up on this in https://issues.redhat.com/browse/ROX-13747
But I did check this time that exit code is 1 where necessary. :wink:
> ROX-13450: fix image check

- dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
- dp-terraform/helm/rhacs-terraform/Chart.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/config/config.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
We'd like to enable Performance Insights (an AWS RDS feature) for the first users of Field Trial, to get a better idea of DB usage.
With this PR, the feature can be enabled using an environment variable for fleetshard-sync. Perhaps in the future we could allow it to be enabled on a per-customer basis (e.g. in the admin API)
~~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private …
> ROX-13811: Enable Performance Insights for managed DBs

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
The RDS instance status log messages do not specify the instanceID, making it impossible to tell which instance they refers to when there are multiple managed Centrals.
```
make verify lint …
```
> Improve RDS instance status log message

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This reverts commit 1847f55d50861bfa2b309927b1f64365840164c7.
The checkout method was fixed in #647 so we can go back to commit auto-discovery.
Ran the script manually.
For stage it worked.
```
[mowsiany@mowsiany rhacs-terraform]$ AWS_AUTH_HELPER=aws-vault HELM_PRINT_ONLY=true ./terraform_cluster.sh stage acs-stage-dp-02
Logged into "https://api.acs-stage-dp-02.8csb.p1.openshiftapps.com:6443" as "system:serviceaccount:acscs-dataplane-cd:acscs-cd-robot" using the token provided.
You have access to 114 projects, the list has been suppressed. You can list all projects with 'oc projects'
Using project "default".
history.go:56: [debug] getting history for release rhacs-terraform
upgrade.go:142: [debug] preparing upgrade for rhacs-terraform
upgrade.go:150: [debug] performing update for …
```
> ROX-13648: Revert "Rollback automatic tag resolution on prod (#645)"

- internal/dinosaur/pkg/services/quota/ams_quota_service.go
- internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
To get AMS to bill the cloud account, we need to use `billing_marketplace_account` instead of `cloud_account_id` parameter.
Links:
1. [Slack discussion](https://coreos.slack.com/archives/C0493H149DK/p1669915157049259) with AMS team
2. [Article from AMS](https://source.redhat.com/groups/public/ocm_team/ocm_blog/handling_multiple_marketplaces_in_ams)
```
```
> ROX-12137: Use billing_marketplace_account instead of cloud_account_id

- fleetshard/pkg/central/reconciler/init_auth.go
After claim mappings were introduced to central https://github.com/stackrox/stackrox/pull/3460, we can use them to move from using `is_org_admin` claim to `admin:org:all` role.
This PR:
* add claim mapping from `realm_access.roles` to `groups`
* change rule from using `org_admin` to `admin:org:all`
Follow https://github.com/stackrox/acs-fleet-manager/blob/main/docs/development/setup-developer-osd-cluster.md and
1. Deploy fleet-manager
2. Deploy fleetshard synchronizer in OSD cluster
3. Add routes to access the Central UI: https://github.com/stackrox/acs-fleet-manager/blob/main/docs/development/test-locally-route-hosts.md
4. Go to `Red Hat SSO` auth provider and see rule with `admin:org:all` group
5. Press `Test Login` and see `admin:org:all` in `groups`
> ROX-12763: use claim mappings for admin:org:all role

- internal/dinosaur/pkg/handlers/cloud_accounts.go
- internal/dinosaur/pkg/services/quota/ams_quota_service.go
- pkg/client/ocm/client.go
- pkg/errors/errors.go
OCM does not load the user information from Red Hat SSO lazily. Instead, it requires that the user has logged into OCM at least once - this can be done by visiting https://console.redhat.com/openshift. See https://issues.redhat.com/browse/SDB-3194 for more context on this behavior.
Our approach here is to inform the user why the creation failed and how they can fix it themselves. 404 in `OrganisationNotFound` occurs when neither org nor user is registered with OCM. 404 in `FailedClusterAuthorization` occurs when the user is unknown to OCM, but they belong to an org that is registered with OCM.
Tested with local fleet manager and newly created RH accounts.
> ROX-13106: Show hint to user when OCM user or org is not found

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
The motivation behind this change is to test our new telemetry feature in the field.
```
```
> Switch stage data plane to stage operator

- .secrets.baseline
- Makefile
- internal/dinosaur/pkg/config/central.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/timeout.go
- pkg/metrics/metrics.go
- templates/service-template.yml
Alternative approach to https://github.com/stackrox/acs-fleet-manager/pull/618 as suggested by Evan.
Instead of creating a new worker to check for a timeout in this PR existing workers check for timeout for instances in corresponding status.
There are a few caveats to the implementation:
* `accepted_centrals_mgr` has a separate timeout for a certain kind of transient errors
* `preparing_dinosaurs_mgr` has separate timeout for server errors, and fail request immediately on client errors. The only value timeout brings here is that the timeout is checked before `PrepareDinosaurRequest` is executed.
* `provisioning_dinosaurs_mgr` did not own transition from `Provisioning` state before. There is a race condition now between updates coming from `fleetshard-sync` and timeout logic. In worst case …
> ROX-12921: Introduce timeout for ACSCS requests

- Makefile
- dev/env/scripts/lib.sh
- dp-terraform/add-on/rhacs-terraform/Makefile
- pr_check_docker.sh
This started as a way to fix this error that I encountered a while ago:
```
[mowsiany@mowsiany acs-fleet-manager]$ make setup/git/hooks
[...]
/usr/bin/which: invalid option -- 's'
/nix/store/fsg2hsj457wm29d6gvxg2giw1d6nic2l-python3.10-pre-commit-2.19.0/bin/pre-commit
Installing pre-commit hooks
pre-commit installed at .git/hooks/pre-commit
```
After [some googling](https://unix.stackexchange.com/questions/404146/what-is-the-best-method-to-test-if-a-program-exists-for-a-shell-script) I decided to eradicate all uses of `which` in the repo in exchange for a portable way, to seed any future cargo-culting in the desired direction. :wink:
Ran the target and it was fine this time:
```
[mowsiany@mowsiany acs-fleet-manager]$ make setup/git/hooks 
git config --unset-all core.hooksPath
make: …
```
> Avoid using `which`

- Makefile
Make `tools_venv` target depend on `tools/requirements.txt` changes. Otherwise, the target is always up-to date if I make changes in `requirements.txt` unless I remove `tools_venv` dir manually. 
Tested manually
> Make `tools_venv` target depend on `tools/requirements.txt`

- scripts/lib/external_config.sh
Mark parameters loaded from Parameter Store as read-only to avoid unnecessary overrides in the script.
Manual testing
> ROX-13472: Mark parameters loaded from Parameter Store as read-only

- .secrets.baseline
- config/fleetshard-authz-org-ids-development.yaml
- config/static-token-payload.json
- dev/env/manifests/shared/03-configmap-config.yaml
- templates/service-template.yml
This change is in preparation for looking up the org name via OCM in fleet manager.
We need the org in the static token to be real for the lookup to succeed. As the real org
I have chosen the RHACS dev organisation.
Note that the static token is currently used in the e2e tests and is injected via the vault
instance. We therefore have a chicken and egg problem:
* The e2e test of this PR will fail until we change the static token secret in the vault.
* If we change the vault secret without merging this PR, the e2e tests in other PRs will fail.
I suggest to change the secret during a quiet time, wait for a successful build and merge the PR.
> ROX-12344: Use dev rhacs org_id in static token

- .github/workflows/ci.yaml
- .github/workflows/rds.yaml
- Makefile
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Adds an integration test that checks RDS data provisioning and deprovisioning logic, that:
* uses the ACSCS dev account to instantiate a temporary RDS DB
* checks that the instance & cluster are created and deleted on AWS
* runs on CI in a separate check, to save time
* is disabled by default when running the tests, because it requires extra configuration and takes about 10 minutes to run
Relying on the CI to run the tests.
> ROX-13911: Add RDS provisioning integration test

- .openshift-ci/e2e-runtime/Dockerfile
Starting from today our CI fails with error:
```
fatal: detected dubious ownership in repository at '/src'
To add an exception for this directory, call:
git config --global --add safe.directory /src
./.openshift-ci/tests/e2e.sh: line 10: /dev/env/scripts/lib.sh: No such file or directory
```
I think it may be caused by a `git` version update in the yum repo. 
CI green
> Fix dubious ownership error in CI

- .pre-commit-config.yaml
- .secrets.baseline
- test/mocks/redhatsso.go
Bump detect-secrets to 1.4.0
CI green
> ROX-13456: Bump detect-secrets to 1.4.0

- pkg/client/redhatsso/dynamicclients/client.go
Switch to explicitly requesting `api.iam.clients` scope when getting token for sso.redhat.com dynamic clients API. Currently, the scope is being returned by default.
1. Created local fleet-manager with dynamic client configuration
2. POST new central
3. Verified that db contains central with client id and client secret
> ROX-13408: Use api.iam.clients in dynamic clients API wrapper

- .secrets.baseline
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/dbclient.go
- fleetshard/pkg/central/cloudprovider/dbclient_moq.go
- fleetshard/pkg/central/postgres/postgres.go
- fleetshard/pkg/central/postgres/postgres_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
In preparation for supporting multiple DB users (i.e. the initial `rds_superuser`, and a non-privileged user for Centrals) , this PR refactors the RDS provisioning client so that it returns the connection parameters as a struct, instead of a string. 
This will make it easier to generate connection strings for different users.
Tested locally by verifying that a DB was provisioned, and that the Central was able to connect:
`INSTALL_OPERATOR=NO MANAGED_DB_ENABLED=TRUE ./dev/env/scripts/up.sh`
`./scripts/create-central.sh`
To test locally, I have to make the DB publicly accessible. I added a new VPC, security group and DB subnet group in dev on AWS for this purpose.
```
make verify …
```
> ROX-13666: Refactor DB connection string

- Makefile
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
- internal/dinosaur/pkg/handlers/cloud_accounts.go
- internal/dinosaur/pkg/handlers/cloud_accounts_test.go
- internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/quota/ams_quota_service.go
- internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
- openapi/fleet-manager-private.yaml
- pkg/client/ocm/client.go
- pkg/client/ocm/client_moq.go
- pkg/errors/errors.go
- templates/service-template.yml
The organisation name is added to the central request to make the cloud service more observable. The plan is to pass it together with the org id to the data plane, set it as label/annotation and then scrape it with Prometheus. Note that the organisation name is effectively immutable for users - it can only be changed in edge cases by Red Hat IT - however it is not unique. The org id is immutable and unique per account. The org name for existing tenants will be migrated using the OCM client.
* The organisation name is fetched from OCM during the request preparation phase.
* A migration is added to add a column for the org name to the database.
* `GetOrganisationIDFromExternalID` is changed to `GetOrganisationFromExternalID`, which now returns the complete organisation struct instead of …
> ROX-12344: Add organisation name to central request

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump the operator version to 3.73.1 as it includes critical fixes to the compliance page and the autogenerated registry issue.
> Bump operator version to 3.73.1 on prod

- CHANGELOG.md
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/values.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
This PR is added support to use pre-created AWS CloudWatch Log Groups. This allows us to set the retention period for our logs.
This is tested on the dev environment with cluster "mt-log-0111". And logs can be found on the following AWS CloudWatch Log Group: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/acs-dev-dp-01.application
This PR is related to the following PR: https://github.com/stackrox/acs-fleet-manager-aws-config/pull/28
1. Apply terraform from PR: https://github.com/stackrox/acs-fleet-manager-aws-config/pull/28 - with the following command: `make resources ENV=dev`
2. Create a dev OSD cluster based on documentation: `docs/development/setup-developer-osd-cluster.md`
3. When the cluster is up and running, apply Helm with …
> ROX-12486: Add support for using existing log groups created by terraform

- pkg/client/fleetmanager/auth_ocm.go
We have seen in the probe service an error during provisioning:
```
Error: ... retrieving access token via OCM auth type: invalid_grant: Invalid refresh token
```
The OCM offline token was valid, so the assumption is currently the following:
In case the created access token (which expires after 15 minutes) is sligthly before hitting the 1 minute margin of refresh _and_ the request takes a long amount of time to be processed (e.g. retrying due to network timeouts, latency), it might be that the token will be invalid once the request reaches the 
server.
While this may be an unusual event with low probablility, it doesn't hurt to increase the margin to 5 minutes, as the token itself is valid for 15 minutes.
> Increase OCM token margin for refresh

- .secrets.baseline
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
- fleetshard/pkg/central/cloudprovider/dbclient.go
- fleetshard/pkg/central/cloudprovider/dbclient_moq.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
The `EnsureDBProvisioned()` was doing two things:
- ensures that the DB was provisioned
- obtains and returns the data necessary to connect to the DB (host name, etc)
It should be possible to do these things independently of each other, and this PR addresses that.
This will be needed in a follow-up PR, to use non-privileged Postgres users for ACS instances.
Tested locally by verifying that a DB was provisioned, and that the Central was able to connect:
To test locally, I have to make the DB publicly accessible. I added a new VPC, security group and DB subnet group in dev on AWS for this purpose.
```
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> …
```
> ROX-13666: Split dbclient.EnsureDBProvisioned() into two functions

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
Add organisation meta data to the central tenant. The org name is set as an annotation, because it does not comply with Kubernetes validation rules.
We will scrape the label and annotations via Prometheus and pass them via metric labels to Grafana dashboards. This will be added as a follow up.
```
relabel_configs:
- action: labelmap
regex: __meta_kubernetes_pod_label_(.+)
- action: labelmap
regex: __meta_kubernetes_pod_annotation_(.+)
```
Tested with local fleet-manager and dev data-plane cluster.
> ROX-12344: Add org-id label and org-name annotation

- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
RDS DB usually takes ~3 minutes, and the timeout was set to 10 minutes. It looks like sometimes it actually takes around 10 minutes, so this PR increases that time limit to 14 minutes.
CI only.
> Increase RDS integration tests timeout

- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/dinosaur.go
- internal/dinosaur/pkg/services/telemetry.go
Use the `acount_id` claim from the Red Hat SSO token as the user id in telemetry events. This aligns with the user id that is used by the ACS front end console plugin.
> ROX-13593: Use account id as user in track events

- .secrets.baseline
- pkg/client/telemetry/config.go
- templates/service-template.yml
We want to enable loading the telemetry key from the fleet-manager vault. Therefore, the telemetry key is changed from a direct CLI flag to a file mount.
> ROX-13593: Store telemetry storage key as secret

- fleetshard/pkg/central/reconciler/init_auth.go
This pretty much reverts https://issues.redhat.com/browse/ROX-12946. 
For details, refer to the [doc](https://docs.google.com/document/d/1b3ycWWi78s4hllN1S566AzdOPeVXOLzAOekVFa1cKRw/edit?usp=sharing)
TBD
> ROX-14473: require user org_id to match ACS owner org_id

- .gitignore
Ignore all files within `secrets/` folder, except database secrets. This makes it such that new secrets do not need to be added individually to the ignore list.
> git ignore all secret files

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
For high availability, a failover RDS DB instance is created, in a different Availability Zone (AZ).
This PR implements provisioning logic for the failover instance (also for existing Centrals), and makes sure that both instances are deleted when deprovisioning an ACSCS instance.
Note that during ACSCS provisioning, `fleetshard` does not wait for the failover instance to be completely created, as that would increase our provisioning time.
Tested in a local cluster. Verified in the AWS console that the DB was provisioned and that 2 instances were created, and that the Central was able to …
> ROX-13924: provision failover RDS instance

- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/dinosaur.go
- internal/dinosaur/pkg/handlers/validation.go
- internal/dinosaur/pkg/services/telemetry.go
- pkg/auth/acs_claims.go
- pkg/auth/acs_claims_test.go
- pkg/auth/context_config.go
- pkg/auth/context_test.go
Extract the `user_id` or `rh-user-id` (human user token vs service account token) and emit them as part of the telemetry events. Group the telemetry user together with the tenant group.
I tried to clean up the claim naming without changing too much. In particular, I tried to distinguish more clearly between the subject claim, account id claim and the new user id claims. However no changes to the Central request schema have been made.
The plan going forward is to deprecate and eventually remove the `OwnerAccountID` column all together, removing the need for the `account_id` token.
Manual test of the telemetry events.
> ROX-13593: Use `user_id` and `rh-user-id` claims in telemetry events

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/util/revision.go
- fleetshard/pkg/util/revision_test.go
- pkg/shared/central_admin_password.go
This PR provides utility functions to enable / disable admin password generation for specific central CRs.
Internally, it will set the `adminPasswordGeneration` field on the central CR to either `false`, i.e. enabling basic authentication with username password, or to `true`, i.e. disabling basic authentication with username password.
This was especially useful in creating migration scripts for a previous incident, where admin access to the central instance was required.
**TODO:** Add …
> Provide utility to disable/enable admin password for specific central CR

- .secrets.baseline
- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
- internal/dinosaur/pkg/config/central.go
- internal/dinosaur/pkg/config/central_request.go
- internal/dinosaur/pkg/handlers/dinosaur.go
- internal/dinosaur/pkg/migrations/202301301200_add_internal_to_central_request.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/routes/route_loader.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
- internal/dinosaur/providers.go
- openapi/fleet-manager-private.yaml
- templates/service-template.yml
This PR provides the ability to disable telemetry for central created by the probe service.
Currently, the probe service will create centrals in a continous interval (each 15 minutes). Since we track the central creation requests in our telemetry (specifically via segment and visualizing via amplitude), this means we get unneccessary information there.
Instead, we want to disable these central instances specifically for telemetry collection.
To achieve this, the following has been done in this PR:
- A new configuration for CentralRequests has been introduced as a `ConfigModule` for fleet manager. It will hold the list of user-agents that should be seen as coming from "internal" clients.
- During this introduction, the CentralRequestsExpirationTime has been refactored to move out of the …
> ROX-14303: Disable telemetry for centrals created by probe service

- Makefile
- pkg/workers/reconciler.go
- pkg/workers/reconciler_test.go
Delete it reconcile timeout log messages. Not required because reconcilers already print multiple log messages to indicate that they are running.
Removed wake up channel because it is not used.
- Run fleet-manager
> ROX-14650- Remove timeout log messages

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
The update is only done in stage to make sure the update is safe.
The new version includes some nice features:
- version bumps of golang and bundled operators. This should fix some security issues.
- self-reported metrics, which allows us to define alerts on reconciliation failures of the observability operator.
- removed "Kafka" from default resources names.
The latter could break some of our alerting rules and documented links. However, it should only come into effect once we delete the existing "Kafka" resources in the cluster and re-create them with the new default. We can do this at a later stage.
Tested this version on a dev cluster, didn't notice any problems.
> update observability operator to v4.0.4

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Creating DB instance in a cluster with Promotion Tier 1 (which the default value) causes our backup instance to scale together with the main instance, even if it has 0 connections to it. More information can be found [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.how-it-works.html#aurora-serverless-v2.how-it-works.scaling).
The reason we have a backup instance is to have automatic failover, if the main instance fails. As these instances are normally not used at all, it's cheaper to not have them scale together with the writer instance.
~~- [ ] CI and all relevant …
> Allow DB instances to scale independently of each other

- templates/service-template.yml
The configuration value passed to the CLI argument for `--central-request-internal-user-agents` was malformed. Instead of specifying a single string, the array was passed as `[fleet-manager-probe-service]`. Thus, the central requests coming from the probe service weren't correctly identified as internal, and the telemetry was mistakenly set.
Now, the value is set correctly and the matching succeeds.
```
```
> Fix internal user agents config in fleet manager template

- pkg/client/telemetry/config.go
Push telemetry events every minute to make sure that groups are created before the first Central event is registered. The default if unspecified is 1 hour.
> Push telemetry events every minute

- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update observability operator to `v4.0.4`. This version has been live in stage for some time, and brings security updates and a change to the resource naming (`kafka` -> `obs`).
> update prod observability operator to v4.0.4

- dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
- dev/env/scripts/bootstrap.sh
- dev/env/scripts/install_operator.sh
- dev/env/scripts/lib.sh
Add operator install script to install and upgrade the operator independently of the setup scripts.
- run scripts
> Add operator install script

- internal/dinosaur/pkg/handlers/dinosaur.go
We currently skip setting the telemetry key as well as tracking events from central requests that are `Internal`, i.e. coming from services such as the probe service.
Within the initial PR, the condition was missed for the deletion request, which is now fixed within this PR.
```
```
> Skip tracking deletion for centrals from probe service

- internal/dinosaur/pkg/api/dbapi/central_request_types.go
Added CentralRequest documentation.
-
> ROX-14544 - Add CentralRequest field documentation

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/config/config.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
Add environment and cluster name annotations to Central pods. The annotations can be read by Prometheus, and will be attached to any metrics scraped from Central. This will make it easier to identify the environment in alerts, both to distinguish between stage/prod and between different data plane clusters (us, eu).
CI
> ROX-12462: add env annotations

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
The nightly build currently deployed to staging points to not-yet-existing docs, so we do not want to push that to production.
So we revert the operator version in staging to the version that we intend to push to production, to be able to validate everything is OK before proceeding with ACS CS release.
Also (no impact) explicitly set `OPERATOR_USE_UPSTREAM="false"` in the `prod` case for now to make the distinction more clear.
I *suppose* the existing centrals in staging might not like this downgrade, but I think they are disposable. I plan to post an announcement about this when merging this change.
None.
> Use a released operator in stage, to test before ACSCS release.

- deploy/helm/probe/deploy.sh
- deploy/helm/probe/templates/01-operator-04-deployment.yaml
- deploy/helm/probe/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
Follow up to #822 to make sure fleetshard-sync, probe and cloudwatch exporter metrics are also labelled in the same way as Central/Scanner metrics.
> ROX-12462: add env to fleetshard-sync, probe, cloudwatch-exporter

- .github/workflows/ci.yaml
- .github/workflows/probe.yaml
Problem:
- `acs-fleet-manager` image is built and pushed by jenkins for all `main` and `production` commits.
- probe image is built and pushed by GHA only for `main` commits
- however deployment of both uses the same way to obtain image tag to push
- this obviously leads to image pull failures for prober when cherry-picked commits exist on `production` branch
To fix this quickly without refactoring the whole probe build/push process and repository configuration, this change moves the probe build+push to a separate workflow, and enables this workflow on both `main` and `production`. Once merged and working, this commit will need to be cherry-picked to the `production` branch.
N/A
> Build and push probe separately, and on production branch too.

- Dockerfile
- Dockerfile.hybrid
- fleetshard/pkg/central/postgres/db_ca_certs.go
- fleetshard/pkg/central/postgres/dbconnection.go
- fleetshard/pkg/central/postgres/dbconnection_test.go
- fleetshard/pkg/central/postgres/dbinit.go
- fleetshard/pkg/central/reconciler/reconciler.go
This PR adds the AWS RDS CA certificates to the fleetshard-sync image, which are then:
* used verify the Postgres connection from fleetshard to RDS
* passed to Central as additionalCAs, so that also Central can verify its Postgres connections
Tested in a local cluster, by running:
And then waiting for a Central to start successfully.
To test locally, I had to make the DB publicly accessible. For this purpose, I added a new VPC, security group and DB subnet group in dev on AWS.
```
make db/teardown db/setup …
```
> ROX-13913: Verify RDS certificates in Postgres connections

- fleetshard/pkg/central/postgres/dbinit.go
This PR removes code that does not need to be executed anymore. All Central DBs in stage and prod have been migrated to not use the `rds_superuser` role anymore, and new Centrals never have access to that user.
The removed code was reassigning the Central DBs owner from `rhacs_master` to `rhacs_central`, but at this point all Centrals are provided the `rhacs_central` user from the beginning, so all DBs belong to this user from the start.
```
```
> ROX-14955: Remove legacy Central DB migration step

- Dockerfile.hybrid
- dev/env/defaults/00-defaults.env
- dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump stackrox operator version to 3.74.0.
ubi version bump is unrelated.
CI
> Bump stackrox operator version to 3.74.0

- deploy/helm/probe/deploy.sh
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- scripts/check_image_exists.sh
Make sure that the probe image exists before we deploy, similar to what we already do for fleetshard-sync. This should address problems with deploying the probe service even though no new image has been built.
I refactored the image check script args and moved the script to the global scripts folder.
> check that probe image exists before deployment

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-02-no-init.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
We want to get rid of the default `strimzi` selector label, and replace it with `rhacs`. The observability operator allows such customizations via the `Observability` custom resource. We need to make sure the operator does not auto create one with default settings.
The CR is created with the current default settings, except:
* Set the cluster id to the cluster name - it's currently a UUID of the OpenShift cluster. The cluster is set by the operator as an external metric label.
* Disable logging explicitly. This shouldn't make a difference in most cases, because the operator ignores logging if the logging operator already exists in the cluster.
* Overwrite the selector labels and set them to `rhacs`.
Tested the Helm chart on dev cluster.
> ROX-10918: use rhacs label selectors

- .github/workflows/deploy-stage.yaml
Adds acs-stage-eu-01 terraforming to the CD pipeline.
https://issues.redhat.com/browse/ROX-14696
I could manually CD the cluster but I want to ensure adding it to CD is a supported way to do the initial bootstrapping. Per https://github.com/stackrox/acs-fleet-manager/blob/main/.github/workflows/deploy-stage.yaml#L5-L8 that means we need to merge to main and fix it if it's broken.
> ROX-14696: Add terraforming and probe deployment to acs-stage-eu-01.

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_central.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- openapi/fleet-manager-private.yaml
The label will be scraped by Prometheus as a source for dashboards. This will help increase the observability around eval and standard instances.
> expose instance type as label on Central pod

- docs/development/secret-management.md
- docs/development/setup-osd-cluster-idp.md
- dp-terraform/osd-cluster-idp-setup.sh
- scripts/lib/external_config.sh
To cover resilience requirements and prepare for disaster recovery in case of failure, it was decided to switch from Parameter Store to Secrets Manager. Parameter Store does not provide DR or backup out of the box, and the implemented S3 backup prototype looks cumbersome and not worth the effort to maintain it. On the other hand, Secret Manager supports replication across regions out of the box and it can be used for disaster recovery. 
The change is backward compatible. Parameters can be still loaded from Parameter Store. After merging this PR, I'm going to move the secured parameters.
CI
> ROX-14997: Add Secrets Manager support

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
I realized that we need to add additional label selectors for the Grafana and Prometheus rule resources - currently these still default to `strimzi`. After these selectors have been deployed to stage and prod envs, we may finally switch the labels to `rhacs` to get rid of Kafka naming.
Note that the first attempt to do this has been reverted via https://github.com/stackrox/rhacs-observability-resources/pull/68, precisely because the selectors in this PR are needed.
> add grafana and prometheus rule label selectors

- dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Set explicit ACS Operator CPU request and limit to 2 (via OLM config).
- ~~[ ] CI and all relevant tests are passing~~
Will test in stage using CD to ensure the config is okay, then push to prod to see if it addresses the issue.
> Set ACS Operator CPU request and limit to 2

- README.md
Added AUTH_TYPE=OCM to the call to fleetshard-sync in the Quickstart section of the README.md, because the ocm token authentication does not work otherwise.
> add AUTH_TYPE=OCM to fleetshard-sync in quickstart README

- dev/env/scripts/exec_fleetshard_sync.sh
- dev/env/scripts/up.sh
- scripts/lib/external_config.sh
Switch dev scripts to use Secrets Manager instead of Parameter Store.
Scripts are used in local deployment, Openshift CI and RDS tests.
CI
> ROX-14997: Migrate dev scripts to Secrets Manager

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
New DBs will be provisioned with aurora-sqlpostgres engine version 13.9, which is a LTS (long term support) version. To stay on the LTS version, the auto upgrade minor version feature is now turned off.
This does not change existing DBs. As part of [ROX-16099](https://issues.redhat.com//browse/ROX-16099), I will monitor the upgrade state on AWS and disable auto upgrade on all instances, when they are all on v13.9. 
Tested in a local cluster, by running:
And then waiting for a Central to start successfully.
To test locally, I had to make the DB publicly accessible. For this purpose, I added a new VPC, security group and DB subnet group in dev on AWS. …
> ROX-16099: new DBs will use a LTS aurora-postgresql version

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
If a Central has the pause-reconcile annotation set, and its deletion is requested, it currently remains stuck in a deprovisioning state. The Central itself is not deleted by the Operator, however fleetshard-sync deletes all its other resources, making it unusable.
This PR takes the approach of setting the pause-reconcile annotation to false (if it's present). This way the Central is deleted, and the UI is not in an inconsistent state.
An alternative would be to have also fleetshard-sync not reconcile a Central that has the annotation set.
Tested locally.
> ROX-15806: Remove pause reconcile annotation before Central deletion

- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/pkg/services/cluster_placement_strategy.go
- internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
Removes the TargetedClusterPlacementStrategy.
This placement strategy was a breakglass mechanism that was added before in ServicePreview to enable forcing cluster selection to a single specific cluster. It is not currently used and will immediately be replaced by disabling Schedulable field for all non-desired clusters once https://github.com/stackrox/acs-fleet-manager/pull/904 is merged.
Ran the local tests per instructions below, all …
> ROX-16108: Remove Targeted Cluster Placement Strategy

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
This PR seems to fix the following incident:
https://redhat.pagerduty.com/alerts/Q1ERBKAIFV2F0K
fleetshard-sync can't connect to new DB instances, with the following error message:
`E0403 09:22:54.265198 1 runtime.go:164] Unexpected error occurred rhacs-cgl99m6d244mjjgq51sg/probe-795ccb9fb7-cc2vd-072a: getting Central DB connection string: initializing managed DB: initializing managed DB: beginning PostgreSQL transaction: remote error: tls: handshake failure`
Not using the ECC CA certificate type seems to solve the problem. Root cause is not known yet, and might be caused by AWS.
Tested in a local cluster, by running:
And then waiting for a Central to start successfully.
To test locally, I had …
> Change RDS DB CA certificate type

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
Pass the cluster's region from parameter store to the Fleetshard Sync so that it creates RDS instances in the correct (local) region.
Waited for https://github.com/stackrox/acs-fleet-manager-aws-config/pull/66 to merge.
Checked that parameter existed in Parameter Store.
Did *not* test the terraforming - we should push this commit to actually test the change using GHA, instead of trying to push the change locally …
> Pass the region from the parameter store to the fleetshard sync

- dev/env/scripts/exec_fleetshard_sync.sh
- dev/env/scripts/up.sh
This PR adds loading of `AWS_ROLE_ARN` in dev scripts.
`AWS_ROLE_ARN` stays in Parameter Store for now, which makes it unavailable from the dev scripts, because they are loading the configuration from Secrets Manager only. 
```
```
> Add missing AWS_ROLE_ARN parameter in dev script for fleetshard-sync

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
This is a bug fix release to work around the RDS certificate incident (https://redhat-internal.slack.com/archives/C051DKRQ2NR). It switches the certificate type to one that is not affected by the AWS bug. This change has already been deployed and tested in stage.
This is a cherry-pick of the bug fix commit.
> Bugfix-release 2023-04-04.1.1c8acf5

- .openshift-ci/e2e-runtime/Dockerfile
This is a workaround to the issue https://bugzilla.redhat.com/show_bug.cgi?id=2184640. This should fix the e2e tests in CI.
> import rpm gpg key for CentOS

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
We switch the deployment tag to HEAD, instead of the last non-merge commit. The reason behind this change is to better enable cherry-picks onto the production branch, which are added to the branch via a new merge commit. Since cherry-picks modify the commit hash, we cannot reuse the image built from `main` commits. The images are produced by app-interface, which only builds images for the latest merge commit of the `main` and `production` branches.
With this change we lose the ability to deploy the exact same image to both stage and production during regular releases, because a new image is build for the production HEAD. However, the contents as calculated by git between the stage and production image will be identical, which is considered sufficient at this time.
In particular, this …
> use HEAD as tag for fleetshard-sync image

- .openshift-ci/e2e-runtime/Dockerfile
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This release includes two additional cherry-pick commits:
* use HEAD commit in dp terraform script to ensure the image exists.
* import rpm gpg keys to work around CoreOS issue.
> Bugfix-release 2023-04-04.2.1c8acf5

- .github/workflows/rds.yaml
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Do not run RDS tests from forks. Second try. The first one was made in #930.
GHA
> ROX-16355: Do not run RDS tests from forks

- go.mod
- go.sum
- pkg/client/redhatsso/serviceaccounts/client.go
- pkg/client/redhatsso/serviceaccounts/client_test.go
- pkg/client/redhatsso/serviceaccounts/integration/client_test.go
- pkg/services/sso/redhatsso_service.go
- test/mocks/redhatsso.go
This PR updates the location and version of the `app-services-sdk-go` used. The old package used [here](https://github.com/redhat-developer/app-services-sdk-go) is now deprecated and is being replaced by the [Core SDK](https://github.com/redhat-developer/app-services-sdk-core).
> MGDX-396 Upgraded app-services-sdk-go to Core SDK

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
This is a follow up to #846, which added cluster name tags to the Central RDS instances. Now we want to filter the exported metrics based on these cluster names in the cloudwatch exporter. This is done to allow us to only export metrics for RDS instances which belong to a specific ACS data plane region.
I decided to switch the exporter from https://github.com/prometheus/cloudwatch_exporter to https://github.com/nerdswords/yet-another-cloudwatch-exporter, because it has better filter and region support.
The metrics themselves are not changed by this, only the labels change slightly. Most notably, the dimension label will change from `dbinstance_identifier` to `dimension_DBInstanceIdentifier`. We will have to change this in the alerts and dashboards.
Tested the exporter on dev cluster.
> ROX-15136: filter aws metrics by cluster name

- docs/development/setup-osd-cluster-idp.md
- dp-terraform/osd-cluster-idp-setup.sh
This PR removes the creation of the HTPasswd provider, since all new DP clusters should make use of the OIDC provider.
It also changes the way one obtains a token to login to the cluster to create the service account used during provisioning the dataplane clusters:
`ocm cluster login` will be used and it's expected to interactively login through browser to obtain the token, and pass the token as input to the cluster.
Since the script currently is only executed manually and during setup of the dataplane cluster, this should be sufficient enough for the time being.
```
./osd-cluster-idp-setup.sh stage acs-stage-dp-02
```
> ROX-15355: Remove HTPasswd creation

- .github/workflows/deploy-production.yaml
Adds acs-prod-eu-01 terraforming to the CD pipeline.
No manual testing performed.
> ROX-16362: Terraform acs-prod-eu-01 on CI

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
A few improvements to the cloudwatch exporter configuration.
* Add `eu-west-1` to AWS regions to search for resources to export.
* Use global `statistics` block to reduce config bloat.
* Restrict to metric series with `DBInstanceIdentifier` dimension to avoid exporting RDS cluster metrics (only export RDS instance metrics).
Tested config with local cloudwatch exporter running against our stage AWS account.
> expand cloudwatch exports to eu region

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Routine update of the observability operator. We benefit mostly from golang deps updates and updates to the operator images. Changelog: https://github.com/redhat-developer/observability-operator/compare/v4.0.4...v4.2.1
The migration should be automatic. Test in stage first, and upgrade in prod if everything goes well.
> bump observability operator to v4.2.1

- dp-terraform/helm/rhacs-terraform/charts/logging/README.md
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-01-rbac.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-02-configmap.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-03-deployment.yaml
The goal here is to persist kubernetes events to cloudwatch in order to ease later troubleshooting of issues.
This relies on the openshift eventrouter component.
```
```
> ROX-13092: Add openshift eventrouter to persist kubernetes events to CloudWatch

- dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Use the newly introduced availability SLI recording rules (see https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/62734) in the SLO dashboard. In particular, the availability SLO now incorporate the K8s pod ready status.
> ROX-14030: use new availability SLI rules in dashboard

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Adds an optional helm chart value so that we can pass the central label selector to the operator using the helm chart
> ROX-16338 Add central label selector to operator helm chart

- cmd/fleet-manager/main.go
- internal/dinosaur/providers.go
- pkg/providers/core.go
Hardcoding the fleet-manager CLI command registration instead of using the DI container registration.
This removes the need of reflection and cleans up error logs dramatically.
The DI container is still passed to all commands.
- run CLI should work
> Hardcode Fleet-Manager CLI command registration

- fleetshard/main.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
Add an Operator Version label to Central instances. It will be used for Canary Upgrades.
Additional note: [k8s Label, selector, and annotation conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#label-selector-and-annotation-conventions)
1. Build and deploy
```
```
2. Create ACS instance
3. Check Labels:
```
kubectl get pods -l 'stackrox.io/operator-version=rhacs-operator.v3.74.0' -n ascms
```
> ROX-16205: Add Operator Version label to Centrals

- probe/pkg/probe/probe.go
Small improvement of the probe logging:
* Remove warnings emitted frequently while the probe is waiting for the instance to be ready/deleted. This warning creates a lot of spam in the logs.
* Log target configuration when a probe run starts.
> improve probe logging

- probe/pkg/metrics/metrics.go
- probe/pkg/metrics/metrics_test.go
- probe/pkg/metrics/server_test.go
- probe/pkg/probe/probe.go
- probe/pkg/runtime/runtime.go
Add region label to indicate in the metrics what data plane region the probe requested an instance in. For example, the counter `acs_probe_runs_started_total` will become `acs_probe_runs_started_total{region="us-east-1"}`. This will be especially useful if we add a regional round robin to the probe in the future.
CI
> add region label to probe metrics

- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_versions.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- openapi/fleet-manager-private.yaml
This PR changes the internal private API so that Fleet-Manager sends actual and desired version information to fleetshard-sync. It also modifies the reconcile cache of fleetshard-sync so that centrals reconciles are not skipped if actual version does not match desired version.
Manual testing:
- create a central in local cluster with fleet-manager/fleet-shard-sync
```
```
> send actual and desired version to fleetshard in private API

- pkg/client/fleetmanager/auth.go
- pkg/client/fleetmanager/auth_ocm.go
The OCM logger creates a lot of noise, especially on CLI environments.
This PR disables the OCM logger by default.
- CI
- Compile fleet-manager and connect to OCM
> Disable OCM logger by default

- Makefile
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
- pkg/logger/logger.go
Clean up logs. Added logger to only log if the given integer value had changed.
```
```
> ROX-15242 - Reduce fleetshard and fleet-manager log noise

- deploy/helm/probe/templates/01-operator-04-deployment.yaml
- deploy/helm/probe/values.yaml
Sets the resource requests and limits for `probe`
The values were derived from the observed metrics on prometheus/grafana. These resource defaults are a bit overkill for the actual observed usage. I was not comfortable putting less than this for a production deployment.
> ROX-15980 probe resource requests and limits

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Sets the resource requests and limits for observability components
The values were derived from the observed metrics on prometheus/grafana.
> ROX-15980 observability resource requests and limits

- e2e/e2e_test.go
- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
- fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
- fleetshard/pkg/central/reconciler/reconciler.go
Sets the resource requests and limits for the egress-proxy.
The values were derived from the observed metrics on prometheus/grafana. These resource defaults are a bit overkill for the actual observed usage. I was not comfortable putting less than this for a production deployment. 
It also seems like the `values.yaml` file was ignored for the `tenant-resources`. This PR also adds changes to use these values by default and apply overrides on top of them. 
The current cluster configuration deploys 1 replica of the `egress-proxy`, so I've changed the value to reflect that as well.
> ROX-15980 set resource requests and limits to the egress-proxy

- e2e/e2e_test.go
The e2e admin tests fail because they set resource requests and limits for central to values that did not allow central pods to be created properly. This PR adjusts those resources so that they are close to the default values used in the "non-admin" tests. With this the test should work again.
- ~~[ ] Add secret to app-interface Vault or Secrets Manager if …
> fix e2e admin tests by reducing required resources

- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/dinosaur.go
- internal/dinosaur/pkg/services/telemetry.go
- internal/dinosaur/pkg/services/telemetry_test.go
Our Segment framework sends several group properties requests to raise chances for the following events to catch the group properties. Unfortunately, as this is done asynchronously, Fleet Manager didn't have a chance to get the properties.
The PR introduces a 6 seconds pause before issuing the central creation tracking event.
```
```
> Add `sleep(6s)` before tracking central creation

- .github/workflows/rds.yaml
- Makefile
- dev/env/defaults/00-defaults.env
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
This PR changes the central tenant DB deletion for RDS so that it always creates a final snapshot this is required in order to restore the tenant in case it has been deleted accidentally by a customer, an engineer or an error in the code.
Adding test case and running rds tests locally and in CI.
```
```
> ROX-13692: create final snapshot for tenant db

- dp-terraform/osd-cluster-idp-setup.sh
This PR adds commands necessary to give all RH employees access to our monitoring stack(Prometheus, Alertmanager, Grafana) in dataplane clusters.
All existing dataplane clusters are already updated, this PR is in case we would want to use new dataplane cluster.
Important limitation that we faced during work on this feature is that creating IdP via `ocm` command does not allow for `groups` claim mapping. Thus we patch IdP resource later in the setup via `ocm patch`.
1. All commands were used during modification of existing clusters
> ROX-15954: Setup non-admin access to observability resources

- fleetshard/pkg/k8s/route.go
https://issues.redhat.com/browse/ROX-16791
Manually edited the route in staging
```
time curl 'https://<url>/api/graphql?opname=triggerScan' --data-raw $'{"operationName":"triggerScan","variables":{"clusterId":"*","standardId":"*"},"query":"mutation triggerScan($clusterId: ID\u0021, $standardId: ID\u0021) {\\n  complianceTriggerRuns(clusterId: $clusterId, standardId: $standardId) {\\n    id\\n    standardId\\n    clusterId\\n    state\\n    errorMessage\\n    __typename\\n  }\\n}\\n"}'   --compressed
real	5m56.838s
user	0m0.019s
sys	0m0.018s
```
```
```
> ROX-16791: Increase route timeout to 10m to allow for longer operations

- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
This PR enables exporting of PostgreSQL logs to CloudWatch, for newly created RDS clusters. 
Existing instances will be modified separately.
- [] ~~Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication channel.~~
Tested in a local cluster, by running:
And then waiting for a Central to start successfully.
To test locally, I had to make the DB publicly accessible. For this purpose, I added a new VPC, security group and DB subnet group in dev on AWS.
``` …
```
> ROX-16894: Enable CloudWatch log exports for new RDS DBs

- internal/dinosaur/pkg/defaults/default_central_spec.go
- internal/dinosaur/pkg/defaults/default_scanner_spec.go
Up for debating the increases in requests, but the limits should be more near to what we expect customers to run in production. The result of this is that it could lead to more evictions, but also should give customers much faster API times. I'm seeing timeouts in the metrics
```
```
> ROX-16883: Increase resource limits

- .github/workflows/rds.yaml
- Makefile
- dev/config/dataplane-cluster-configuration-crc.yaml
- docs/development/howto-e2e-test-rds.md
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
The first PR  #994 was causing errors in the stage environment because the reconciler would proceed to run delete DB calls to AWS even though the deletion was already in progress. The ad-hoc fix for staging was to revert the PR. This PR is the new attempt to implement the feature without breaking reconciliation logic.
See the new file `howto-e2e-test-rds.md`.
Also running local RDS integration tests.
```
```
> ROX-13692: fix final snapshot creation

- .secrets.baseline
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
- fleetshard/pkg/central/cloudprovider/dbclient.go
- fleetshard/pkg/central/cloudprovider/dbclient_moq.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
Probes are creating a lot of central tenants and deleting them again. This causes us to hit the limit for manual DB snapshots because every tenant deleted create a final DB snapshot. This PR skips final DB snapshots for centrals created by the probe.
```
make ocm/setup …
```
> ROX-13692: skip final snapshots for probe

- .secrets.baseline
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
- fleetshard/pkg/central/cloudprovider/dbclient.go
- fleetshard/pkg/central/cloudprovider/dbclient_moq.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
Inspired by https://github.com/stackrox/acs-fleet-manager/pull/1018 this PR does not export RDS logs to CloudWatch for Centrals created by the Probe service.
These instances are creating a lot of useless log groups and basically spamming CloudWatch.
```
```
> ROX-16561: Do not export RDS/Postgres logs to CloudWatch for Probe instances

- .secrets.baseline
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-dead-mans-switch.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-pagerduty.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
This will enable us to set up a Slack receiver for alerts that we don't want going to PagerDuty.
This configuration was pulled directly from the generated version of this secret in one of our data plane clusters and modified to be generated by this Helm chart instead.  There is no functional difference between this config and the one generated by the Observability operator.
The PagerDuty and Dead Man's Snitch secrets are deleted since those secrets are now used directly in the Alertmanager configuration.
* Deployed CRC (CodeReady Containers)
* Changed dir to `dp-terraform/helm/rhacs-terraform/charts/observability`
* Created a Github personal token to correctly configure the Obervability operator
* Stuck the token and repo config into `values.yml`
* Ran `helm template . | oc apply -f -`
* …
> Directly manage Alertmanager configuration

- scripts/fmcurl
Add the FM_URL variable to fmcurl script. To also use it for easy access to fleet-manager on other urls.
- ~~[ ] CI and all relevant tests are passing~~
```
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> …
```
> add FM_URL env variable for fmcurl script

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This is part of a larger effort to stop treating stage alerts as critical alerts in PagerDuty.  The specific changes being made in this PR:
* Pass the `severity` parameter in the PagerDuty receiver configuration. This will be used in production to capture non-critical production events in PagerDuty without triggering a critical notification to on-call engineers.  (These events are currently dropped in Alertmanager)
* Switch to the PagerDuty v2 Events API.  This is required for PD to recognize the `severity` parameter.  This is done by switching from `service_key` to `routing_key`.
* Updated the key in `terraform_cluster.sh` (and thus AWS Secrets Manager) to reflect the routing key change.
* Made PagerDuty the default receiver in the Alertmanager config.  This will send non-critical alerts …
> ROX-17083: Make PagerDuty the default receiver

- pkg/logger/logger.go
- pkg/logger/logger_test.go
Fixed incorrect behavior of `logger.InfoChangedInt32`. The previous implementation used `cache.LoadOrStore` which stored only the first value for the key. This resulted in filtering only messages with the number of central instances stored right after starting fleetshard-sync, i.e.:
```
fleetshard starts
36 centrals -> Message: Received central count changed: received 36 centrals
36 centrals -> filtered
36 centrals -> filtered
37 centrals -> Message: Received central count changed: received 37 centrals
37 centrals -> Message: Received central count changed: received 37 centrals
37 centrals -> Message: Received central count changed: received 37 centrals
37 centrals -> Message: Received central count changed: received 37 centrals
36 centrals -> filtered
36 centrals -> filtered
36 centrals …
```
> Fix central count log message deduplication

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/fleetshardmetrics/metrics.go
- fleetshard/pkg/fleetshardmetrics/metrics_test.go
- fleetshard/pkg/runtime/runtime.go
This PR adds a Prometheus metric that exposes the pause-reconcile instances managed by fleetshard-sync.
The metric is implemented as a Gauge, where value 1 means an instance is pause-reconcile'd, and 0 means it's not. Values are labeled by the instance name.
See also https://github.com/stackrox/rhacs-observability-resources/pull/102
Manual testing:
```
kubectl -n acsms port-forward fleetshard-sync-5479d64d89-v4mph 8080:8080
```
Then opened `http://localhost:8080/metrics` in a browser and checked that the new metrics are there and have correct values, before and after adding the pause-reconcile annotation, e.g.:
```
kubectl -n rhacs-chs64i3dabr0026a6fag edit centrals.platform.stackrox.io test-central-1
```
``` …
```
> ROX-15234: Prometheus metric for pause-reconcile instances

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/leader-election-role.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-role.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
Fix RBAC operator rules in fleetshard deployment.
These were missing when the fleetshard-based installation was introducded.
Currently this operator installation is protected by a feature flag and not used in production.
- needs to be added later
> Fix operator RBAC rules

- fleetshard/pkg/central/reconciler/reconciler.go
https://issues.redhat.com/browse/ROX-17712
Adding retries to wait for Central to be deleted, not just marked for deletion.
> ROX-17712: wait for central to be deleted

- fleetshard/pkg/central/operator/upgrade_test.go
Fix the CI by correcting the name of a service account that was changed in a previous PR (https://github.com/stackrox/acs-fleet-manager/pull/1084) but not in the test
```
```
> Fix service account name in unit test

- fleetshard/pkg/central/operator/upgrade.go
- fleetshard/pkg/central/operator/upgrade_test.go
- fleetshard/pkg/runtime/runtime.go
Do not fail on empty operator images. This lead fleetshard-sync to CrashLoop if no Centrals are available.
- /
> Do not fail on empty operator images

- dev/env/scripts/lib.sh
- dev/env/scripts/up.sh
- docs/development/feature-flags.md
- docs/legacy/feature-flags.md
- fleetshard/config/config.go
- fleetshard/config/config_test.go
- fleetshard/main.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
- pkg/features/feature.go
- pkg/features/features.go
- pkg/features/features_test.go
- pkg/features/list.go
Adds feature flags package from StackRox repository.
It removes the buildinfo protection for release build. This flag is not supported in fleet-manager and not necessary as fleet-manager is not shipped to customers.
Added documentation with more details.
- unit tests
- deploy acs-fleet-manager locally with dev scripts
> Add feature flags package

- dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
- dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/config/config.go
- fleetshard/config/config_test.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
It turned out that the static key or jwt loaded from the OAuth identity provider is not suitable for the local development, because:
1. AWS rejects tokens with the long validity period even if they are not expired. It means that we need to refresh the "static" token periodically, which requires some effort.
2. It's hard to setup the token in a case when fleetshard-sync runs locally out of the cluster.
**As a result, fleetshard-sync can't start locally with `MANAGED_DB_ENABLED=true`**
We are forced to use the access key for this special case, as it is most convenient. It will also help in addressing the concerns raised in #1078.
The change in `rds.go` will make the configuration loadable from environment variables, allowing the auth type to be switched. In the case of dev environments, the …
> Use the access key for the fleetshard-sync AWS auth on the local dev environment

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/route.go
Fleetshard-sync does not react to changes in host names or the TLS certificates for central tenant routes. This result in the problem that rotating the certificates for central tenants is currently not possible without manual interaction with the routes.
This PR changes fleetshard-sync, so that it recognizes changes in the private.ManagedCentral Endpoints configuration. If it detects changes the routes are updated accordingly.
- ~~[ ] RDS changes were e2e tested …
> ROX-17532: add update logic for central routes on Host and TLS changes

- .golangci.yml
- Makefile
My pre-commit runs sometimes take a lot of time. It seems that on my machine they are often executed against all files.
I didn't figured out how to fix this, instead added a workaround as a Makefile target.
- Run `make pre-commit`
> Add pre-commit target for faster runs locally

- fleetshard/pkg/central/reconciler/reconciler.go
> Prefactor: extract status collection to dedicated function in fleetshard central reconciler

- fleetshard/pkg/central/reconciler/reconciler.go
> Prefactor: extract central DB reconciliation to dedicated function in fleetshard central reconciler

- fleetshard/pkg/central/reconciler/reconciler.go
> Prefactor: extract central CR removal reconciliation to dedicated function in fleetshard central reconciler

- fleetshard/pkg/central/reconciler/init_auth.go
- fleetshard/pkg/central/reconciler/reconciler.go
> Prefactor: extract auth provider configuration reconciliation to dedicated function in fleetshard central reconciler

- fleetshard/pkg/central/reconciler/errors.go
- fleetshard/pkg/central/reconciler/reconciler.go
> Prefactor: extract central CR definition creation to dedicated function in fleetshard central reconciler

- .secrets.baseline
- config/dataplane-cluster-configuration-staging.yaml
- dev/config/dataplane-cluster-configuration-crc.yaml
- dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
- dev/config/dataplane-cluster-configuration-minikube.yaml
- dev/config/dataplane-cluster-configuration-rancherdesktop.yaml
- dev/env/manifests/shared/03-configmap-config.yaml
- docs/development/setup-developer-osd-cluster.md
- internal/dinosaur/pkg/migrations/20230621000000_remove_available_operators_field_cluster.go
- internal/dinosaur/pkg/migrations/migrations.go
Remove available_central_operator_versions database field
- CI
- Install Fleet-Manager and see if database migration works
- Check that Data-Plane clusters are not broken
> Remove available_central_operator_versions database field

- probe/pkg/probe/probe.go
During the release process, it would be helpful to see which central is created by probe.
This can be helpful for a few reasons:
1. when we update ACS operator and all ACS instances are paused for reconciliation. A new instance would still be created with a new version of the operator and it would be helpful to see the ID of the instance created by probe, so that we can make a closer look at used images in generated resources and see if it is really using a new version
2. sometimes, during release, when we are rolling out updates for ACS instances and there are several restarts we can see a lot of alerts in a pending state, but we are not sure if that is a probe instance or not. By looking at the log what was created by probe we could easy ignore related namespace and identify if there …
> Tweak probe log to show central ID on create

- scripts/lib/helm.sh
Make `helm.sh` build dependencies in the chart directory instead of the working directory
When I run the terraforming script from the project root, I get the following error:
```
Error: Chart.yaml file is missing
```
```
```
> Make helm.sh build dependencies in the chart directory instead of the working directory

- probe/pkg/probe/probe.go
- probe/pkg/probe/probe_test.go
Currently the probe does not delete instances that have been created by other probe instances to prevent interfering with other concurrently running probes. This can lead to orphaned instances, if the probe pod has an ungraceful shutdown. To clean up in such cases, also delete Centrals from other probe instances if they are older than 24 hours.
CI
> remove orphaned probe instances

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
- fleetshard/pkg/central/operator/upgrade.go
- fleetshard/pkg/central/operator/upgrade_test.go
- fleetshard/pkg/runtime/runtime.go
Add method for removing unused operator deployments based on desired slice of operator images. So any deployed image which **is not** presented in the desired slice should be removed.
```
make deploy/dev-fast
```
> ROX-17987: Remove unused Operator deployments

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- pkg/features/list.go
This PR adds some logic to prevent fleetshard from updating Centrals if there are no changes, which prevent unnecessary opreator reconciliation loops.
> ROX-17712 prevent unnecessary central updates

- fleetshard/pkg/central/reconciler/reconciler.go
The operator is detecting changes because of a diff on the scanner component enabled. It seems like this is related to the `+kubebuilder default` behavior. Though, since webhooks are disabled in ACSCS, the dry-run ugprade doesn't catch this. Explicitely enabling scanner should circumvent the issue.
> ROX-17712 Explicitly enable scanner

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Disable dogfooding in prod
```
```
> Release cherry-pick: Disable dog-fooding in prod (#1141)

- scripts/lib/external_config.sh
Chamber has inconsistent error handling for different backends:
- if the requested "service" does not exist in Parameter Store it will not return an error code
- if the requested "service" does not exist in Secret Manager it will return an error code
This is a problem for us because not all results of the AWS Terraform process store "output" in Secret Manager. Some values are stored in Parameter Store (i.e. ARNs, generated names, etc.)
This PR is adding a small tweak to ignore errors from chamber when "service" does not exist in Secret Manager.
- ~[ ] Add the ticket number to the PR title if available, i.e. …
> Suppress chamber errors for secretsmanager backend

- dp-terraform/helm/rhacs-terraform/templates/_helpers.tpl
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
Insert image pull `dockerconfigjson` for quay to Fleetshard-sync secret. Credentials comes from Secrets Manager.
```
helm upgrade --install --debug --dry-run rhacs-terraform \
--namespace rhacs \
--values ./values-acs-dp-02.yaml
```
> ROX-17723: Add image pull secret for quay to Fleetshard-sync

- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/_helpers.tpl
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-secrets.yaml
Move dogfooding instance from `rhacs` to `rhacs-secured-cluster` namespace
```
HELM_DRY_RUN=true HELM_DEBUG=true AWS_SAML_ROLE=<stage user>  ./terraform_cluster.sh stage stage_cluster
```
> ROX-18445: Move secured-cluster to dedicated namespace

- Dockerfile
```
MANAGED_DB_ENABLED=TRUE make deploy/dev
.....
create an isntance
....
Check logs
...
I0717 11:50:34.612442       1 logger.go:208] Received central count changed: received 0 centrals
I0717 12:41:31.713546       1 logger.go:208] Received central count changed: received 1 centrals
I0717 12:41:31.714822       1 reconciler.go:125] Start reconcile central rhacs-ciqjdadn69cg01rgplq0/test
I0717 12:41:31.857270       1 charts.go:145] Creating object rhacs-ciqjdadn69cg01rgplq0/egress-proxy-config
I0717 12:41:31.908291       1 charts.go:145] Creating object rhacs-ciqjdadn69cg01rgplq0/egress-proxy
I0717 12:41:32.010662       1 charts.go:145] Creating object rhacs-ciqjdadn69cg01rgplq0/egress-proxy
I0717 12:41:32.163467       1 charts.go:145] Creating object rhacs-ciqjdadn69cg01rgplq0/egress-proxy …
```
> Add rds ca certs to unprivileged user

- probe/cmd/probe/main.go
- probe/pkg/metrics/metrics.go
- probe/pkg/metrics/metrics_test.go
- probe/pkg/metrics/server.go
- probe/pkg/metrics/server_test.go
Initialize gauage metrics to avoid complications due to undefined gauge values. See https://github.com/stackrox/rhacs-observability-resources/pull/115. The timestamps default to 0, which translates to `1970-01-01`. It is defined such that any actual timestamp will be larger than this value.
```
```
> fix(probe): init probe metric gauges with zero value

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
The Central PVC has been deprecated with the transition to postgres as a storage backend. See https://docs.openshift.com/acs/4.1/upgrading/upgrade-operator.html#remove-central-attached-pv-operator_upgrade-operator for reference on how to disable the PVC.
> chore(fleetshard): disable central-db PVC

- .secrets.baseline
- fleetshard/pkg/central/cloudprovider/awsclient/rds.go
- fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
- fleetshard/pkg/central/cloudprovider/dbclient.go
- fleetshard/pkg/central/cloudprovider/dbclient_moq.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
In preparation for dynamic DB URLs, this PR adds the following changes:
* the DB client interface now supports different names for the databaseID and the acsInstanceID
* the DB clusters and instances are tagged with the acsInstanceID (this is needed because if the names DB name is changed and there is data loss, we can use the tag to determine to which ACS instance the DB belonged to)
Manually verified that the DB cluster and instances created by the AWS integration tests are properly tagged.
```
```
> ROX-18427: tag RDS DBs with their corresponding ACS instance ID

- dev/env/scripts/create-imagepullsecrets
- dev/env/scripts/docker.sh
- scripts/install_operator_canary.sh
- Install necessary pull secrets for operator namespace
- download necessary images
```
colima k reset
scripts/install_operator_canary.sh
```
> Fix local bootstrap for RHACS_TARGETED_OPERATOR_UPGRADES mode

- dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
This PR fixes the configuration for audit logs to use the `us-east-1` region because CloudWatch log groups will be created there.
Logging has the same setup. Log Groups are created in the `us-east-1` region.
PR to move Log Groups and SSM params is provided here: https://github.com/stackrox/acs-fleet-manager-aws-config/pull/111
Changes are already applied, and AWS resources are provisioned on staging.
- ~~[ ] Discussed security and business related topics privately. Will move any security and business related topics that …
> ROX-14547: Configure audit logs to use proper region

- dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/06-statefulset.yaml
This PR adds a trigger to roll out aggregator pods once a year in order to use a rotated certificate.
- ~~[ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
- ~~[ ] Check AWS limits are reasonable for changes provisioning new resources~~
Manual testing is possible on a local cluster (i.e. colima), but it requires some modifications to go around OpenShift generated secrets.
Steps:
1. …
> ROX-17260: Add annotation to trigger yearly certificate rotation

- fleetshard/pkg/runtime/runtime.go
Skip ACS Operator installation attempt if it's already attempted
Delete duplicate operator images
~~- [ ] CI and all relevant tests are passing~~
```
1. Prepare cluster for canary upgrade feature
scripts/install_operator_canary.sh
2. Create a new …
```
> ROX-18728: Add operator deployment cache

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
Alerts in PagerDuty are currently all grouped together, even when it doesn't make any sense.
So instead, group PD alerts by rhacs_instance_id if rhacs_instance_id is on the alert; otherwise group by cluster_id.
```
```
> Update alertmanager grouping confiugration

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
* `rhacs_instance_id` -> `namespace`: not all alerts have `rhacs_instance_id`
* add `severity`: don't want to group alerts with different severities together
```
```
> Changing labels to group by

- fleetshard/pkg/central/reconciler/reconciler.go
Diagnostic bundle functionality within central requires access to k8s API to obtain diagnostic data about central cluster.
This PR aims to provide such access via `NO_PROXY` variable.
TBD
> Add k8s API to NO_PROXY configuration

- fleetshard/pkg/central/reconciler/reconciler.go
With the introduction of declarative config, the default group, also referred to as the "minimum role", has been made declarative. That means that currently it is not possible to change it going forward, or use a different value than `None`.
While only a limited amount of users do use the feature (currently only two instances across all instances use this), we still don't want to break the behavior for them.
- see CI.
> fix(reconciler): make default group not declarative

- dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
Expose the ACS operator repository in the terraform Helm chart as a value. This comes in handy when deploying a data plane cluster with an upstream operator version, because it allows to inject your own images.
```
```
> feat(terraform): add acsOperator repository value

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
For dev deployments we often deploy fleetshard-sync without managed DB integration. In these cases, we still need the Central PVC. Hence, only set the obsolete PVC annotation if `managedDB=true`.
```
```
> fix(fleetshard): set Central PVC annotation only if managedDB=true

- deploy/helm/probe/deploy.sh
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- Allow the special case of int==integration.
- Teach probe deploy script about integration env.
CI should cover the parts that **can** be tested.
> ROX-16090: Support integration in a couple more places

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
This PR adds a second declarative config mount point to ACSCS centrals. 
The secret referenced here will not be created by reconciler, but rather manually and only when customer requests multiple orgs support. In that case `cloud-service-manual-declarative-configs` secret will be created and populated with the corresponding auth provider configuration.
The reasons to introduce separate secret here:
* Want to separate ownership - `cloud-service-sensible-declarative-configs` contents are  controlled only by `fleetshard-sync`, let's keep it that way
* It's easier to identify if declarative configuration was manually changed if secret is separate
Ideally, I would like to name secrets `cloud-service-reconciled-declarative-configs` and `cloud-service-manual-declarative-configs`, however, …
> ROX-19330: Add second declarative config mount point to central CR

- internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
Add a nil check because when `err != nil`, it is not guaranteed that `resp` is not nil. See https://issues.redhat.com/browse/ROX-19332 for an example of where we ran into a nil pointer dereference because of the missing check.
PS: Sadly the golang standard library does not provide a nil-safe getter for the status code :(
> fix(fleet-manager): add nil check to deleting mgr

- dev/config/dataplane-cluster-configuration-infractl-osd.yaml
- dev/env/scripts/up.sh
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/config/config.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/cipher/cipher.go
- fleetshard/pkg/cipher/local_base64_cipher.go
- fleetshard/pkg/cipher/local_base64_cipher_test.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/k8s/secret.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
- internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/services/data_plane_dinosaur.go
- openapi/fleet-manager-private.yaml
This PR adds the logic to report K8s secrets created by FS sync or the RHACS operator back to store them in fleet-manager (namely `central-tls` and `central-db-password`). The secrets are encrypted using AWS KMS to ensure they are stored securely in FMs database and in transit. We need to create the KMS keys before merging this into main and deploying it to the stage environment. Because of that the PR: https://github.com/stackrox/acs-fleet-manager-aws-config/pull/117 has to be merged first.
This is part of the Epic https://issues.redhat.com/browse/ROX-17060, the implementation to restore secrets if they are missing in the cluster will be done in another PR.
In this PR we implement following parts of the overall solution:
- Getting the secret from cluster
- Encrypting them
- Report from …
> ROX-18428: report secret data to fleet-manager

- .secrets.baseline
- templates/service-template.yml
For integration env we need to use a slightly different name to avoid clashes with the stage RDS which resides in the same appsre stage account.
Also updated the secrets baseline since presubmit asked me to :shrug:
However I did not include all the changes applied by local pre-submit because they would fail in the CI presubmit check.
CI is enough.
> ROX-19478: Parameterize manager RDS secret name.

- probe/pkg/probe/probe.go
- probe/pkg/runtime/runtime.go
Prevent the `()` in log when the Central response is empty.
```
E0904 10:29:57.650706 1 probe.go:103] could not list centrals: : Get "https://api.integration.openshift.com/api/rhacs/v1/centrals": context deadline exceeded
W0904 10:29:57.650759 1 runtime.go:44] cleanup failed: cleanup centrals failed: retry failed: context deadline exceeded: probe run failed: creation of central instance failed: parsing HTTP response: undefined response type
I0904 10:29:57.650781 1 probe.go:69] probe run has been started: fleetManagerEndpoint="https://api.integration.openshift.com/", provider="aws", region="us-east-1"
I0904 10:29:57.661891 1 probe.go:147] creation of central instance () requested
I0904 10:29:57.661931 1 probe.go:54] elapsed time: 11.143458ms
I0904 10:29:57.661946 1 probe.go:79] probe run …
```
> chore: fix probe log when response if empty

- dev/env/scripts/up.sh
- e2e/e2e_auth_test.go
- e2e/e2e_test.go
- fleetshard/config/config.go
- fleetshard/main.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/cmd/admin/centrals/list.go
- internal/dinosaur/pkg/cmd/centrals/create.go
- internal/dinosaur/pkg/cmd/centrals/delete.go
- internal/dinosaur/pkg/cmd/centrals/get.go
- internal/dinosaur/pkg/cmd/centrals/list.go
- internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
- pkg/client/fleetmanager/auth.go
- pkg/client/fleetmanager/auth_ocm.go
- pkg/client/fleetmanager/auth_rhsso.go
- pkg/client/fleetmanager/auth_static_token.go
- probe/cmd/probe/main.go
- probe/internal/cli/cli.go
- probe/pkg/fleetmanager/client.go
- scripts/lib/log.sh
Reverts stackrox/acs-fleet-manager#1229
We have a problem with the deletion of instances on staging and this is causing production alerts.
> Revert "ROX-19494: Bump wait time and provide context for initialization."

- fleetshard/pkg/central/postgres/dbconnection.go
- fleetshard/pkg/central/postgres/dbconnection_test.go
- fleetshard/pkg/central/postgres/dbinit.go
- fleetshard/pkg/central/reconciler/reconciler.go
Due to changes in ACS 4.2, some changes to the Central DB connection string in ACS CS are required.
The new connection strings should be backwards compatible with older ACS versions (ACS CS is currently running v4.1.3).
Tested RDS changes E2E - with both ACS v4.1 and v4.2.
Connection string from Central logs:
```
Migrator: 2023/09/08 16:25:35.546389 log.go:18: Info: connect to gorm: "host=rhacs-cjtkg9j3d8v001se2n8g-db-cluster.cluster-cz7zwsnynmtn.us-east-1.rds.amazonaws.com port=5432 user=rhacs_central dbname=central_active statement_timeout=1200000 client_encoding=UTF8 sslmode=verify-full sslrootcert=/usr/local/share/ca-certificates/00-rds-ca-bundle.crt pool_min_conns=10 pool_max_conns=90"
```
```
make ocm/setup OCM_OFFLINE_TOKEN=<ocm-offline-token> …
```
> ROX-19228: ACS CS connection string updates for 4.2

- dev/env/scripts/up.sh
- fleetshard/main.go
- scripts/lib/log.sh
See ticket for timeouts we're seeing from time to time. This bumps the timeout a little and provides better/more log messages to be able to debug this better in the future should the bump prove insufficient.
FTR, this is the "safe" part of #1229 that does not include the context propagation changes, which proved problematic.
@vladbologa please kindly verify that the date command works as expected on a mac.
CI should be sufficient.
> ROX-19494: Increase timeout and improve debugability of e2e test.

- fleetshard/pkg/central/reconciler/proxy_test.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
Since we use ACSCS instead of ACSMS now, let's update mentions of ACSMS as to not confuse future code contributors.
1. CI is enough
> Rename acsms -> acscs in proxy_test.go and dinosaurs_auth_config_mgr.go

- fleetshard/pkg/central/reconciler/reconciler.go
To keep logs more clean we remove logged encrypted secrets before info logging the status of a reconciliation.
- ~~[ ] CI and all relevant tests are passing~~
- ~~[ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
- ~~[ ] Check AWS limits are …
> obscure data in fleetshard-sync status logs

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
Currently the name of a Central DB is fixed and based on the Central's ID. E.g. for the ID `cjmugfm9rusboqitae5g` the DB cluster must be called `rhacs-cjmugfm9rusboqitae5g-db-cluster`.
This PR gives the possibility to override the default naming scheme. For example, if the above DB is restored from backup into `rhacs-examplebackup-db-cluster`, then fleetshard-sync can be instructed to use the alternate name in the following way:
`kubectl create configmap central-db-override --namespace=rhacs-cjmugfm9rusboqitae5g --from-literal=databaseID=examplebackup`
Tested E2E locally by creating a ConfigMap as described above and confirming that Central can connect to an overridden DB.
``` …
```
> ROX-18427: read central DB ID override from optional ConfigMap

- templates/service-template.yml
Add `gitops-config-file` which later can be used to parse  gitops config in fleet manager. This file represents configmap from gitops repository
~- [ ] Add secret to app-interface Vault or Secrets Manager if necessary~~
N/A
> ROX-19558: Mount gitops config to Fleet Manager

- internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
- internal/dinosaur/pkg/api/admin/private/api_default.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/rhsso/augment.go
- internal/dinosaur/pkg/routes/route_loader.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
- openapi/fleet-manager-private-admin.yaml
- pkg/errors/errors.go
This PR creates an admin API that:
* creates a new client/secret pair via the dynamic client sso.r.c API.
* delete the previous dynamic client.
* updates the client/secret pair in fleet manager DB.
In case of failure to either use new client or delete the previous one, client ID is logged that allows for ACSCS engineer to manually delete stale client.
In case dynamic clients are not configured, `404` status code is returned.
The dynamic clients API client is initialized once, however, it might not be initialized properly if dynamic clients are not configured. Whether dynamic clients are configured is checked on every request.
(You need to set up `SSO_CLIENT_ID_DEFAULT` and `SSO_CLIENT_SECRET_DEFAULT`, as well as specify `--central-idp-client-id` as …
> ROX-11640: RHSSO dynamic clients rotation API

- internal/dinosaur/pkg/rhsso/augment.go
Within a recent incident, we received failures when creating dynamic clients for sso.r.c.
The error message was lackluster, as it only included: `403 Forbidden`.
The API itself _should_ return a proper error message, however we currently do not log it.
This PR changes this by ensuring we log the API response contained within the custom error type.
```
```
> ROX-19588: Log HTTP error response

- dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime_test.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/api_agent_clusters.go
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
- openapi/fleet-manager-private.yaml
- pkg/features/list.go
Uses the `centralYAML` from the gitops config to reconcile the centrals. 
- Use a hardcoded gitops config
- Add an override patch to modify the central instance
- Verify that the patch is applied to Centraly lint binary test test/integration
> ROX-19013: Add gitops to fleetshard

- dev/env/manifests/monitoring/01-namespace.yaml
- dev/env/manifests/monitoring/02-monitoring.coreos.com_prometheusrules.yaml
- dev/env/manifests/monitoring/03-monitoring.coreos.com_servicemonitors.yaml
- dev/env/scripts/bootstrap.sh
This PR fixes the ACS CS dev env (specifically the ability to reconcile a Central) for the following use-case:
* ACS version is 4.2.0
* the dev environment is set up with `make deploy/bootstrap` && `make deploy/dev`, and
* `INSTALL_OPERATOR=false`
In the scenario above, a locally run operator is failing to reconcile Centrals, with errors like
```
namespace: \"openshift-monitoring\" from \"\": no matches for kind \"ServiceMonitor\" in version \"monitoring.coreos.com/v1\"\nensure CRDs are installed first]"
```
This PR fixes this by installing the missing CRDs.
```
INSTALL_OPERATOR=false make deploy/bootstrap
INSTALL_OPERATOR=false make deploy/dev
make -C operator install run
```
The operator should be able to reconcile the Central, and the Central pod should …
> Fix local dev env when using ACS 4.2 without OLM

- .openshift-ci/e2e-runtime/Dockerfile
- Dockerfile
- probe/Dockerfile
> Use Openshift golang-1.20 builder image

- fleetshard/pkg/central/operator/config.go
- fleetshard/pkg/central/operator/config_test.go
- fleetshard/pkg/central/operator/upgrade.go
- internal/dinosaur/pkg/gitops/config.go
This is the first PR to add the operator configurations to the gitops config.
Refactor operator config to use field.Error to match gitops configuration.
- Add more test cases for validate function
- Refactor function to use `field.Error` instead of `error`
- Use `GetChart` instead of `MustGetChart` to avoid runtime panics when provided an invalid configuration via GitOps
- Added unit tests
> Refactor operator config to use field.Error

- internal/dinosaur/pkg/services/dinosaur.go
This PR fixes route creation when restoring a central tenant through the `admin/centrals/$id/restore` endpoint.
Because of the typo the `routes_creation_id` / `RoutesCreationID` was not set to "", which led to skipping creation of DNS routes when restoring a central tenant.
~~- [ ] RDS …
> fixed typo causing skip of DNS creation in restore

- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
The dogfooding ACSCS instance regularly generates an alert for the "Pod Service Account Token Automatically Mounted" policy violation on egress-proxy deployment. This PR follows the guidance of the violated policy and updates the deployment with `automountServiceAccountToken: false`. Note that according to [this StackOverflow answer](https://stackoverflow.com/questions/44505461/how-to-configure-a-non-default-serviceaccount-on-a-deployment), updating pod spec in the deployment is fine.
No testing has been performed. Ideally, we would see alerts number drop for the integration data plane, however, we don't have it integrated in the dogfooding instance yet.
> Disable automounting for egress proxy

- .github/workflows/start-release.yaml
A workflow to be triggered manually to prepare a PR to be merged to `stage` branch as part of the release.
Inspired by [a similar workflow in the observability-artifacts repo](https://github.com/stackrox/rhacs-observability-resources/blob/master/.github/workflows/sync.yaml), but with support for specifying a commit or branch.
Once merged, I will clone the PR to the AWS config repo.
Tested quite extensively [in my fork](https://github.com/porridge/acs-fleet-manager/actions/workflows/start-release.yaml). [Example PR](https://github.com/porridge/acs-fleet-manager/pull/8).
> ROX-19692: Add a release preparation workflow.

- dev/env/manifests/fleet-manager/04-gitops-config.yaml
- fleetshard/pkg/central/operator/config.go
- fleetshard/pkg/central/operator/config_test.go
- fleetshard/pkg/central/operator/upgrade.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/gitops/config.go
- internal/dinosaur/pkg/gitops/config_test.go
- internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
- internal/dinosaur/pkg/routes/route_loader.go
Add the operator to the gitops configuration.
- Change return value from `operator.Validate` to `field.ErrorList` for extendability and compatibility with `gitops.Validate`.
- Add test scenario to validate the operator configuration with Central configs
- [] ~~Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
- Unit tests
> ROX-19735 - add operator configs to gitops

- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- internal/dinosaur/pkg/services/quota.go
- internal/dinosaur/pkg/services/quota/ams_quota_service.go
- internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
- internal/dinosaur/pkg/services/quota/quota_management_list_service.go
- internal/dinosaur/pkg/services/quota/quota_management_list_service_test.go
- internal/dinosaur/pkg/services/quotaservice_moq.go
- pkg/client/ocm/client.go
- pkg/client/ocm/client_moq.go
This PR adds a call to `/current_account` [API endpoint](https://api.openshift.com/?urls.primaryName=Accounts%20management%20service#/default/get_api_accounts_mgmt_v1_current_account).
The reason behind this hack is that when an organization is just created, it might take up to 30 minutes for AMS to populate quota data—calling `/current_account` forces AMS to populate this data earlier.
Since this is optimization and not a requirement to reserve quota, the errors are logged and not returned to the customer.
It is possible to optimize the performance by calling `/current_account` only once per user or organization. However, I would suggest to do it in a follow-up.
1. `make deploy/bootstrap`
2. Specify `CM_SERVICE_CLIENT_ID_DEFAULT` and `OCM_SERVICE_CLIENT_SECRET_DEFAULT`
3. Modify …
> Call /current_account before reserving quota

- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/services/dinosaur.go
The admin API restore endpoint is not working, because #1253 and #1277 introduced a small bug.
There are no e2e tests for the restore yet, thus those bugs were not recognized.
1. ID was not set for the resetRequest, leading to a failed Update query because the primary key was not set
2. The logged status was not copied before it is obscured because it was a pointer and not a value, leading to a wrong backup data.
This should be merged before those PRs hit `prod` environment.
To make sure it is working now I followed the manual test of restore endpoint below.
~~- [ ] …
> fixed restore endpoint

- CODEOWNERS
Context: We are transitioning from Helm chart to Addon. Until the Helm chart is deprecated and deleted, we need to keep them in sync. This will ensure all changes are at least reviewed by those responsible for the transition to the Addon. It does *not* mean changes are locked; it just means the Addon needs to be updated as well.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
https://issues.redhat.com/browse/ROX-11551
https://issues.redhat.com/browse/ROX-17339
> Adding CODEOWNERS to semi-lock the Helm chart

- fleetshard/pkg/cipher/aes256_cipher.go
- fleetshard/pkg/cipher/aes256_cipher_test.go
- fleetshard/pkg/cipher/key_generator.go
- fleetshard/pkg/cipher/kms_cipher.go
- fleetshard/pkg/cipher/kms_cipher_test.go
This PR adds a `KeyGenerator` interface and respective `AES256KeyGenerator` and `KMSDataKeyGenerator` implementations of the interface.
This implementations will later be used to generate a encryption key to provide to a managed central tenant in order to encrypt secrets stored in its DB.
CI and local unit tests are sufficient.
```
```
> ROX-16664: add KeyGenerator interface and implementations

- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/cipher/cipher.go
- fleetshard/pkg/runtime/runtime.go
Depends on #1285. This PR adds logic to the central reconciler in fleetshard-sync to generate a data encryption key secret for each tenant.
The KeyGenerator used is generated with the AES256KeyGenerator or the KMSKeyGenerator depending on fleetshard-sync configuration. (default: AES256KeyGenerator)
After central implements the required features this data encryption key will be used to encrypt notifier secrets in central tenant databases.
See #1296.
```
```
> ROX-16664: create central encryption secret

- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
Set label selector value to Dogfooding secured cluster CR. It's necessary to specify which operator should reconcile the instance
N/A
> ROX-19811: Set label selector to dogfooding secured cluster CR

- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/secret.go
Depends on #1285 and #1295 .
This PR add the `central-encryption-key` secret to the list of secrets that should be backed up in fleetmanagers database. It also adds an E2E test to test all expected secrets get backed up.
```
make binary
./fleet-manager serve --enable-central-external-certificate --dataplane-cluster-config-file ./dev/config/dataplane-cluster-configuration-infractl-osd.yaml --force-leader --central-idp-client-id ""
export CLUSTER_NAME=local_cluster                 
export MANAGED_DB_ENABLED=true
export AWS_AUTH_HELPER=aws-saml
export CREATE_AUTHPROVIDER=true
./dev/env/scripts/exec_fleetshard_sync.sh
kubectl get secrets -n rhacs-ck6p6969rus49ma6iko0 central-encryption-key -o yaml | yq .data.encryptionKey | …
```
> ROX-16664: backup central encryption key

- dev/env/scripts/lib.sh
The code patches the specified service account, not the default service account.
> Fix log message about injecting image pull secrets into service account

- fleetshard/main.go
- pkg/logger/kubeapi_logger.go
`controller-runtime` client invokes  an instance of structured logr.Logger if there is something worth to log. If `logr.logger` instance is not provided then it fails with `[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.` error. This PR adds a `logr.Logger` instance to `controller-runtime` client.
Fleetshard-sync doesn't use structured logging and `logr.Logger` is a structured logger. So a small wrapper is introduced to use glog as log sink in `logr.Logger` instance
~~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication …
> ROX-20053: Set controller-runtime logger

- dev/env/scripts/install_operator.sh
While debugging an (unrelated, it seems) issue about image pull secrets not being properly propagated within the e2e test suite, I stumbled upon this issue here.
The PR seems weird, I agree, but what I was able to observe (reproducible) is the following: when the patching of the Service Account happens immediately after creation of the Service Account, the patching won't be effective. I believe this is due to OLM (creating this Service Account, I believe) updating this Service Account shortly after creation and hence overwriting what the patching tried to achieve. I was still able to reproduce the issue of undoing the patching with a 5s delay, but not with a 10s delay. :-/ I did not dig deeper into OLM to figure out exactly what is going on and what is the logic here, since this did not …
> dev scripts: Add delay before patching ServiceAccounts to include Image Pull Secrets

- e2e/e2e_canary_upgrade_test.go
In case the environment in which to execute e2e tests is missing proper auth tokens, executing the e2e tests can fail as follows:
```
Assertion or Panic detected during tree construction
var _ = Describe("Fleetshard-sync Targeted Upgrade", func() {
/Users/mclasmeier/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_canary_upgrade_test.go:38
Ginkgo detected a panic while constructing the spec tree.
You may be trying to make an assertion in the body of a container node
(i.e. Describe, Context, or When).
Please ensure all assertions are inside leaf nodes such as BeforeEach,
It, etc.
Here's the content of the panic that was caught:
Your Test Panicked
Expect(err).ToNot(HaveOccurred())
/Users/mclasmeier/go/src/github.com/stackrox/acs-fleet-manager/e2e/e2e_canary_upgrade_test.go:52
When you, …
```
> Move auth and client init into BeforeEach to improve Ginkgo errors

- Makefile
Ginkgo is currently invoked with the `--slow-spec-threshold` parameter. This parameter is deprecated nowadays and can be replaced with `--poll-progress-after`. See https://issues.redhat.com/browse/ROX-13622.
* Setup e2e test env
* execute `.openshift-ci/tests/e2e.sh`
> ROX-13622: dev env: Update Ginkgo CLI invocation to not use deprecated option

- e2e/e2e_test.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/handlers/admin_dinosaur_test.go
This PR fixes a bug with strategic patch for the endpoint. `PATCH /api/rhacs/v1/admin/central/$tenant_id`. ForceReconcile in the database would never be set because it is deleted from the map used to merge the original requests values with the patch values.
Also adds an E2E test to make sure force_reconcile can always be set via API because it is required for a lot of SOPs to work properly.
only CI/local unit test
```
```
> fix ForceReconcile, add unit and e2e tests

- dev/env/scripts/lib.sh
The deployment tooling uses a mechanism to inject all `RHACS_`-prefixed variables into the pod specs, but this currently also includes those variables ending with `_DEFAULT`, which are internal variables used for the defaulting logic of the deployment tooling. This PR filters them out before injecting into the pod environments.
- ~~[ ] Add secret to …
> Do not inject feature flag defaults into Kubernetes Deployments

- dp-terraform/helm/rhacs-terraform/values.yaml
Try setting an explicit tag for the squid proxy image and see if all existing deployments update themselves.
We currently have two different images on the `int` [cluster](https://acs-cii18grublkv81uil8gg.acs.rhcloud.com/main/vulnerabilities/workload-cves?entityTab=Image&sortOption[field]=Image&sortOption[direction]=desc&s[IMAGE][0]=registry.redhat.io/openshift4/ose-egress-http-proxy:v4.11.0&s[CLUSTER][0]=acs-int-us-01) so after this PR is merged we expect only one.
Irrelevant for this PR.
None: integration cluster is our litmus test.
> Update squid proxy image

- pkg/errors/errors.go
Broaden amount of error codes that return an extended error message + give customer alternative if going to `/openshift` URL does not work
```
```
> Improve AMS error experience

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Because the operator is now installed with a Helm chart, ACS CS will not pick up this change from the next ACS releases, so I'll do it manually (for now). The reasoning for the change is documented [here](https://docs.google.com/document/d/1F99glzhX2i2Ppe5Qq3M-Po_jSSUiVssqFyWRhVm1X3o/edit?usp=sharing)
I'm also switching to the downstream `kube-rbac-proxy` image, because we're currently using downstream ACS images.
I verified that the image supports the new `--http2-disable` flag by running:
`docker run --rm  registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.13 --http2-disable`
```
```
> ROX-20542: disable http/2 in operator kube-rbac-proxy to mitigate CVE-2023-44487

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Remove CPU limits from observability components to prevent unnecessary throttling.
Note that the Grafana pod has been throttling despite idling since Grafana was updated to `10.2.0`. This behavior is not understood, but throttling due to CPU limits is undesired anyway.
> chore(observability): remove cpu limits

- dp-terraform/helm/rhacs-terraform/values.yaml
Fixes the issue with the wrong service accounts range
```
pods "rhacs-external-secrets-webhook-867d7f9b6f-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .containers[0].runAsUser: Invalid value: 1001130001: must be in the ranges: [1001050000, 1001059999], provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider
```
```
```
> ROX-19905: Fix external-secrets securitycontext

- fleetshard/pkg/k8s/route_test.go
New tests for the route service
```
```
> test: add tests for route service

- e2e/e2e_suite_test.go
- fleetshard/config/config.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/k8s/route_test.go
- fleetshard/pkg/runtime/runtime.go
In order to protect against (D)DOS attacks, the OpenShift routes to Central managed by FleetShard sync are being annotated in order to activate traffic throttling features.
The default values were derived from the haproxy metrics available in the current ACS CS instances.
- The most busy central shows a total HTTP response count of 9 averaged over a 5 minute period.
Assuming all the averaged requests were a burst of concurrent requests, these could have been about 3000 requests.
Adding a safety 10 factor, and using powers of two as throttling value, the default would be 32768 concurrent requests.
- The most busy central reported up to 43 concurrent connections on a 5 minute period. The limit derived from here is 512 concurrent connections, allowing at most the half as being established at …
> ROX-19562: Add annotations to rate limit managed-central routes traffic

- internal/dinosaur/pkg/gitops/config.go
- internal/dinosaur/pkg/gitops/service.go
- internal/dinosaur/pkg/gitops/service_test.go
- internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/presenters/managedcentral_test.go
- internal/dinosaur/providers.go
Changes:
- Remove the gitops service. Replace with a function without receiver. 
- Add a function to the managedCentralPresenter to be able to render multiple centrals concurrently. (Moved that from the handler)
- Added a cache to store the rendered central YAML, keyed by central ID.
> Cache rendered centrals v2

- dp-terraform/helm/rhacs-terraform/templates/scc.yaml
~For some reason~ Because the stage/prod clusters are running an older version of openshift (4.11), the anyuid SCC does not allow ephemeral volumes by default. Adding a custom SCC so that we can use ephemeral volumes.
> ROX-20654 Add SCC to allow using ephemeral volumes

- deploy/helm/probe/deploy.sh
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/ocm/install_addon.sh
Add extra flags to `make tag` to suppress unexpected output.
```
url: (3) URL using bad/illegal format or missing URL
Image acs-fleet-manager tag make: Entering directory '/home/runner/work/acs-fleet-manager/acs-fleet-manager'
0a4399f
make: Leaving directory '/home/runner/work/acs-fleet-manager/acs-fleet-manager' does not exist. Received the following response from quay API:
```
https://github.com/stackrox/acs-fleet-manager/actions/runs/6800037700/job/18487696298
```
```
> Fix deploy to integration

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
We have high memory usage for operators manager container in prod. With this PR I active the heap profiling feature of the operator so that operators writes heap dumps once it's memory usage gets to 50% of the configured limits.
- ~~[ ] RDS changes were e2e tested …
> ROX-2063: change operator deployment to enable heap profiling

- .secrets.baseline
- dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/06-statefulset.yaml
- dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-logging.yaml
- dp-terraform/helm/rhacs-terraform/charts/logging/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
For **integration**, **stage-dp-02**, **stage-eu-02**, **prod-eu-01**, the "normal" worker pool will be labeled with `node-role.kubernetes.io/acscs-infra: ""`. In that case, nothing changes.
For **prod-dp-01**, there will be an additional node pool labeled with `node-role.kubernetes.io/acscs-infra: ""` and with a taint `node-role.kubernetes.io/acscs-infra` of effect `NoSchedule`. This will cause all infra-related workloads to be scheduled on those nodes rather than on the "regular" worker pool.
> ROX-16643 Move infra-workloads to dedicated node pools

- cmd/fleet-manager/main_test.go
- dev/config/dataplane-cluster-configuration-crc.yaml
- dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
- dev/config/dataplane-cluster-configuration-kind.yaml
- dev/config/dataplane-cluster-configuration-minikube.yaml
- dev/config/dataplane-cluster-configuration-rancherdesktop.yaml
- dev/env/manifests/fleet-manager/03-fleet-manager-service.yaml
- dev/env/manifests/shared/03-configmap-config.yaml
- internal/dinosaur/pkg/services/clusters.go
- internal/dinosaur/pkg/services/dinosaur.go
- pkg/providers/core.go
- pkg/server/profiler/profiler_server.go
- pkg/server/profiler/profiler_server_test.go
- scripts/create-central.sh
- scripts/fmcurl
- templates/service-template.yml
- Add pprof server to fleet-manager on port 6060
- Add name parameter to `create-central.sh`
- Allow more instance for eval instances in development
- Increase data-plane capacity in development
- /
> Add pprof server to fleet-manager and unlimited evals in testing&develop

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
In the context of cloud services, we want to have Telemetry always configured, except for the internal instances, such as probes.
Therefore, the proposed change sets the TelemetryEnabled property to true (which essentially enables telemetry configuration), and disables telemetry collection by setting "DISABLED" value for the key.
CI, unit tests.
> ROX-20795: probe telemetry configuration

- dp-terraform/helm/rhacs-terraform/values.yaml
- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
Previously in https://github.com/stackrox/acs-fleet-manager/pull/1411 we switched egress-proxy to a specific image to forcefully update all egress-proxy images on all data plane clusters. This has its own disadvantages, for instance, one needs to bump the image regularly.
This PR attempts a different strategy: floating image tag with "always" pull policy. While this does not guarantee that all deployments have the same image at a given point of time, we expect it to eventually update all egress-proxy images on, say, cluster upgrade events.
None, CI run and testing on stage.
> Switch egress-proxy to a floating tag

- pkg/server/profiler/profiler_server.go
- pkg/server/profiler/profiler_server_test.go
Fix flaky test, removing retries instead use timeout for dialing the profiling endpoint.
> Fix falky profiling test

- cmd/acsfleetctl/main.go
- fleetshard/pkg/central/operator/config.go
- internal/dinosaur/pkg/gitops/cmd/validate.go
[ROX-19328](https://issues.redhat.com//browse/ROX-19328) - Add gitops validate CLI command
- Use acsfleetctl to validate config files in gitops repo
> ROX-19328 - Add gitops validate CLI command

- dp-terraform/helm/Dockerfile
Fleetshard operator lacks external secrets dependency in the image. The following changes have been added:
1. Add the external secrets dependency secrets operator can’t work without the external secrets dependency
2. Delete the default `securityContext.runAsUser` from the subchart. External secrets operator sets user id as 1000 by default which is prohibited by openshift (without extra scc config). If you delete the key then openshift assigns a user id from a range, so from security perspective it should be better. The null value I set for `securityContext.runAsUser` in root `values.yaml` works in helm but not in the operator. Most likely because the older version of helm is used in operator-sdk. I submitted a bug report to operator sdk and made a workaround to remove the default key(s) …
> Add helm dependencies to Dockerfile

- Makefile
- dp-terraform/helm/Dockerfile
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
- dp-terraform/helm/rhacs-terraform/values.yaml
- dp-terraform/ocm/install_addon.sh
This change sets the fleetshard-sync image tag for the operator the same as the operator tag.
Additionally, I've made a cleanup of the `install_addon.sh` script and ported the recent changes from `terraform_cluster.sh`.
```
```
> Set the same image fleetshard sync tag as the operator

- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-logging.yaml
Currently, tolerations are not set on openshift-logging collector pods. Because of that, logs from apps running on `acscs-infra` nodes are not collected.
Based on [API documentation](https://docs.openshift.com/container-platform/4.12/logging/api_reference/logging-5-6-reference.html), `tolerations` can be set under:
`.spec.collection.logs.fluentd.tolerations` (DEPRECATED)
or 
`.spec.collection.tolerations`
Since the `logs` property is deprecated, this PR removes it. With that, we should solve two issues:
1. tolerations will be set to correct property in CR
2. deprecated property will not be used anymore
- ~[ ] Add the ticket number to the PR title if available, …
> Fix tolerations for logging collectors to work on ACSCS infra nodes

- pkg/client/redhatsso/dynamicclients/client.go
As requested by the CIAM team, change the scope for requesting RHSSO dynamic clients to "api.iam.clients.acs" from "api.iam.clients".
None, a trivial change that will fail miserably if something does not work.
CI run.
> Change the scope for requesting dynamic clients.

- dp-terraform/helm/rhacs-terraform/values.yaml
With `nodeSelector` defined, collectors will be deployed only on nodes specified by that option. In the case of logging collectors, it is a DaemonSet, and we should have a collector pod running on every cluster node.
This PR is a follow-up on https://github.com/stackrox/acs-fleet-manager/pull/1499 
This issue was discovered on the integration cluster after checking the status of the deployment of the previous PR.
- ~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
- ~[ ] …
> Remove nodeSelector for logging operator collector

- dp-terraform/helm/rhacs-terraform/values.yaml
After validating #1501 on the integration cluster, I found that `infra` nodes do not contain a logging operator collector.
I think this is a problem with the logging operator running on the OSD cluster because OSD has `infra` nodes, and the cluster logging operator (CLO) does not take that into consideration.
This PR should fix that problem.
- ~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
- ~[ ] Add secret to …
> Enable cluster logging operator collectors on infra nodes

- internal/dinosaur/pkg/migrations/20231212140000_add_expiration_lease_type.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
- internal/dinosaur/providers.go
Without this migration, new `expiration_date_mgr` introduced in https://github.com/stackrox/acs-fleet-manager/pull/1248 won't work on already deployed `fleet-manager`:
```
I1211 18:30:38.096596       1 leader_election_mgr.go:128] failed to acquire leader lease: expected to find a lease entry, found none for :expiration_date_worker
```
1. TBD local test
> Add expiration date worker lease via migrations

- dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
- dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
integration control plane moved to a new cluster. We need to relax the regex to see the new data source.
No tests :-(
> chore(dashboards): cover new cluster names in data sources regex

- internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
- internal/dinosaur/pkg/api/admin/private/api_default.go
- internal/dinosaur/pkg/api/admin/private/model_central.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/presenters/admin_dinosaur.go
- internal/dinosaur/pkg/routes/route_loader.go
- openapi/fleet-manager-private-admin.yaml
```console
$ curl -H "Authorization: Bearer $STATIC_TOKEN_ADMIN" \
"http://localhost:8000/api/rhacs/v1/admin/centrals/cl75fu8bs0bd6k334h0g/expired-at" \
-d "timestamp=2024-01-02T13:45:56Z" \
-d "reason=test" -X PATCH
```
Logs:
```
W1127 09:29:41.074361      13 admin_dinosaur.go:258] Setting expired_at to "2024-01-02T13:45:56Z" for central "cl75fu8bs0bd6k334h0g": test
I1127 09:29:41.076758      13 framework.go:51] user='rhacs-ms-test@redhat.com' action='admin-expired-at' src_ip='127.0.0.1:60156' session='20873d12-aae8-4d3b-9c14-44a5a253c367' tx_id='631' opid='cli631dfh90d6k12pjdg' operation ended successfully
```
`expired_at` field in GET centrals:
```console
$ curl -H "Authorization: Bearer $STATIC_TOKEN_ADMIN" "http://localhost:8000/api/rhacs/v1/admin/centrals"
```
```json
{
"kind": …
```
> ROX-21118: change `expired_at` via API

- internal/dinosaur/pkg/gitops/config.go
- internal/dinosaur/pkg/gitops/config_test.go
- internal/dinosaur/pkg/gitops/provider_test.go
Install addon from Fleet Manager: Part 3.
Add the Data Plane clusters configuration to gitops config in order to update the addons via fleet manager 
```
```
> ROX-21070: Declare Data Plane Cluster configuration in gitops config

- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Reduce the resync period from 1 hour to 10 minutes. The resync period defines the interval in which the observability operator reconciles the observability config with https://github.com/stackrox/rhacs-observability-resources. The reason for the reduction is that a 1 hour can be a bit too long when waiting for the reconciliation. 10 minutes should be more convenient, while still being sufficiently far away from any rate limits.
> chore: reduce resync period

- pkg/serviceregistration/leader.go
The logic used to retry in the leaderelection used apimachinery exponential backoff. But this actually does not retry infinitely. Implemented a simple exponential backoff to retry forever.
> ROX-20479: fix leader retry

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Add a PVC to the alertmanager deployment. This should prevent silences getting lost after pod restarts. Also did a small refactoring of the Prometheus PVC by introducing values for it.
> ROX-21596: add PVC for alertmanager

- .secrets.baseline
- Makefile
- config/dataplane-cluster-configuration.yaml
- dev/config/dataplane-cluster-configuration-minikube.yaml
- dev/config/dataplane-cluster-configuration-rancherdesktop.yaml
- dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml
- dev/env/scripts/lib.sh
- docs/development/running-fleet-manager.md
- docs/legacy/data-plane-osd-cluster-options.md
- docs/legacy/feature-flags.md
- internal/dinosaur/pkg/clusters/standalone_provider.go
- internal/dinosaur/pkg/config/dataplane_cluster_config.go
- internal/dinosaur/test/helper.go
- templates/secrets-template.yml
- templates/service-template.yml
Since we're not going to support cluster mgmt in Fleet Manager we can remove kubeconfig parameter that is required for managing standalone clusters.
The presence of this parameter can be annoying, because we need to modify kubeconfig every time we need to add a new cluster. 
```
```
> Remove kubeconfig from fleet-manager

- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
- internal/dinosaur/pkg/services/data_plane_cluster.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- internal/dinosaur/pkg/workers/clusters_mgr_test.go
- internal/dinosaur/providers.go
- pkg/api/cluster_types.go
- pkg/client/ocm/client.go
- pkg/client/ocm/client_moq.go
Install addon from Fleet Manager: Part 4.
This change adds a feature to automatically update addons from Fleet Manager.
```
```
> ROX-21070: Implement the addon mgmt in fleet manager

- .secrets.baseline
- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/runtime/runtime.go
- internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
- internal/dinosaur/pkg/api/admin/private/api_default.go
- internal/dinosaur/pkg/api/admin/private/model_central_rotate_secrets_request.go
- internal/dinosaur/pkg/handlers/admin_dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- openapi/fleet-manager-private-admin.yaml
- pkg/client/fleetmanager/api_moq.go
- pkg/client/fleetmanager/client.go
When secrets are rotated on data plane cluster side (e.g. leaf certs of central) they are not automatically updated in the backup of fleet-manager. This PR adds an admin API endpoint to trigger that rotation. Once we implement better working rotation mechanisms we should also address automating the backup rotation.
- Local fleet-manager & fleetshard-sync setup with `infractl` cluster
- Create central with `create-central.sh`
- Wait for full creation flow
- Call the new API
```
rhoas login --auth-url=https://auth.redhat.com/auth/realms/EmployeeIDP 
export OCM_TOKEN=$(rhoas authtoken)
./scripts/fmcurl "rhacs/v1/admin/centrals/$central_id/rotate-secrets" -XPOST -d '{"reset_secret_backup": true}'
make db/psql
Verify that secrets are deleted, and backup get restored after some time when FS …
```
> ROX-21679: add rotate secret backup feature to admin API

- templates/service-template.yml
Fixing the fleet-manager (active) service label to match the other fleet-manager-envoy service labels.
> ROX-20479: fix fleet-manager service label

- templates/service-template.yml
services cannot share the same `serving-cert-secret-name` otherwise this results in a conflict where tls secrets cannot be reconciled. Creating an additional serving cert for the active fleet-manager
> ROX-20479: fix fleet-manager-active cert label

- .secrets.baseline
- templates/service-template.yml
Mounting a tls secret for the "active" fleet-manager service, otherwise routing to this service fails
> ROX-20479: fix fleet-manager-active cert

- templates/service-template.yml
Reverting adding a 2nd tls cert to envoy as it is not supported
> ROX-20479: revert fleet-manager-active cert

- templates/service-template.yml
Adding the cert for the fleet-manager-active so that the fleet-manager-active route can establish TLS with the envoy sidecar
> ROX-20479: fleet-manager-active certs

- templates/service-template.yml
Adding a second filter chain to the envoy gateway for the active fleet manager
> ROX-20479: add duplicate filter chain for active fleet-manager

- .github/workflows/ci.yaml
Disable tests to unblock other PRs. Proper fix will follow
```
```
> Temporarily disable integration tests on CI

- templates/service-template.yml
Adding all possible fleet-manager-active hostnames that the router might use to envoy config
> ROX-20479: adding all possible fleet-manager-active hostnames to envoy config

- .github/pull_request_template.md
- .github/workflows/ci.yaml
- Makefile
Remove ocm client credentials and replace them by the offline token.
Reason: even though ocm **server** is mocked on integration(-test) environment it still uses real OAuth token endpoint to authenticate in RHSSO if client credentials are set. Using an offline token allows to bypass the call to the real service.
```
```
> Fix integration tests and enable them back on CI

- templates/service-template.yml
Openshift ingress does not forward SNI headers, so envoy is unable to distinguish requests coming from fleet-manager-envoy vs fleet-manager-active services, and unable to resolve the correct certificate. 
The solution is to add a separate listener on a different port, to server the fleet-manager-active service and use the correct certificate.
> ROX-21779 Add envoy active listener

- .github/workflows/ci.yaml
- .openshift-ci/tests/e2e-test.sh
- .secrets.baseline
- dev/env/scripts/lib.sh
- internal/dinosaur/pkg/environments/development.go
- internal/dinosaur/pkg/environments/integration.go
- pkg/db/dinosaur.go
- pkg/server/server_config.go
- pkg/serviceregistration/leader.go
- pkg/serviceregistration/service.go
- templates/service-template.yml
- test/helper.go
By disabling the leader election in integration(-test) environment
It seems that it happens with delay, after the test is already run. This result in starting workers **after** the test teardown which includes database migrations rollback. That result in longer test run time and errors like:
```
E0117 16:41:38.123802   80357 reconciler.go:56] failed to list accepted centrals: RHACS-MGMT-9: failed to list by status
 caused by: ERROR: column central_requests.internal does not exist (SQLSTATE 42703)
```
```
```
> Fixed race condition in integration tests

- .github/workflows/ci.yaml
- .openshift-ci/e2e-runtime/Dockerfile
- .openshift-ci/e2e-runtime/e2e_dockerized.sh
- Dockerfile
- Dockerfile.tools
- Makefile
- dev/env/scripts/docker.sh
- probe/Dockerfile
This PR adds native support for arm64. arm64 images are now pushed from GHA. 
The main problem is that "registry.ci.openshift.org/openshift/release:golang-1.20" doesn't have arm64 image variant.
I also did a few improvements to the buildkit build to support multi-platform builds.
More details: https://docs.docker.com/build/guide/multi-platform/
```
```
> Native arm64 docker build with buildkit

- templates/service-template.yml
Fix error where port name is too long
> ROX-21779 Fix api-envoy-active port name too long error

- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/api/dbapi/central_request_types.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
- internal/dinosaur/pkg/handlers/validation.go
- internal/dinosaur/pkg/migrations/20240122180000_add_alternate_user_id.go
- internal/dinosaur/pkg/migrations/20240122180000_add_alternative_user_id.go
- internal/dinosaur/pkg/migrations/migrations.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- openapi/fleet-manager-private.yaml
- pkg/auth/acs_claims.go
- pkg/auth/context_config.go
This PR is based on next assumptions:
* There's ongoing process of switching from old `sub` claim format to new one
* Console dot is returning `sub` in new format under `sub` claim name; it will return `sub` in old format under `deprecated_sub` claim name
*  When using dynamic client, `sso.r.c` returns `sub` in old format; at some point switch will be made to return `sub` in new format
This PR adds auth provider groups for both old and new format so that the owner of an instance can login whatever format is returned from `sso.r.c`.
**Note**: this PR only solves the problem for new instances. Already existing instances will continue to work until a switch in dynamic clients happens. This case should be handled in a separate PR.
```
make db/teardown …
```
> Allow for both "sub" claim formats to be used in login

- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/services/data_plane_dinosaur.go
The check intended to prevent fleet-manager from overwriting secrets if they are already stored broke the update logic in case new secrets were added.
The check was still useful because it protected FM from overwriting secrets with an empty map if no secrets are reported by FS, so I only changed the logic to validate the incoming request instead of the database state. 
~~- [ ] Discussed security and business related topics privately. Will move any security and business related topics that arise to private communication …
> fix: update for secret backup for tenants

- dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
New routes have been added to target only the "active" fleet-manager instance. 
- romndkjdq62p7sr.api.integration.openshift.com for integration
- gbrh0yv9ebhqegl.api.stage.openshift.com for stage
- ixi6srehbv5uxsa.api.openshift.com for prod
This will change the stage and prod FM_ENDPOINT urls to point to the active fleet-manager instance
Note that these endpoints are returning errors right now, that's because the envoy gateway config that listens on port 9002 has not been deployed to stage and production yet. When we deploy FM, the endpoints should be working 🤞
> ROX-21779 Set new FM_ENDPOINT for stage and production

- go.mod
- go.sum
- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
- pkg/client/ocm/client.go
- pkg/client/ocm/impl/client_impl.go
- pkg/client/ocm/mocks/client_moq.go
1. Replace `addons_mgmt` to `clusters_mgmt` in OCM client facade.
1. Use forked version that contains PackageImage until it becomes available upstream.
```
make ocm/setup
```
> Fix missing PackageImage field in clusters_mgmt

- .secrets.baseline
- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/k8s/route_test.go
- fleetshard/pkg/k8s/secret.go
After restore of central-tls secret the owner reference is not set to the central CR again. This blocks the operator from automatically rotating leaf certificates for central, since it won't touch secrets not owned by it.
With this PR fleetshard-sync, will set the owner reference of the secret to the CR it creates, which should fix the issue.
CI and added e2e tests should be sufficient
```
make ocm/setup
```
> ROX-21946: FS set central-tls OwnerReference if not already set

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
Fixing of the fleetshard cache bug. 
How to reproduce: 
1. Reconcile central v1
2. Reconcile centra v2
3. Deployment is unhealthy (restarting)
4. Reconcile central v1
5. Reconcile central v2 (ignored/skipped)
The reason that the reconcile loop at step 5 is ignored is that the hash is not stored at step 4, even if the central CR was updated. At step 5, the reconciler will be skipped because the hash (v2) matches the last stored hash (step 2). 
The effect is that v1 is deployed, but the reconciler thinks it reconciled v2.
The fix is to unset the hash if the reconciler exited early. 
As an added precaution, trigger the reconcile loop if central was reconciled more than 15 minutes ago.
> ROX-20872: fix fleetshard reconciler race condition

- fleetshard/pkg/central/reconciler/reconciler.go
When central is ready, we should keep the hash so that next reconciles will be skipped
> Keep central hash when central is ready

- internal/dinosaur/pkg/services/quota/ams_quota_service.go
`ID()` is a function returning `string`.
Before:
```
I0121 05:25:42.860591       1 ams_quota_service.go:70] Quota no longer entitled for organisation %!q(func() string=0x2ecf500)
```
> fix: log message argument

- .secrets.baseline
- e2e/e2e_central_traits_test.go
- e2e/e2e_test.go
- pkg/client/fleetmanager/client.go
- pkg/client/fleetmanager/mocks/client_moq.go
> ROX-21867: e2e for traits

- go.mod
- go.sum
Bump ocm-sdk-go to 0.1.401 and switch it back to upstream since it contains all the changes needed for the addon service.
CI
> ROX-22237: Bump ocm-sdk-go and switch it back to upstream

- build_push_app_interface.sh
Add probe image build on app-interface.
```
make ocm/setup
```
> ROX-16615: Add probe image build on app-interface

- fleetshard/pkg/central/reconciler/proxy.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
With the introduction of ScannerV4 to ACSCS, this required also changing up the proxy configuration (specifically the NO_PROXY one) for deployed components.
```
make ocm/setup
```
> fix(scannerv4): adjust proxy settings

- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaur_test.go
When restoring an expired instance, reset the expiration timestamp to `null`, so that the grace period restarts, which allows for 2 more weeks for postponing or giving quota.
```
make ocm/setup
```
> ROX-22358: reset grace period on restore

- internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
- pkg/metrics/metrics.go
A new Fleet-manager Prometheus metric, showing the total number of expired centrals.
The idea is to create an alert on a spike of such events.
Initial run:
```console
$ curl -s http://localhost:8080/metrics | grep expired
acs_fleet_manager_expired_centrals_count 0
```
1. Created locally an eval central, managed by quota-management-list;
2. Patched quota-management-list config to allow 0 instances;
3. Restarted fleet-manager to trigger expiration worker;
4. Checked the fleet-manager metrics:
```console
curl -s http://localhost:8080/metrics | grep expired
acs_fleet_manager_expired_centrals_count 1
```
> ROX-22557: Count `expired-at` non-null changes

- internal/dinosaur/pkg/services/telemetry.go
This change fixes panic in case telemetry collection is disabled.
Existing tests are good enough.
> fix: check if telemetry is enabled

- .github/workflows/ci.yaml
- .secrets.baseline
Context is in https://issues.redhat.com/browse/ROX-22887
If we don't pin the version to 1.20 in the build step it will break when the runner tries to use 1.21, because our go.mod file is missing the new toolchain directive (see https://tip.golang.org/doc/toolchain).
When we upgrade to using go 1.21 we'll just need to run `go mod tidy` once, commit the changes, and update our CI runners to use go 1.21.
> ROX-22887: Use go 1.20 to build images in CI

- dp-terraform/helm/Dockerfile
It looks like v1.34.0 is broken. The reconciliation stopped working after merging #1687
Related issues: 
- https://github.com/operator-framework/operator-sdk/issues/6690
- https://github.com/operator-framework/operator-sdk/issues/6692
No testing performed
> Rollback helm-operator to v1.33.0

- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- Adding template & default values for secured cluster ScannerV4
- Enabling local scanning on SecuredClusters
```
make ocm/setup
```
> ROX-22926: Enable dogfood local scanner

- dp-terraform/helm/Dockerfile
- dp-terraform/helm/rhacs-terraform/values.yaml
If the helm release fails, this puts the webhook in a broken state:
1. Cert-controller updates the CA cert every 5 minutes:
```
{"level":"info","ts":1710156288.9732099,"logger":"controllers.webhook-certs-updater","msg":"injecting ca certificate and service names","cacrt":"...
```
2. The Fleetshard operator rolls back the secret due to a failed release and thus clears the secret data. The secret is empty in the chart: https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/webhook-secret.yaml
In other words, webhook can't start, because the operator reconciles it again and again.
This becomes an endless loop, spawning a service account every time a reconciliation is attempted. 
Test on integration 😅
> Disable ESO webhook

- tools/noop.go
On local dev environments, the git hook would fail because there is a go.mod without any go files (there was a file, but with a build tag which gets ignored). Added a noop go file
```
make ocm/setup
```
> ROX-22593: git hook fix

- internal/dinosaur/pkg/services/dinosaur.go
This PR does its best to keep track of central request state change. 
Conversion to string is done so that secrets, routes and auth config are not logged.
`DeprovisionExpiredDinosaurs` is not covered here since query does not return affected rows.
1. TBD
> ROX-22361: Log ACSCS instance state change

- deploy/helm/probe/templates/01-operator-04-deployment.yaml
- probe/cmd/probe/main.go
- probe/config/config.go
- probe/config/config_test.go
- probe/internal/cli/cli_test.go
- probe/pkg/metrics/metrics.go
- probe/pkg/metrics/metrics_test.go
- probe/pkg/metrics/server.go
- probe/pkg/metrics/server_test.go
- probe/pkg/probe/probe.go
- probe/pkg/probe/probe_moq.go
- probe/pkg/probe/probe_test.go
- probe/pkg/runtime/runtime.go
- probe/pkg/runtime/runtime_test.go
Make the probe service create multiple central specs (different cloud providers/regions) in a single probe run.
The change is a prerequisite for migrating the probe service from the data plane to the control plane. 
The change is backward compatible w.r.t. the helm chart => no deployment changes needed.
```
export FLEET_MANAGER_ENDPOINT=<stage url>
export AUTH_TYPE=OCM
export OCM_USERNAME=<ocm username>
export OCM_TOKEN=token
export CENTRAL_SPECS=`[{ "cloudProvider": "aws", "region": "us-east-1" }, { "cloudProvider": "aws", "region": "eu-west-1" }]`
./probe/bin/probe start
```
```
export HELM_DRY_RUN=true
export HELM_DEBUG=true
./deploy/helm/probe/deploy.sh dev acs-dev-dp-01
```
> ROX-16615: Make the probe service create multiple centrals (per region / cloud provider)

- Makefile
- probe/README.md
- probe/config/config.go
- probe/config/config_test.go
- templates/probe-template.yml
This change introduces the probe template as an alternative installation method to the helm chart. Templates are used to deploy services on app-interface.
- Template yaml
- dev makefile targets
- Instructions to run on dev clusters
```
make deploy/probe
```
> ROX-16615: Probe template

- internal/dinosaur/pkg/services/data_plane_dinosaur.go
- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaurservice_moq.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
- internal/dinosaur/pkg/workers/dinosaurmgrs/timeout.go
Rename dinosaurService `Update` to `UpdateIgnoreNils` to better highlight that it doesn't support nil values update. 
CI
> ROX-22428: Rename dinosaurService#Update

- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/k8s/secret.go
This PR updates the name and format of the notifier encryption key secret. See the [ROX-21682](https://issues.redhat.com/browse/ROX-21682) for more details.
Note that the old secret is not preserved, because backwards compatibility is not needed. For existing tenants, the old secret will continue to exist in the namespace (but not in the fleet-manager backup), but this shouldn't cause any issues.
```bash
❯ kubectl -n rhacs-cnu4bn0ed75c738999k0 get secret central-encryption-key-chain -o yaml
apiVersion: v1
data:
key-chain.yaml: a2V5TWFwOgogIDA6IFB3WTVVVXdWYzlsN0tLc1VlVzhoM2pWRERyakdaTWJUdXUyWVVwVUdvU1k9CmFjdGl2ZUtleUluZGV4OiAwCg==
kind: Secret
metadata:
annotations:
platform.stackrox.io/managed-services: "true"
creationTimestamp: …
```
> ROX-21682: Add support for central-encryption-key-chain

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
`populateEncryptionKeySecret` was base64-encoding the `key-chain.yaml` file twice. 
`k8s` is already base64-encoding Data fields of secrets, so by doing a base64 encode I was effectively encoding the contents of the file twice. Then Central cannot parse the secret. This PR fixes this.
```bash
❯ kubectl -n rhacs-co1bmsl75klc73alldc0 get secret central-encryption-key-chain -o yaml
apiVersion: v1
data:
key-chain.yaml: a2V5TWFwOgogIDA6IGVPcUFRSXNrWVBwQndoWS9hN3FxRytyRDdXQ2lYV1pJZmZ6VFJJcWRITjg9CmFjdGl2ZUtleUluZGV4OiAwCg==
kind: Secret
metadata:
annotations:
platform.stackrox.io/managed-services: "true"
creationTimestamp: "2024-03-26T12:13:04Z"
labels:
app.kubernetes.io/managed-by: rhacs-fleetshard
name: central-encryption-key-chain
namespace: …
```
> ROX-21682: remove double base64 encoding

- templates/service-template.yml
This PR adds requests and limits to the initContainer of fleet-manager.
The initContainer executes `fleet-manager migrate`, which is why I decided to re-use the same requests and limits that we use for the `fleet-manager` container itself (which executes `fleet-manager serve`).
It's not possible to see on Prometheus the actual memory & CPU usage of the init container in production, probably because the process is too short lived and it's not getting scraped. To get an estimation of its usage, I ran this locally:
```bash
❯ /usr/bin/time -l -h -p ./fleet-manager migrate
I0408 15:37:43.709514   26957 cmd.go:20] Migration starting
I0408 15:37:43.873693   26957 202212150000_add_organisation_name.go:67] added column "OrganisationName" in schema migration "202212150000"
I0408 15:37:43.879213 …
```
> ROX-23370: add requests and limits to FM initContainer

- internal/dinosaur/pkg/services/quota/ams_quota_service.go
- internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
RHACSTrial quota_cost may have zero allowance, but we still allow provisioning due to zero-cost. This PR makes the `HasQuotaAllowance` method consistent with the `ReserveQuota` logic.
The tests are also corrected for related resources not having `marketplace-aws`, but `marketplace` billing model _type_.
Not manual. Unit tests.
> fix: consider zero-cost resources allowed

- .secrets.baseline
- config/jwks-file-static.json
- config/static-token-admin-payload.json
- docs/development/test-locally-static-token.md
- templates/service-template.yml
Token are rotated in bitwarden and Vault
```
make ocm/setup
```
> ROX-23607: Rotate fleet manager static tokens

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
For [ROX-23557](https://issues.redhat.com/browse/ROX-23557) we need to make sure that all namespaces for which NetworkPolicy denial logging is desired carry a certain annotation. This PR introduces this annotation for tenant namespaces.
I haven't conducted manual tests. CI e2e tests + unit tests should be good.
>  ROX-23557: Add annotation for ACL Logging to tenant namespaces

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
This PR adds settings for the cloudwatch exporter to also export our custom violation denials metrics. This includes the metric for SELinux AVC denials and the metric for NetworkPolicy ACL denials.
```
make ocm/setup
```
> ROX-23559: Export Violation Denial Metrics

- Makefile
- emailsender/Dockerfile
- emailsender/cmd/app/main.go
- emailsender/config/config_test.go
Add local building for Email service
```
make email-sender
...
make image/build/email-sender
docker run --rm -it -e CLUSTER_ID=test …
```
> ROX-23251: Add local deployment for email sender service

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Part of [ROX-22148](https://issues.redhat.com/browse/ROX-22148).
Since the cloudwatch resources are only located in us-east-1, we don't need to scrape for other regions within the cloudwatch exporter.
```
make ocm/setup
```
> fix: Remove eu-west-1 regions for cloudwatch exporter

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
The Deployment's `env` schema expects values as strings, even for boolean values. The Go code in the fleetshard-sync will do the conversion from string to bool internally. This quotes the boolean value.
Error:
> release upgrade failed; cannot patch "fleetshard-sync" with kind Deployment:  "" is invalid: patch: Invalid value: "": json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
> ROX 23550: Fix deployment, quote parameter

- internal/dinosaur/pkg/gitops/default_central.yaml
- internal/dinosaur/pkg/gitops/default_central_test.go
Expose scanner http monitoring port for Prometheus metrics. This will allow us to scrape scannerV4 pods.
```
make ocm/setup
```
> feat: enable scanner-v4 monitoring

- build_push_app_interface.sh
Reverts stackrox/acs-fleet-manager#1784 since build jobs are failing because of authorization issues.
> Revert "ROX-23252: add email sender to build and push"

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-central.yaml
CloudWatch logs show repeated NetworkPolicy denial from 10.128.2.21 to four IPs each running Central pods on port 8443 - we were missing a NetworkPolicy for Fleetshard Sync's "readiness" check on Central's auth provider existing.
Whether this auth provider configuration should exist or not now that it's declarative is debatable. If we remove it, we should remove this NetworkPolicy as well.
> ROX 23550: Fix fleetshard sync to central

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
- fleetshard/pkg/central/operator/upgrade_test.go
The `ose-kube-rbac-proxy` sidecar is no longer used by the ACS operator (as of 4.4.0, see https://github.com/stackrox/stackrox/pull/9808), so ACS CS should also no longer deploy it.
```
make ocm/setup
```
> ROX-22289: Remove kube-rbac-proxy sidecar

- fleetshard/pkg/central/charts/data/tenant-resources/templates/README.md
- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner.yaml
Added Scanner v2 Internet access per https://docs.openshift.com/acs/4.4/architecture/acs-architecture.html#acs-architecture-interaction-between-services_acs-architecture
- ~~[ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~~
- ~~[ ] Check AWS limits are reasonable for changes provisioning new resources~~
- ~~[ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on integration environment~~
Ongoing testing of Network Policies in ACSCS …
> ROX-23550: Add scanner egress to Internet for image registry access

- fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
- fleetshard/pkg/central/reconciler/reconciler_test.go
We are seeing network policy violations in Probe namespaces sporadically - ~4 spread over a few minutes each time a Probe cycle runs. We have a theory that it's due to the NetworkPolicy's being updated, potentially due to updates to the egress-proxy deployment. Since we'd like to remove it anyways, this PR disables the egress-proxy deployment creation; we can then see if it has the desired effect on the network policy reloading.
- ~~[ ] RDS changes were e2e …
> ROX-23555: Disable egress proxy creation when securing tenant network

- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
Adds an overlay to the dogfooding CR to prevent scanner SELinux violations for now.
A proper fix in the upstream Helm chart will be done as part of [ROX-24119](https://issues.redhat.com/browse/ROX-24119).
FYI @Maddosaurus 
```
make ocm/setup
```
> ROX-24120: Add overlay for collector DaemonSet

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/k8s/secret.go
- fleetshard/pkg/k8s/secret_test.go
The check on the expected error when central-tls secret was not yet created before routes get created was broken because the error we checked for was no longer returned. Leading to error logs like:
```
E0111 15:09:47.955154 1 runtime.go:246] Unexpected error occurred rhacs-cmg021tu6lpgt9015g6g/probe-7687b89ff9-kd2jv-4fb9: updating routes: creating reencrypt route for central cmg021tu6lpgt9015g6g: getting central-tls secret for tenant probe-7687b89ff9-kd2jv-4fb9: central-tls secret not found 
```
I've implemented a solution that should now properly check for this error again:
- ~~[ ] Added test description under `Test manual`~~ -> CI is sufficient
- ~~[] Add secret to app-interface Vault or Secrets Manager if necessary~~
- ~~[ ] RDS changes were e2e tested …
> ROX-21702: fix error matching logic for central-tls secret not found

- Makefile
- dev/env/defaults/04-crc.env
- dev/env/defaults/cluster-type-crc/env
- dev/env/scripts/docker.sh
- dev/env/scripts/lib.sh
Adjust crc settings for dev scripts in order to run microshift preset. 
More info: https://crc.dev/blog/posts/2023-04-05-microshift-on-crc/
Setup
```
$crc version
CRC version: 2.35.0+3956e8
OpenShift version: 4.15.10
Podman version: 4.4.4
```
```
$crc config view  
- consent-telemetry                     : yes
- cpus                                  : 8
- memory                                : 16384
- preset                                : microshift
```
Steps
```
crc setup
crc start
eval $(crc oc-env)
make deploy/bootstrap
```
> Build on microshift preset for crc

- .secrets.baseline
- dev/config/gitops-config.yaml
- e2e/e2e_canary_upgrade_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
- internal/dinosaur/pkg/api/private/api/openapi.yaml
- internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
- internal/dinosaur/pkg/gitops/config.go
- internal/dinosaur/pkg/gitops/service.go
- internal/dinosaur/pkg/gitops/service_test.go
- internal/dinosaur/pkg/presenters/managedcentral.go
- internal/dinosaur/pkg/presenters/managedcentral_test.go
- openapi/fleet-manager-private.yaml
Currently, only tweaking central CRs via gitops is possible. 
I want to enable the VPA only for select tenants. But the VPA will be defined in the "tenant-resources" helm chart. 
This PR adds the following features
- Defining the default tenant-resources chart values within the gitops config
- Overriding per-tenant tenant-resources chart values with gitops config
- "Graceful" fallback to previous implementation if the values are not provided via the gitops config
```
make ocm/setup
```
> ROX-24127: tenant resources via gitops

- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
- fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
There was a decision to drop CPU limits for ACS operator. Even though it is removed from gitops it still applies this default CPU limit for each running ACS Operator
N/A
> Drop default CPU limit for ACS operator

- pkg/auth/fleetshard_authz_middleware.go
I think the audience check is broken. I've reused it in one of my PRs (#1826) and tested it. It was always returning an error although I had a matching audience.
I think the issue is that when matching audiences we should return and not break the loop. At least that fixed it in my PR.
```
make ocm/setup
```
> fix: checkAudience by returning if an audience matched

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
This PR fixes an omission from the scanner-v4 network policies: matcher should allow egress to indexer.
Indexer is already allowing ingress from matcher.
```
make ocm/setup
```
> ROX-23749: fix scanner-v4-matcher network policy

- Dockerfile
Reverts stackrox/acs-fleet-manager#1838
The annotation breaks AppSRE builds.
> Revert "Add syntax annotation to Dockerfile"

- e2e/e2e_test.go
- fleetshard/pkg/central/reconciler/reconciler.go
Network policy violations caused by probes might be cause by a race condition where:
* the Central CR is deleted
* tenant network policies are deleted before the Central pod terminates
This is more likely to happen to probes, because normal instances also start a DB snapshot, which might increase the time spent between Central CR deletion and netpol deletion.
It's not really possible to test it except in the integration environment. If it does not fix the violations, I will revert it.
This change has uncovered a problem with the `should be created and deployed to k8s with admin API` e2e test, that includes a tenant name change. It was causing the deletion to hang, because in [ensureCentralCRDeleted](https://github.com/stackrox/acs-fleet-manager/blob/e5c71ef34ea02882e9dffbc7d2408988c67a2dfa …
> ROX-24158: Wait for central-service pods to terminate before netpol deletion

- dev/config/gitops-config.yaml
- e2e/e2e_canary_upgrade_test.go
Use ACS 4.4.z in the tests and dev env, to prevent error logs about scanner-v4 (unknown field in 4.3).
```
make ocm/setup
```
> fix(tests): Update ACS to 4.4.2 in e2e tests and dev env

- emailsender/pkg/email/ses.go
- emailsender/pkg/email/ses_test.go
Central sends raw email message bodies. It should be more convenient to use SES `SendRawEmail` API instead `SendEmail` because there is no need to parse Central's raw message in this case. Also, Central might send attachments and only `SendRawEmail` supports sending attachments.
~- [ ] Check AWS limits are reasonable for changes …
> ROX-23254: Add SendRawEmail method

- Makefile
- dp-terraform/helm/Dockerfile
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- Rename Fleetshard Operator image tag
- Automatically update Email Sender image tag in Fleetshard Operator
```
make ocm/setup
```
> ROX-23252: Automatically update email sender image tag

- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
The emailsender cmd in the deployment does not fit to the location of the binary in the docker image.
```
make ocm/setup
```
> fix: emailsender cmd

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-default.yaml
The empty `ingress: []` field is not needed, and Kubernetes does not store in the cluster, after the manifest is applied. 
When the network policies are re-applied, the difference in spec is possibly triggering a reconcile, and might be the cause of the network policy violations that we have in ACS CS during probe provisioning.
```
make ocm/setup
```
> ROX-24158: remove unnecessary field from tenant default network policy

- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/config/config.go
- emailsender/config/config_test.go
- emailsender/pkg/api/routes.go
- pkg/shared/tls.go
- pkg/shared/tls_test.go
Follow Up on #1826 .
This adds a function to the AuthConfig of emailsender that allows reading it from it's own Kubernetes service account.
emailsender is expected to be called by central with it's Kubernetes service account. Since emailsender has its own service account as well we can use that information to read the configuration values required for authentication (issuer, audience, jwks_url).
This way we don't need a config file / config map that is different per environment we deploy to, where we have to manually managed the input vars (e.g addon parameters).
- Deployed the emailsender service to kube
- Create a dummy pod central in a dummy namespace rhacs-test with nginx image called central
- Exec into that pod and send a curl to emailsender with the serviceaccount -> works
- Send …
> ROX-23255: emailsender read auth cfg from kubernetes

- config/emailsender-authz.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/cmd/app/main.go
- emailsender/config/config.go
- emailsender/config/config_test.go
- emailsender/pkg/api/emailhandler.go
- emailsender/pkg/api/emailhandler_test.go
- emailsender/pkg/api/middleware.go
- emailsender/pkg/api/middleware_test.go
- emailsender/pkg/api/routes.go
- emailsender/pkg/api/routes_test.go
- pkg/auth/acs_claims.go
- pkg/auth/context_config.go
- pkg/auth/fleetshard_authz_middleware.go
- pkg/auth/fleetshard_authz_middleware_test.go
- pkg/errors/errors.go
- pkg/shared/tls.go
- pkg/shared/tls_test.go
Additional to the added unit tests I tested the API as follows:
```
export CLUSTER_ID=test
go run emailsender/cmd/app/main.go
curl localhost:8080/api/v1/acscsemail -H "Authorization: Bearer $(ocm token)" -H "Content-Type: application/json" -XPOST --data-raw '{"to":["test@test.acscs-email.test"],"rawMessage":"dGVzdCBtZXNzYWdlIGNvbnRlbnQ="}' -v
curl localhost:8080/api/v1/acscsemail -H "Content-Type: application/json" -XPOST --data-raw '{"to":["test@test.acscs-email.test"],"rawMessage":"dGVzdCBtZXNzYWdlIGNvbnRlbnQ="}'
```
```
make ocm/setup
```
> ROX-23255: add auth implementation for emailsender API

- internal/dinosaur/pkg/services/addon.go
- pkg/metrics/metrics.go
The metric is needed when the OCM api returns success after an update, but something is wrong on the cluster and the components cannot be updated. This leads to a situation where all components of the data plane are running but are not up to date.
```
make ocm/setup
```
> ROX-22549: Add an addon metric to track version mismatch

- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/cmd/app/main.go
- emailsender/config/config.go
- emailsender/pkg/api/emailhandler.go
- emailsender/pkg/email/sender.go
I tested sending emails via emailservice locally and discovered some problem that I needed to be fixed to be able to send a first email.
- Add a from header that looks more human friendly than the only the email address
- Have the sender address configurable (addon part t.b.d but it is now a helm value)
- Adding json tags to the SendEmailRequest so that it fits to the object send by central
- Adding some comments to satisfy Go linter
- Run the emailsender locally
- Open stackrox repo
- add a temporary test:
```
func TestEmailSending(t *testing.T) {
t.Setenv("ROX_ACSCS_EMAIL_URL", "http://localhost:8080")
acscsEmail := acscsEmail{
client: &clientImpl{
loadToken: func() (string, error) {
return "<your-ocm-token-here>", nil
},
url:        fmt.Sprintf("http://localhost:8080%s", sendMsgPath), …
```
> ROX-23249: multiple emailsender issues discovered by debugging

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- dp-terraform/test/helm_template_test.go
- fleetshard/config/config.go
Add TENANT_IMAGE_PULL_SECRET to the dp-terraform helm chart in order to derive an imagepullsecret from fleetshard-sync namespace
```
make ocm/setup
```
> ROX-20474: Add TENANT_IMAGE_PULL_SECRET to the dp-terraform helm chart

- internal/dinosaur/pkg/gitops/config.go
- internal/dinosaur/pkg/gitops/provider_test.go
- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
- internal/dinosaur/pkg/workers/clusters_mgr.go
- pkg/metrics/metrics.go
For better readability
```
make ocm/setup
```
> ROX-22549: Change cluster_id label to cluster_name for the addon status metric

- e2e/e2e_suite_test.go
- e2e/e2e_test.go
I'd remove the tenant name change tests, because they give the false impression that the feature works out of the box, and they were also hiding incorrect behavior:
- the test was hiding the fact that a name change triggers the creation of a second Central in the namespace, because the name change and the deletion were performed at the same time, 
- `ensureCentralCRDeleted` was not deleting the central, instead it was deleted by `ensureNamespaceDeleted` which is why the tests were passing
Now because of https://github.com/stackrox/acs-fleet-manager/pull/1842 `ensureCentralCRDeleted` is timing out, so I'd remove them altogether for now, unless we want to fix the renaming logic soon.
```
make ocm/setup
make verify …
```
> ROX-21884: remove commented out tenant name change test

- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
This PR add a kubernetes svc resource for the emailsender template.
The service includes an annotation that will cause openshifts service-ca operator to create a secret called `emailsender-tls` that contains a cluster internal CA certfiicate.
The PR also changes the emailsender deployment to use this certificate.
Tested by rendering and applying emailsender manifest locally on a crc:
```
helm template --namespace rhacs --set "secured-cluster.clusterName=test,secured-cluster.centralEndpoint=test,fleetshardSync.managedDB.enabled=false,emailsender.enabled=true,emailsender.clusterId=test,emailsender.clusterName=test,emailsender.environment=dev" . | yq e '. | select(.metadata.name == "emailsender")' > emailsender-manifests.yaml
k apply -f emailsender-manifests.yaml
```
> ROX-23253: add emailsender TLS service to helm template

- internal/dinosaur/pkg/services/addon.go
- pkg/metrics/metrics.go
I realized that I misused the label concept in Prometheus. From the [docs](https://prometheus.io/docs/practices/naming/):
```
CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
```
Basically, every label brings an extra dimension. Because of that I can't build the graph I want.
```
make ocm/setup
```
> ROX-22549: Remove excessive labels for the addon metric

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
Need to allow port 9091 because of this change: https://github.com/stackrox/stackrox/pull/10982
```
make ocm/setup
```
> ROX-23749: Allow Scanner V4 observability ingress on port 9091

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
From ACS 4.5 onwards, Scanner V4 indexer and matcher require egress access to the Kube API, for mTLS setup for OpenShift monitoring.
See also:
https://github.com/stackrox/acs-fleet-manager/pull/1881
https://github.com/stackrox/stackrox/pull/10982
```
make ocm/setup
```
> ROX-23749: allow indexer and scanner egress to kube API

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
This change fixes an error when SERVICE_ACCOUNT_TOKEN auth type is enabled
```
mountPath must be unique
```
```
make ocm/setup
```
> ROX-23709: Fix the volume mount error

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
After the fix in #1889 token is not refreshed by kubelet after 1 hour.
```
make ocm/setup
```
> ROX-23709: Fix token expiration

- dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
This PR adds a external secret to emailsender helm chart, that is supposed to make the DB configuration available from an AWS secret.
https://github.com/stackrox/acs-fleet-manager-aws-config/pull/214 is required first, to create the secret that should be load into the cluster.
```
make ocm/setup
```
> ROX-23260: add external secret for emailsender db config

- .openshift-ci/e2e-runtime/Dockerfile
- .openshift-ci/tests/e2e.sh
- .openshift-ci/tests/netpol-test.sh
- test/network-policy/fake-client/Chart.yaml
- test/network-policy/fake-client/templates/deployment.yaml
- test/network-policy/fake-client/values.yaml
- test/network-policy/fake-service/Chart.yaml
- test/network-policy/fake-service/templates/configmap.yaml
- test/network-policy/fake-service/templates/deployment.yaml
- test/network-policy/fake-service/templates/service.yaml
- test/network-policy/fake-service/values.yaml
This PR introduces tests for the tenant network policies.
The `fake-service` service and `fake-client` deployment can then be used to mock ACS components, by applying the appropriate labels and setting the ports where they listen or connect to. They can easily be installed using Helm.
They can then be used to write tests, such as the following:
* create a fake Central in namespace A, and a fake Scanner in namespace B
* show that Scanner can connect to Central
* apply the network policies, in turn, in namespace A and then namespace B
* shows that in both cases, the communication is interrupted - proving that the network policies prevent lateral communication between tenants in this case
They will run on OpenShift CI, as part of the e2e test suite.
``` …
```
> ROX-23967: Tenant network policies tests

- fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-central.yaml
This PR adds the cluster internal emailsender service/pods to the allowed egress traffic for the tenant-central network policy.
```
make ocm/setup
```
> ROX-23258: add emailsender to egress NP for central

- dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
> ROX-23260: Use fleetshardsync clusterName value

- emailsender/cmd/app/main.go
- emailsender/pkg/email/ratelimiter.go
> ROX-23260: Setup rate limiter

- scripts/import_init_bundle.sh
Add a script to easily import an init-bundle to Secrets Manager
```
make ocm/setup
```
> ROX-24844: Add a script to easily import an init-bundle to Secrets Manager

- dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
> Use emailsender clusterName in secret

- .github/workflows/aws-integration.yaml
- dev/env/scripts/exec_fleetshard_sync.sh
Use the github role instead of the technical user in AWS integration tests
```
make ocm/setup
```
> Use the github role instead of the technical user in AWS integration tests

- Makefile
- emailsender/pkg/email/ses_integration_test.go
This PR adds a integration to the AWS SES code implemented for the emailsender.
It also changes the Makefile so that this test is executed within the AWS integration test Github Action.
- Login to the AWS dev account
- Run: `RUN_AWS_INTEGRATION=true go test github.com/stackrox/acs-fleet-manager/emailsender/pkg/email`
> ROX-24936: add AWS integration test for emailsender

- Makefile
- emailsender/README.md
- emailsender/pkg/db/models.go
Extending the dev documentation for emailsender component.
Consistency of the link depends on merges of:
- https://gitlab.cee.redhat.com/stackrox/acs-cloud-service/runbooks/-/merge_requests/106
- https://github.com/openshift/openshift-docs/pull/77408
```
make ocm/setup
```
> ROX-25022: emailsender dev docs

- Dockerfile
I was not able to find the root cause but current dockerfile is failing if build with podman. Somehow `go mod download` do not see mounts with podman build but docker build works totally fine at the same time. This PR changes building a little so both podman and docker can build the image.
*NOTE:* I increased memory for podman machine locally because otherwise it is getting OMMed when building the Dockerfile. I dont know podman machine parameters on appSRE node.
```
docker build -t fm .
// OK
podman build -t fm .
// OK
```
> ROX-24458: Add podman support for dockerfile

- .openshift-ci/tests/netpol-test.sh
More tenant network policy tests, to cover more cases.
```
cd .openshift-ci/tests
KUBECTL=oc ./netpol-test.sh
```
> ROX-23967: Add more tenant network policy tests

- emailsender/cmd/app/main.go
- emailsender/config/config.go
- emailsender/pkg/db/connect.go
- emailsender/pkg/db/mock.go
- emailsender/pkg/email/ratelimiter_test.go
- emailsender/pkg/workers/cleanup.go
- emailsender/pkg/workers/cleanup_test.go
We don't cleanup emails that we don't longer need to enforce our 24h rolling window for rate limits.
This can lead to a ever growing DB and performance penalties for a long running emailsender DB.
This PR solves this problem by adding a background job that periodically deletes all email sent events older than 2 days.
```
make db/teardown db/setup
CLUSTER_ID=CLUSTER_ID go run emailsender/cmd/app/main.go
make db/psql
INSERT INTO email_sent_by_tenants (tenant_id, created_at) VALUES ('test', NOW()');
INSERT INTO email_sent_by_tenants (tenant_id, created_at) VALUES ('test', NOW()- INTERVAL '3 DAY');
```
> fix: add a cleanup job for email events

- fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
It is a leftover after removing rbac proxy from the Operator
```
make ocm/setup
```
> Drop redundant resource values for rbac proxy

- Dockerfile
Return docker build cache for go dependencies. Add a descriptive comment.
```
make ocm/setup
```
> Restore go dependency caching with layers

- emailsender/config/config.go
- emailsender/config/config_test.go
Use a configurable `jwks_uri` independent from the openid discovery document for emailsenders internal kubernetes authentication.
This proofs to be more reliable since every K8s distribution we use has `https://kubernetes.default.svc/openid/v1/jwks` for internal access to the jwks keys, while it seems that each distribution (crc, minikube, OSD, ROSA, colima, infra OCP) return different URLs. Those URLs all require different handling:
- K8s Pod IP in URL
- K8s Node IP in URL
- K8s svc DNS in URL
- Public facing URL
- Some require authentication, some don't
If we face a K8s distribution that doesn't follow that pattern we can still modify the URL via the new env configuration values.
CI is sufficient.
> ROX-25276: emailsender auth on rosa

- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-logging.yaml
This changes the configuration of the openshift-logging operator to change the logging backend from `fluentd` to `vector`. It doesn't change the configuration yet.
See https://access.redhat.com/articles/6999658.
```
make ocm/setup
```
> ROX-24895: Migrate from fluentd logging to vector logging

- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
Since Prometheus can't watch multiple namespaces, remove the namespace selector introduced in #1962
```
make ocm/setup
```
> ROX-21531: Remove probe namespace selector from the Observability CR

- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
the `global.image.tag` will only be considered if the specific sections do not specify an image tag.
this is a common pattern and can be helpful for app-interface deployments: https://github.com/app-sre/qontract-reconcile/pull/4557
```
make ocm/setup
```
> introduce global.image.tag for rhacs-terraform helm chart

- dev/config/gitops-config.yaml
Switch ACS operator in dev gitops config to fast stream **mainly for arm64 support**.  
```
make ocm/setup
```
> Switch ACS operator in dev gitops config to fast stream

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Fallout of #1971. The exporter pod is crashing with
```
{"caller":"main.go:67","err":"Couldn't read /tmp/config.yml: Discovery job [0]: Invalid 'type' field, use namespace \"AWS/RDS\" rather than alias \"rds\"","level":"error","msg":"Error running yace","ts":"2024-08-05T12:43:18.745446387Z","version":"v0.61.2"}
```
```
make ocm/setup
```
> fix(terraform): cloudwatch exporter config

- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/cmd/app/main.go
- emailsender/config/config.go
- emailsender/pkg/email/sender.go
- emailsender/pkg/email/sender_test.go
- emailsender/pkg/email/ses.go
This PR adds:
- A abstraction layer to be able to create different email.Sender interface implementation
- Configuration options to determine which concrete implementation to use
- A LogEmailSender implementation fo the email.Sender interface
I want to use the new LogEmailSender implementation to be able to run central <> emailsender API compatibility tests without having to provide AWS credentials. This tests will be running in both repositories stackrox/stackrox and stackrox/acs-fleet-manager and I don't want to provide stackrox/stackrox credentials to access any ACSCS cloud accounts.
- ~~[ ] Unit and integration tests added~~ -> current tests are sufficient.
- ~~[ ] RDS changes were e2e tested …
> ROX-24936: add abstraction for email.Sender to allow multiple impl

- internal/dinosaur/pkg/handlers/validation.go
Validating the names that users specify when creating centrals. When you create a central, this ends up being a Central Kubernetes resource. But Kubernetes has strict rules around the allowed names of object. This PR is to ensure that we're validating the name like Kubernetes does. The scenario we want to prevent is allowing the creation of a Central with a name that is invalid for kubernetes. For example, a name that is not allowed by Kubernetes, could be allowed by FleetManager when creating an instance. Because of that, we changed the validation rules for:
`ValidDinosaurClusterName` in `validation.go` (acs-fleet-manager) to follow the rules from 
--> `ValidateCustomResourceDefinition` in `validation.go` (apiextentions-apiserver)
validation_test.go …
> ROX-23367: Central Name Validation

- .github/workflows/emailsender-central-compatibility.yaml
- .gitignore
- Makefile
- dev/env/scripts/lib.sh
- emailsender/compatibility/emailsender_central_test.go
- emailsender/compatibility/post-acscsemail-integration.json
- scripts/ci/central_compatibility/central-values.yaml
- scripts/ci/central_compatibility/emailsender-db.yaml
- scripts/ci/central_compatibility/emailsender-values.yaml
- scripts/ci/central_compatibility/entrypoint.sh
- scripts/ci/central_compatibility/run_compatibility_test.sh
Adds a Github Action to test compatibility of central <> emailsender:
- Uses Kind to setup a K8s cluster in an ubuntu node
- Deploys a stackrox nightly and a fresh build emailsender to kind
- Tests if central can send notification to emailsender via central API
To run locally:
```
mkdir workspace
cd workspace
git clone git@github.com:stackrox/stackrox.git
git clone git@github.com:stackrox/acs-fleet-manager.git    
export GITHUB_REPOSITORY=acs-fleet-manager
bash scripts/ci/central_compatibility/entrypoint.sh
```
> ROX-24936: emailsender central compatibility test

- emailsender/pkg/email/sender.go
- emailsender/pkg/email/sender_test.go
This PR fixes emailsender to set the "To" header of emails sent. The header is explicitly not set by the acscsEmail integration to allow emailsender to append. But that part was forgotten during initial implementation.
This led to emails being send but email clients would show an empty To header.
```
make db/teardown db/setup
#Login to ocm and AWS dev account before running this
make run/emailsender
curl localhost:8080/api/v1/acscsemail -v -XPOST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $(ocm token)" \
--data-raw '{"to":["jmalsam@redhat.com"], "rawMessage":"dGVzdCBtZXNzYWdlIGNvbnRlbnQ="}'
```
> fix: add To header to emailsender emails

- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
For ArgoCD to be allowed to manage resources in tenant namespaces, these namespaces must have a label
See https://docs.openshift.com/container-platform/4.10/cicd/gitops/configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations.html#creating-an-application-by-using-the-oc-tool_configuring-an-openshift-cluster-by-deploying-an-application-with-cluster-configurations
```
make ocm/setup
```
> ROX-26027: add argoCD labels to tenant namespaces

- Dockerfile
Konflux needs exactly 'Red Hat, Inc.' label in dockerfile
> Fix label in dockerfile to follow Konflux requirements

- .github/workflows/emailsender-central-compatibility.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- scripts/ci/central_compatibility/emailsender-values.yaml
Adding env variable DATABASE_SSL_MODE and corresponding helm value to the dp-terraform chart.
```
make ocm/setup
```
> fix: add emailsender db ssl mode to helm chart values

- Makefile
The Makefile target `image/build/fleetshard-operator` is failing for me because `--load` is a docker buildx only option.
```
make deploy/bootstrap deploy/dev
```
> fix: Makefile docker command for fleetshard-operator

- .github/workflows/emailsender-central-compatibility.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/Dockerfile
- scripts/ci/central_compatibility/emailsender-values.yaml
New attempt for #2028 which includes installing RDS ca cert file into the emailsender container image.
```
podman run -e CLUSTER_ID=test -e DATABASE_HOST='emailsender-local-test.cluster-cz7zwsnynmtn.us-east-1.rds.amazonaws.com' -e DATABASE_PASSWORD='<pw>' -e DATABASE_SSL_MODE='verify-full' -e DATABASE_CA_CERT_FILE='/rds_ca/aws-rds-ca-global-bundle.pem' --privileged -v /root/config:/config --rm -ti quay.io/rhacs-eng/emailsender:a4d1fcb
```
> fix: emailsender use TLS for db connections

- .github/workflows/emailsender-central-compatibility.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/Dockerfile
- scripts/ci/central_compatibility/emailsender-values.yaml
Reverts stackrox/acs-fleet-manager#2035
It appears that OSD is assigning a different user to run emailsender as opposed to what is defined in the Dockerfile for emailsender. This causes ownership of the CA certificate to be wrong, so emailsender crashes.
> Revert "fix: emailsender use TLS for db connections"

- .github/workflows/emailsender-central-compatibility.yaml
- dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- emailsender/Dockerfile
- scripts/ci/central_compatibility/emailsender-values.yaml
Follow up on
#2035 
Fixed the issue we had on integration by making the RDS ca file readable for all users.
```
docker run -e CLUSTER_ID=test -e DATABASE_HOST='emailsender-test.cluster-cz7zwsnynmtn.us-east-1.rds.amazonaws.com' -e DATABASE_PASSWORD='db-pw' -e DATABASE_SSL_MODE='verify-full' -e DATABASE_CA_CERT_FILE='/rds_ca/aws-rds-ca-global-bundle.pem' --user 1001180000 -v /root/config:/config:z --rm -ti quay.io/rhacs-eng/emailsender:136f53f
```
> fix: emailsender to DB TLS connection

- Makefile
By default make test/integration does not set any OCM_ENV environment variable. Because of that local executions usually fails with 5 failing tests while CI execution succeeds because it sets OCM_ENV=integration in the workflow definition.
Since those tests are integration tests and expect to have OCM_ENV=integration set to succeed this env variable should be set by default for the Makefile target.
```
make ocm/setup
make test/integration
```
> fix: default for make test/integration

- templates/probe-template.yml
Add serviceAccount with quay secret to ACSCS probe service. It should fix lack of permission to pull images from Konflux quay org on app-interface for the service
N/A
> ROX-26424: Add service account with quay secret to ACSCS probe service

- dp-terraform/helm/Dockerfile
- dp-terraform/helm/rhacs-terraform/values.yaml
- dp-terraform/test/helm_template_test.go
Switch Fleetshard-sync and Emailsender services to Konflux based images. Images are pullable and also have `git_short_sha` tags. Default tag in Konflux is `latest`.
```
podman pull quay.io/redhat-services-prod/acscs-rhacs-tenant/acscs-main/acs-fleet-manager:f636090
Trying to pull quay.io/redhat-services-prod/acscs-rhacs-tenant/acscs-main/acs-fleet-manager:f636090...
Getting image source signatures
Copying blob sha256:83d79038125ccc1484a67d0242d6b6fb16d135546bae21fe4a63b97f0f6e82b5
Copying blob sha256:133388727492505cb9d292d14f00942ad2915ab7df3ec1aabbea88cd25035f7b
Copying blob sha256:9ce83ecc988c9fd2bb533e68e07248d1bdbce9482114eae1ccda583d57c4aa5f
Copying config sha256:5b4b5fb18b359771f67f32837b131bbd1d07f5089fc3455952e6f31f9eb888bf
Writing manifest to image destination …
```
> ROX-26478: Use Konflux based images fleetshard emailsender

- README.md
We've got broken references to external services in the README.md overview. Even if not broken, I don't think those refs provide a lot of value so I suggest to just remove them.
```
make ocm/setup
```
> chore: remove broken references in README

- .openshift-ci/tests/e2e.sh
- Makefile
> Remove ocm login in e2e tests

- Makefile
- e2e/run_e2e_stage.sh
- probe/config/config.go
- templates/probe-template.yml
-Switch Authentication type OCM–> RHSSO in Probe Service. 
-And Delete OCM AuthType from Probe Service
Jira ticket: https://issues.redhat.com/browse/ROX-26359
Main Epic: https://issues.redhat.com/browse/ROX-24048
> ROX-26359: Switch Authentication Type Probe Service Update

- dp-terraform/helm/Dockerfile
- dp-terraform/helm/konflux.Dockerfile
Add a new dockerfile for fleetshard operator for Konflux. It is required to use only RH approved images for building on Konflux. This change should unblock building fleetshard operator on Konflux.
This dockerfile will be used in the Konflux bot PR #2063
build and run locally
> ROX-26499: Use RH certified helm operator image for fleetshard operator

- .github/workflows/ci.yaml
Pre-commit CI fails because we use python version which complains when you install system wide package via pip and pre-commit action is doing exactly that under the hood. We need to specify python setup so non default python from ubuntu is used. The error comes from the [PEP-668](https://peps.python.org/pep-0668/)
You can see CI failure in the [empty line to trigger pre commit CI](https://github.com/stackrox/acs-fleet-manager/pull/2066/commits/4609eda1efbbfc9074e8cc75448cb617cc0ed024) commit
```
Run pre-commit/action@v3.0.1
Run python -m pip install pre-commit
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a …
```
> Fix pre commit CI actions

- .tekton/acs-fleetshard-operator-pull-request.yaml
- .tekton/acs-fleetshard-operator-push.yaml
Pass `IMAGE_TAG` env value to the Fleetshard Operator Konflux dockerfile. It should be short git commit SHA like we build it locally or on github actions. `IMAGE_TAG` is a crucial value and sets which fleetshard/emailsender images to run
~- [ ] (If applicable) …
> ROX-26499: Specify IMAGE_TAG for the fleetshard operator build on Konflux

- fleetshard/main.go
- fleetshard/pkg/fleetshardmetrics/metrics.go
- internal/certmonitor/certmonitor.go
- internal/certmonitor/certmonitor_test.go
Background: Implement monitoring for certificate expiration, tracking and managing of digital certificates expiration dates. Extracts timestamps from certificates and exposes metrics to Prometheus. (FIXED)
In response to error in: https://github.com/stackrox/rhacs-observability-resources/pull/279
Problem: `acs_fleetshard_certificate_expiration_timestamp` - seems to retain all certificates even after their namespaces have been deleted. Combined with the ephemeral instances created by the probe, this creates a very large number of time series. 
Solution: Fixed the handling of metric deletion by:
-adding namespace informer
-implemented `DeletePartialMatch` instead of `Delete`
Previous Certificate Monitoring PR: https://github.com/stackrox/acs-fleet-manager/pull/1946
Previous Certificate …
> ROX-21530: Updating Cert Expiry Metrics

- .secrets.baseline
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-01-namespace.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
- dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
- dp-terraform/test/helm_template_test.go
When you uninstall the obserability helm subchart, the CR is deleted together with the operator and the namespace, which causes the CR and the namespace to remain stuck in the uninstallation state
In order to shutdown the observability operator gracefully you need to perform the following sequence of actions:
1. Set `observability.customResourceEnabled=false` to delete the CR and effectively uninstall prometheus, alertmanager and grafana but, keep the operator and most importantly the PVCs associated with prometheus and alertmanager. 
2. Set `observability.enabled=false` to uninstall the operator
As a result, the `rhacs-observability` namespace and the PVCs are NOT removed in order to retain the existing metrics.
```
make db/teardown db/setup …
```
> ROX-26065: Observability subchart teardown

- dp-terraform/helm/konflux.Dockerfile
There is an external-secrets helm subchart. It has a `securityContext.runAsUser: 1000` default value. Openshift doesn't allow to use 1000 user. That's why there [is an override](https://github.com/stackrox/acs-fleet-manager/blob/main/dp-terraform/helm/rhacs-terraform/values.yaml#L258) in the `values.yaml`.
There is separate Konflux Dockerfile for ACS Fleetshard Operator. It uses a trusted helm operator image but unfortunately this image has [a bug](https://github.com/operator-framework/operator-sdk/issues/6635) which ignores overriding default values for the subchart. Because of that setting to null  `securityContext.runAsUser` for external secrets is ignored. Which leads to violating scc
This PR should fix it by manually dropping `runAsUser` value from the external secret subchart.
``` …
```
> ROX-26745: Fix konflux based ACS fleetshard operator ignoring subchart default values override

- fleetshard/pkg/central/reconciler/reconciler.go
Adding required argoCD application parameters in preparation of moving Central CRs to ArgoCD
```
make ocm/setup
```
> Add additional argoCD parameters for Central CRs

- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
This PR prevents sending to many upgrade requests to OCM in case the addon is stuck in an upgrading state. It limits update requests to once every 20 minutes.
This was introduced due to a incident where fleet-managers update calls reached the OCM service logs limit and thus caused cluster features like z stream updates to fail.
```
make ocm/setup
```
> ROX-26421: add backoff logic if addon is stuck in upgrading

- dev/config/gitops-config.yaml
- dev/env/manifests/openshift-gitops/04-clusterrole.yaml
- fleetshard/pkg/central/reconciler/argo_reconciler.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
This PR allows toggling the reconciliation of the Central CR by ArgoCD.
TODO before merging/enabling: Change the gitops configuration, so that the overrides are migrated to `tenantResourcesValues`
1. In the gitops config, toggle `tenantResourcesValues.argoCd.centralEnabled` on or off
2. Observe that ArgoCD reconciles the Central CR resource
3. Observe that the Argo-CD- and Fleetshard- reconciler Centrals are mostly the same.
> ROX-24523: Move central to ArgoCD

- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-secrets.yaml
- dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- dp-terraform/test/helm_template_test.go
Conditionally load image pull secrets from Secrets Manager 
```
make ocm/setup
```
> ROX-27209: Create external secrets for quay image pull secrets

- dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
Enables specifying the ArgoCD application source using addon parameters
```
make ocm/setup
```
> Add helm parameters for argocd application

- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
The addon upgrade backoff was implemented without differencing upgrade requests to distinct clusters. So that any stuck upgrade would stop sending requests to clusters that are not stuck.
The Last Install status is now tracked on a per cluster and addon id basis. And the backoff logic respects that as well.
CI
> fix: backoff addon upgrade on a per install basis

- fleetshard/main.go
> ROX-27244: serve pprof server with fleetshard-sync

- dev/env/manifests/fleetshard-operator/07-serviceaccount.yaml
- dev/env/manifests/fleetshard-operator/51-fleetshard-cr.yaml
- dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
- dev/env/scripts/bootstrap.sh
- dev/env/scripts/create-imagepullsecrets
- dev/env/scripts/up.sh
- fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
- Remove `acs-fleetshard-operator` image pull secret
- Reference `rhacs-registry` image pull secret for ACS operator deployments instead
- Change the meaning of `TENANT_IMAGE_PULL_SECRET` env variable. Now it contains secret name, instead of containing its value. This will allow the secret not to be created if `INHERIT_IMAGEPULLSECRETS` is false.
```
make ocm/setup
```
> ROX-27209: Change image pull secret for operator deployments

- dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-04-operator-group.yaml
DP terraform helm chart doesn't install the Openshift logging operator on the clusters where it is not installed.
```
make ocm/setup
```
> Add missing operator group for the logging operator

- fleetshard/config/config.go
- fleetshard/pkg/central/reconciler/argo_reconciler.go
- fleetshard/pkg/runtime/runtime.go
https://issues.redhat.com/browse/ROX-27131
Fixes wrong naming of environment variable names pertaining to tenant's ArgoCD applications
```
make ocm/setup
```
> ROX-27131: fix tenant ArgoCD environment variable names

- .github/workflows/aws-integration.yaml
- .github/workflows/ci.yaml
- .github/workflows/emailsender-central-compatibility.yaml
- .golangci.yml
- .openshift-ci/e2e-runtime/Dockerfile
- Dockerfile
- Dockerfile.tools
- README.md
- emailsender/Dockerfile
- fleetshard/pkg/central/reconciler/gen/main.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- go.mod
- pkg/client/ocm/impl/client_impl.go
- pkg/client/ocm/impl/client_test.go
- pkg/client/redhatsso/serviceaccounts/integration/client_test.go
- pkg/db/model_type_check.go
- pkg/services/account/account_mock.go
- probe/Dockerfile
- tools/go.mod
Migrate to 1.22 golang
_Note_: `ubi8/go-toolset` support only 1.22.9 golang version ATM
```
make binary
```
> Bump golang to 1.22

- emailsender/pkg/email/sender.go
- emailsender/pkg/email/sender_test.go
Add tenantID to the email sender Alias to make it clear that email sent for specific instance 
N/A
> ROX-25966: Add tenantID to email from alias

- fleetshard/pkg/central/reconciler/managed_db_reconciler.go
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/reconciler_test.go
- fleetshard/pkg/central/reconciler/util.go
This PR refactors the `CentralReconciler` to introduce a dedicated `ManagedDbReconciler`
It also changes the `ensureSecretExists` and `checkSecretExists` to be methods without a receiver, rendering them able to be used by other parts of the code. In this case, these methods are both used by `CentralReconciler` and `ManagedDbReconciler`
> ROX-27129: extract managed-db-reconciler

- fleetshard/pkg/central/reconciler/argo_reconciler.go
- fleetshard/pkg/central/reconciler/argo_reconciler_test.go
This PR adds the capability to specify, through `tenantResourcesValues`, a custom ArgoCD source (path/revision/repo).
This is useful because this allows overriding a single tenant, so that it uses a different set of manifests from the `acscs-manifests` repository.
Example:
```
tenantResources:
overrides:
- instanceIds: [...]
values: |
argoCd:
sourceTargetRevision: "abc"
sourcePath: "/custom-manifests"
sourceRepoUrl: "github.com/my-custom-repo"
```
> ROX-23278: Allow specifying custom argoCD application source per tenant

- .gitignore
- .secrets.baseline
- Makefile
- e2e/dns/record_cleanup.go
- e2e/e2e_canary_upgrade_test.go
- e2e/e2e_suite_test.go
- e2e/e2e_test.go
- e2e/multicluster/multicluster_migration_test.go
- e2e/multicluster/multicluster_suite_test.go
- e2e/testutil/assert.go
- e2e/testutil/testutil.go
- fleetshard/pkg/k8s/client.go
- internal/dinosaur/pkg/presenters/admin_dinosaur.go
- pkg/client/fleetmanager/client.go
- pkg/client/fleetmanager/mocks/client_moq.go
- Adds a ginkgo e2e test suite for multicluster test
- First test verifies cluster migration between multiple clusters
- Adds a make target to run the tests test/multicluster/e2e
- Moved common logic with other e2e tests to a `testutils` package
- Change admin CentralRequest presenter to actually set the ClusterId, which is required for the test
- See test manual on how to execute this agains 2 infra clusters
- Extends our k8s client pkg to allow loading config for multiple cluster
```
kinit jmalsam
export CLUSTER_TYPE="infra-openshift"
export CLUSTER_1_KUBECONFIG=/Users/johannes/kubes/cluster1
export CLUSTER_2_KUBECONFIG=/Users/johannes/kubes/cluster2
export QUAY_USER=<your user>
export QUAY_TOKEN=<your token>
export ENABLE_CENTRAL_EXTERNAL_CERTIFICATE="true"
export …
```
> ROX-27073: add cluster migration e2e test

- internal/dinosaur/pkg/services/dinosaur.go
- internal/dinosaur/pkg/services/dinosaur_test.go
There's a bug that the restore API for deleted tenants does not reset EnteredProvisioningAt which causes restore to fail.
```
make ocm/setup
```
> fix: reset EnteredProvisioningAt for restore operation

- internal/dinosaur/pkg/services/dinosaur.go
A new subscription is created, but the subscription ID value in the database remains old.
```
make ocm/setup
```
> fix: update subscription id in the database when changing billing parameters

- internal/dinosaur/pkg/services/addon.go
- internal/dinosaur/pkg/services/addon_test.go
There is only a PATCH endpoint for updating addons in OCM.
So when a parameter is removed from the gitops config, it is not removed from the addon installation or switched to default value as expected, but remains there unmodified. As a result, there will always be a mismatch between the addon installed on the cluster and the expected state of the addon represented in the gitops config.
The proposed solution is to get all the default parameters for the given addon version and enrich the expected addon parameters by the default values. 
This will only help if the engineer wants to switch from the value defined in gitops to the default value defined in OCM. **When they need to remove a parameter from OCM, it always requires a new version to be released in OCM.**.
So the full procedure of …
> ROX-24494: ACSCS Addon overrides in Gitops lingers after removing from Gitops

- Makefile
- dev/config/gitops-config.yaml
- fleetshard/pkg/central/reconciler/reconciler.go
- fleetshard/pkg/central/reconciler/util.go
- fleetshard/pkg/k8s/route.go
- fleetshard/pkg/testutils/k8s.go
- templates/secrets-template.yml
Add support for the routes reconciliation on ArgoCD. 
The feature can be now enabled by setting the value `centralIngressEnabled` to `true` in the gitops config.
If disabled (default), reconciliation should be performed in fleetshard-sync mode as before.
If enabled, the routes created by fleetshard-sync are deleted and the reconciliation will be performed by tenant-resources (ArgoCD).
Next steps:
1. Enable the feature on dev environment to make E2E tests pass with the new setup.
2. Enable the feature on the rest environments and effectively delete the routes reconciled by fleetshard-sync.
3. Set `centralIngressEnabled` to true by default in `tenant-resources`
4. Cleanup the fleetshard-sync source code by removing the switch and code which is responsible for the routes reconciliation. …
> ROX-27980: Support argocd reconciliation for routes 

- dp-terraform/helm/Dockerfile
- dp-terraform/helm/rhacs-terraform/Chart.lock
- dp-terraform/helm/rhacs-terraform/Chart.yaml
- dp-terraform/helm/rhacs-terraform/values.yaml
- Upgrades the external secret helm chart and image to 0.14.4
- Removes our special handling of `securityContext.runAsUser` because the helm chart implemented openshift specific logic with https://github.com/external-secrets/external-secrets/pull/3420
Manually tested installing the helm chart against infra OCP cluster and made sure there are no conflicts with SCCs
> ROX-27835: update external secret operator and remove special handling of user

- .tekton/base-acscs-pipeline.yaml
- Bump `ecosystem-cert-preflight-checks` to the latest version
- Add `sast-shell-check`, `sast-unicode-check` and `sast-coverity-check`. Those tasks will be required by 2025-04-01 according to Konflux logs: 
```
[Warning] tasks.future_required_tasks_found
ImageRef: quay.io/redhat-user-workloads/acscs-rhacs-tenant/acscs-main/acs-probe@sha256:6ecee9a7ee1e0069bcfbc1204f0cd34c9fd07f5284d51b4ca596ceb10125ec84
Reason: One of "sast-unicode-check", "sast-unicode-check-oci-ta" tasks is missing and will be required on 2025-04-01T00:00:00Z
Title: Future required tasks were found
```
N/A
> Konflux: Add sast-shell sast-unicode and sast-coverity checks

- pkg/server/api_server.go
- pkg/server/healthcheck_server.go
- pkg/server/metrics_server.go
- pkg/server/profiler/profiler_server.go
- pkg/server/server.go
Integration tests sometimes fail because they call the api server when it's not yet started. 
Reason: `APIServer.Start()` runs server in a separate goroutine. 
Fix: bind address in the same goroutine, then start the http service asynchronously (as before).
\+ refactor: remove redundant `Service` interface  
```
make ocm/setup
```
> fix(fleet-manager): auth_test flake

- dev/env/scripts/apply
- scripts/ci/multicluster_tests/entrypoint.sh
Fleetshard-sync deployment fails on CI with recent `kubectl` versions.
Caused by: https://github.com/kubernetes/kubernetes/pull/125646. We set null values for `nodeSelector` and `tolerations` in the Fleetshard CR in order to delete the default values in the helm chart.
Fix: Enable server-side apply in dev/CI scripts.
```
make ocm/setup
```
> fix(CI): Enable server-side apply in dev scripts

- fleetshard/pkg/central/reconciler/status.go
- fleetshard/pkg/central/reconciler/status_test.go
- fleetshard/pkg/fleetshardmetrics/metrics.go
- fleetshard/pkg/fleetshardmetrics/metrics_test.go
- fleetshard/pkg/fleetshardmetrics/server_test.go
- fleetshard/pkg/runtime/runtime.go
1. Instead of sending a single status for every central in the same reconcile gouroutine, introduce a new goroutine that waits for all the central reconciliation and sends the aggregated status report to fleet-manager. This keeps the main runtime function nonblocking and reduces the number of HTTP requests sent to fleet-manager
2. Added `status` label to `acs_fleetshard_total_centrals` metric that allows to group total centrals by status. 
- Unit tests
- Manual tests
> ROX-16860: Send aggregated statuses and group the total central metric by status

- fleetshard/pkg/central/reconciler/status.go
- fleetshard/pkg/central/reconciler/status_test.go
- fleetshard/pkg/fleetshardmetrics/metrics.go
- fleetshard/pkg/fleetshardmetrics/metrics_test.go
- fleetshard/pkg/runtime/runtime.go
- Returned back the error counter metric
- Removed misleading central error status (the reconciliation error != central error status)
- Renamed increment methods for better readability
```
make ocm/setup
```
> ROX-16860: Remove misleading central error status from the status counter

- internal/dinosaur/pkg/services/dinosaur.go
Also allow cluster reassignment for tenants in provisioning.
This is needed in case a tenant is stuck in the migration and does not reach ready on the new cluster, to move it back to the original cluster so that it works again.
```
make ocm/setup
```
> ROX-28814: allow assign-cluster in provisioning status

- .secrets.baseline
- e2e/e2e_test.go
- internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
- internal/dinosaur/pkg/api/admin/private/api_default.go
- openapi/fleet-manager-private-admin.yaml
- pkg/client/fleetmanager/client.go
- pkg/client/fleetmanager/mocks/client_moq.go
This PR adds the testing of restore operation to the admin API e2e tests.
Together with #2289 this change will ensure appropriate regression testing of the restore logic for ACSCS tenants.
CI is sufficient
> ROX-28980: add tenant restore operation to e2e tests

- dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
As discussed in acs-cs bi-weekly review
> ROX-29122: remove service account token from cloudwatch exporter

- probe/pkg/central/service.go
Fixing an alert where probe tries to deploy to a disabled region
Context: https://redhat-internal.slack.com/archives/C043EBGTKMJ/p1746614278185969
```
make ocm/setup
```
> fix: have probe ignore disabled regions

- .secrets.baseline
- e2e/e2e_test.go
> fix(e2e): Change TLS termination to passthrough

- dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml
registry.redhat.io/openshift-logging/vector-rhel8 is deprecated and needs to be replaced.
```
make ocm/setup
```
> ROX-28579: use vector-rhel9 image for audit logs

- fleetshard/pkg/central/reconciler/reconciler.go
Once RHSSO dynamic clients will return both `sub` and `deprecated_sub`, it will allow for seamless transition to the new format.
```
make ocm/setup
```
> ROX-15091: Add deprecated_sub claim mapping

- internal/central/pkg/services/quota/ams_quota_service.go
- internal/central/pkg/services/quota/ams_quota_service_test.go
Sometimes in the integration env of AMS subscription may disappear. Which is why sometimes tenants in ACSCS are stuck in a deleting state.
This PR changes the deletion logic to don't cause deletion to fail, but print a info message if a 404 was received when trying to delete the Subscription. It's reasonable to assume the Sub doesn't exists if we receive a 404.
e2e tests and added unit test are sufficient
> ROX-29863: do not block deletion if deleting quota fails with 404

- fleetshard-operator/pkg/controllers/gitopsinstallation_controller.go
This PR solves the following problem: when the reconciler watches `argocd.Application` and the gitops operator is not installed yet on a fresh cluster (CRD is not available), the operator is crashlooping with the following error:
```
E0703 13:02:40.155758 1 kind.go:71] controller-runtime/source/EventHandler: "msg"="if kind is a CRD, it should be installed before calling Start" "error"="failed to get restmapping: no matches for kind \"Application\" in version \"argoproj.io/v1alpha1\"" "kind"="Application.argoproj.io"
```
This PR makes the reconciler stop watching the target objects.
```
make ocm/setup
```
> ROX-29638: Do not watch target objects

- internal/central/pkg/externaldns/externaldns.go
- internal/central/pkg/services/central.go
- internal/central/pkg/workers/centralmgrs/centrals_routes_cname_mgr.go
Skips creation of CNAME records when ExternalDNS is enabled.
```
make ocm/setup
```
> external-dns reconciliation logic

- internal/central/pkg/handlers/data_plane_central.go
- internal/central/pkg/routes/route_loader.go
This PR changes the private API for data planes, so that it returns 404 if the central requests for a cluster ID are empty and the cluster can't be found in the DB.
We deliberately only check for cluster existence after central requests found is 0 because:
- We still want to be able to get centrals assigned to clusters that have been deleted
- We don't want to send additional DB queries for the default case, which is the cluster exists and has centrals assigned
```
make ocm/setup
```
> ROX-13456: return 404 on private cluster if cluster is not found

- fleetshard/pkg/cipher/cipher.go
- fleetshard/pkg/cipher/kms_cipher.go
- fleetshard/pkg/cipher/kms_cipher_test.go
- go.mod
- go.sum
Upgrade the kms package to use `aws-sdk-go-v2` instead of the V1 `aws-sdk-go`
CI is sufficient
```
make ocm/setup
```
> ROX-26792: upgrade KMS to use aws-sdk-go-v2

- dev/env/manifests/external-secrets/application/00-application.yaml
- e2e/e2e_canary_upgrade_test.go
- internal/central/pkg/handlers/central.go
- internal/central/pkg/handlers/validation.go
- internal/central/pkg/handlers/validation_test.go
This change improves error handling across public API endpoints to provide more user-friendly error messages that UIs can display directly to users.
Key improvements:
- Replace regex patterns in central name validation with human-readable text
- Improve cloud provider/region validation error messages with clearer formatting  
- Enhance search parameter validation messages
Before: "name does not match ^[a-z]([-a-z0-9]*[a-z0-9])?$"
After: "name must use lowercase letters, numbers, and hyphens only (max 32 characters)"
This ensures UI teams can display error messages directly without additional processing or translation.
> ROX-12886: improve public API error messages for better UX

- .secrets.baseline
- templates/service-template.yml
Fix missing service-template mapping for the `quota-internal-organisation-ids` parameter
N/A
> Fix missing quota-internal-organisation-ids mapping

- internal/central/pkg/services/addon.go
- internal/central/pkg/services/clusters.go
- internal/central/pkg/services/data_plane_central.go
- internal/central/pkg/workers/clusters_mgr.go
- internal/central/pkg/workers/clusters_mgr_test.go
Changing logs for cluster operations to also include clustername so that it's easier to figure out dataplane issues by just looking at logs.
```
make ocm/setup
```
> ROX-17156: use clustername in logs

- internal/central/pkg/handlers/admin_central.go
- internal/central/pkg/handlers/central.go
- internal/central/pkg/services/central.go
- internal/central/pkg/services/centralservice_moq.go
Users in a RH Org can see all Centrals in their Org, if they try to delete one not owned by them and they are not system or organization admin they currently get 404 errors, which does not make sense since they are allowed to see the central.
This PR changes the code so that it returns 403 in those cases.
```
make ocm/setup
```
> ROX-13466: return unauthorized when deleting central in org but not owned

- .github/renovate.json5
Add configuration for Kofnlux bot PRs
```
make ocm/setup
```
> ROX-31200: Add renovate config for konflux bot
