stackrox/acs-fleet-manager

build_deploy.sh
Set image repository to `app-sre/fleet-manager`. This will simplify Jenkins CI job.
Not needed
=> Set default image repository

build_deploy.sh
Fix log message for #61 
Not needed
=> Fix push log message

dev/env/central-to-ready/TESTING-HOWTO.md, dev/env/central-to-ready/central-status-update-ready.json
=> Update ready transition instructions

Makefile
Using  `--password-stdin` will hide password from history and logs
=> Use --password-stdin for docker login

templates/secrets-template.yml, templates/service-template.yml
RDS provisioner in app-interface [uses a different name](https://coreos.slack.com/archives/C02CMTM9GG1/p1654505197989519?thread_ts=1654500737.953039&cid=C02CMTM9GG1) for the RDS secret than assumed here initially.
None
=> Use correct RDS secret name.

templates/service-template.yml
[Needed](https://coreos.slack.com/archives/C02CMTM9GG1/p1654508959684979?thread_ts=1654500737.953039&cid=C02CMTM9GG1) for pulls to succeed.
=> Use an image pull secret for app-sre/envoyproxy.

templates/service-template.yml
=> Temporarily use a configmap in place of the observatorium secret.

templates/service-template.yml
Same as #96 and #97.
Hopefully the last in the series?
=> Temporarily use a configmap in place of the dataplane cert secret.

config/dinosaur-capacity-config.yaml, internal/dinosaur/pkg/config/dinosaur.go, internal/dinosaur/pkg/services/dinosaur.go
Manually set `maxCapacity` on app start
=> Drop DinosaurCapacityConfigFile

internal/dinosaur/pkg/workers/clusters_mgr.go, pkg/environments/environment.go, pkg/workers/leader_election_mgr.go, pkg/workers/worker_interface.go
Add few more logs for stopping reconciliation
=> Extend logs for stopping

scripts/setup-dev-env.sh
Forgot to push a change into a pull-request.
This PR sets the `set +e` `set -e` on the dev script.
=> Enable `set -e` in dev setup script

fleetshard/pkg/fleetmanager/client.go, fleetshard/pkg/fleetmanager/client_test.go
This PR fixes JSON unmarshalling of empty responses.
- Added unit test
=> Fix json unmarshal on emtpy bodies

fleetshard/README.md
=> Update fleetshard e2e instructions

fleetshard/pkg/centralreconciler/reconciler.go
=> ROX-11440: Fix namespace creation

fleetshard/main.go
=> Remove comment

Makefile
Add make target to build all binaries and generate open API.
- run `make all`
=> Add make all build target

templates/service-template.yml
Mount OSD dataplane cofig file for stage using on appSRE control plane
=> Mount stage dataplane configuration file

templates/service-template.yml
Add volume for staging dataplane configmap and rename its mount
=> Add dataplane cluster config configmap

templates/service-template.yml
Fix indent issue caused by #167
=> Fix volume indent issue in service template

templates/service-template.yml
Add dataplane configmap mapping
=> Add dataplane configmap object mapping

templates/service-template.yml
Use kubeconfig value provided by appSRE vault
=> Mount kubeconfig from the appSRE vault

fleetshard/pkg/centralreconciler/reconciler.go, fleetshard/pkg/centralreconciler/reconciler_test.go
Refactor deletion test to not need multiple attempts, instead collecting results and returning an aggregation.
- CI
=> Refactor deletion test

OWNERS
Add code owners to openshift ci
@mtodor @dhaus67 @ivan-degtiarenko
=> Add code owners

.secrets.baseline
chore: Update the .secrets.baseline file and its line numbers to avoid failing CI.
=> Update .secrets.baseline file.

.secrets.baseline, pkg/client/iam/client.go, pkg/client/iam/client_moq.go, pkg/client/redhatsso/client.go, pkg/client/redhatsso/client_test.go, pkg/services/sso/iam_service_moq.go, pkg/services/sso/redhatsso_service.go, pkg/services/sso/redhatsso_service_test.go, pkg/shared/http.go, test/mocks/redhatsso.go
This PR will port existing unit tests for sso related code (either `pkg/services/sso` or `pkg/client/redhatsso`) as well as existing code which includes fixes.
This shall increase the test coverage of our sso related code as well as help us stay up-to-date with latest changes within kas-fleet-manager.
=> Port unit tests and sso-related code changes from KAS-fleet-manager.

docs/setup-developer-osd-cluster.md, dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml, dp-terraform/helm/rhacs-terraform/values.yaml
This PR introduces a new step-by-step guide to setting up an OSD cluster for development purposes.
- ~[ ] CI and all relevant tests are passing~
The best way to test is to execute all steps. Good luck! 😁
=> ROX-11716: Initial work on step by step guide to setup OSD cluster

.openshift-ci/image-push/entrypoint.sh
=> ROX-11814: Push image to quay

internal/dinosaur/constants/cluster.go
Fix of the leftover from template
=> Fix DNS prefix

docs/development/setup-developer-osd-cluster.md
This PR contains:
- moving document file to the `development` directory within docs
- how to run front-end is added to the guide
To test the guide, please follow the provided steps.
=> Add how to run front-end guide

.openshift-ci/tests/e2e.sh, .secrets.baseline, config/fleetshard-authz-org-ids-development.yaml
This PR will ensure the auth E2E tests will be run in pipeline, specifically within OSCI.
Besides the code changes, the credentials have been added to the vault used by OSCI.
=> ROX-11441: Run auth E2E tests in pipeline.

dev/config/dataplane-cluster-configuration-crc.yaml
Added cluster config for Code Ready Containers (CRC)
```
```
=> added cluster config for local CRC

.openshift-ci/build-root/Dockerfile
This is required for installing git.
```
```
=> Add AppStream repo to CentOS root image

.openshift-ci/build-root/Dockerfile
Collecting a list of test env dependencies. :-/
```
```
=> Centos image: Install jq

dev/env/scripts/bootstrap.sh
Locally I was able to reproduce a bootstrapping issue (on completely fresh Colima & Rancher Desktop clusters) where the operator did not come up because the newly created subscription ended up in a broken state:
```
Conditions:
Last Transition Time:  2022-08-02T10:13:20Z
Message:               all available catalogsources are healthy
Reason:                AllCatalogSourcesHealthy
Status:                False
Type:                  CatalogSourcesUnhealthy
Message:               error using catalog operatorhubio-catalog (in namespace olm): failed to list bundles: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.43.35.218:50051: i/o timeout"
Reason:                ErrorPreventedResolution
Status:                True
Type: …
```
=> Test Env: Add additional wait during setting up of the operator

e2e/e2e_test.go
Noticed an old pending PR from @SimonBaeumer: https://github.com/stackrox/acs-fleet-manager/pull/142
I rebased his work in this PR, which supersedes #142.
```
```
=> Add ticket numbers

OWNERS
Add Vlad 🎉 
... and remove Juan. 😢 
```
```
=> Add Vlad to OWNERS file

e2e/run_e2e_stage.sh
This helps to debug e2e staging vault secret injection on appSRE CI
=> Add debug env print

dev/env/scripts/lib.sh
=> Fix typo in test env for rancher desktop

templates/service-template.yml
=> Fix identation in config map

dp-terraform/helm/rhacs-terraform/README.md
This PR adds instructions on re-terraforming the data plane clusters with additional check steps.
You can follow the added instructions to the README.
=> Add re-terraform steps to README

.github/workflows/pre-commit.yaml, .pre-commit-config.yaml, scripts/generated-files-uptodate.sh
=> Include pre-commit hook for verifying that generated files are up-to-date

README.md
This PR adds the following badge to README.md: ![Dinosaur counter](https://dinosaurs.rhacs-dev.com/)
```
```
=> Add dinosaur counter badge to README.md

dp-terraform/add-on/rhacs-terraform/go.mod, dp-terraform/add-on/rhacs-terraform/go.sum
This PR updates containerd dependency to fix the vulnerability 
```
```
=> Update containerd dependency [dependabot]

templates/service-template.yml
This command will drop all schemas.
This is a temporary change to pristine stage RDS. Stage DP clusters were recreated so we should clean stage DB as well.
=> TEMPORARY Add rollback command to drop stage RDS

.github/pull_request_template.md
Add security checklist item to pull request template
=> Add security checklist item to pull request template

dev/env/scripts/bootstrap.sh
=> Don't forget to capture output of kubectl sanity check

dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
This allows us to set the Grafana image version explicitly (among other improvements).
Tested deployment of this operator version on staging system.
```
```
=> Update observability operator to v3.0.14

templates/service-template.yml
Reverts stackrox/acs-fleet-manager#294
=> Revert "TEMPORARY Add rollback command to drop stage RDS"

internal/dinosaur/pkg/workers/clusters_mgr.go
Follow-up PR to https://github.com/stackrox/acs-fleet-manager/pull/317.
Instead of only supporting updating the `cluster_dns` setting this PR implements support for updating most of the configuration fields for manually scaled data-plane clusters.
```
```
=> Allow updating manual cluster configuration in fleet-manager's DB

templates/service-template.yml
Change stage app interface configuration to use external DNS and certs.
```
```
=> enable external dns and tls for appinterface template

go.mod, go.sum, pkg/client/redhatsso/client.go, test/mocks/redhatsso.go
This fixes build issues in #319 opened by dependabot
```
```
=> Bump github.com/redhat-developer/app-services-sdk-go/serviceaccounts from 0.4.0 to 0.5.0

docs/development/test-locally-route-hosts.md
This PR adds some blank lines for better readability.
=> Add line breaks in Markdown files

.github/workflows/pre-commit.yaml, docs/architecture/README.md, internal/dinosaur/pkg/config/central.go, internal/dinosaur/pkg/presenters/managedcentral.go
Seems like the workflow that executes the action has been broken for quite some time (i.e. its running, but the hooks will be skipped).
https://github.com/stackrox/acs-fleet-manager/commit/3776f169f22dd19bc4729bdaf76776d5835afa82 seems to have introduced this behavior.
I've reverted back the changes for now, fixed the issues that are already on main and have not been addressed, and will create a follow-up to ensure the local hook is executed within pipeline.
=> Fix pre-commit workflow

.secrets.baseline, Makefile, templates/service-template.yml
Symmetric to https://github.com/stackrox/acs-fleet-manager/pull/382 changes, but with `central-idp-issuer` value. Do not merge until values are added to `app-interface`
--
=> Configure central-idp-issuer as env variable

templates/service-template.yml
=> Rollback database

templates/service-template.yml
Rollback database rollback
- CI
=> Rollback database rollback

internal/dinosaur/pkg/api/admin/private/api/openapi.yaml, internal/dinosaur/pkg/api/admin/private/api_default.go
Run `make generate` to update generate files.
- CI
=> Run make generate

dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml, fleetshard/pkg/central/reconciler/reconciler.go
This PR adds the git commit SHA to the fleetshard-sync deployment.
- Manual testing
=> Add git commit sha and tag to fleetshard-sync deployment

dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/test.sh
This pull requests updates the trigger for the deployment YAML to be accepted.
- helm template
=> Fix deployment trigger annotation

dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml, internal/dinosaur/pkg/api/dbapi/central_spec.go, internal/dinosaur/pkg/defaults/default_central_spec.go, internal/dinosaur/pkg/defaults/default_scanner_spec.go, internal/dinosaur/pkg/defaults/parsers.go, internal/dinosaur/pkg/defaults/pretty_printer.go, internal/dinosaur/pkg/presenters/managedcentral.go, pkg/environments/environment.go
Rework resource defaulting: Instead of hard-coding the resource defaults, make them overwritable using environment variables.
Use the env package for unmarshalling directly into a corresponding struct.
Change the fleet-manager deployment in the test environment so that slimmer central tenants are created by default.
+ Some pre-commit fixes.
```
```
=> ROX-12394: Configurable Tenant Defaults

dev/env/scripts/up.sh
Update previously forgotten occurrence of the old `yq` invocation style.
```
```
=> Use new yq invocation style

dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml, dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
- Move from prod-01 to prod-04
- add prod namespace
- bump plugin
=> ROX-12811: Grafana change datasource to prod-04 cluster and add a prod namespace

internal/dinosaur/pkg/presenters/dinosaur.go
See https://issues.redhat.com/browse/ROX-12829
```
```
=> ROX-12829: Fix Central Data URL

e2e/dns/records_loader.go, e2e/e2e_test.go, fleetshard/pkg/k8s/route.go
This PR fixes CI failures introduced in #445
- ~[ ] Documentation added if necessary~
CI Green
```
```
=> Fix E2E tests

templates/service-template.yml
=> Use Vault secret files for OCM credentials

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump the version of fleet sync used on stage to check the latest changes.
~~- [ ] Documentation added if necessary~~
Command run for updating:
```
./terraform_cluster.sh stage acs-stage-dp-01
```
=> Bump stage fleet shard sync version

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This removes the token refresh proxy.
Deployed this image to staging, created a Central and waited for it to become ready.
=> Update fleetshard-sync on prod env

e2e/loadtest/README.md, e2e/loadtest/docker-compose.yml, e2e/loadtest/locustfile.py
Add instruction how we run loadtest. It is necessary for appSRE onboarding
=> Add load test instructions

Makefile
Just a quality-of-live improvement.
Use case: When deploying to e.g. Infra the Fleet* image needs to be available on Quay. So one could use existing Makefile targets for building the image, retagging manually and pushing to Quay.
With this PR one can simply do:
```
$ IMAGE_REGISTRY=quay.io NAMESPACE=mclasmei make image/push 
GOOS="linux" GOARCH="amd64" go build  ./cmd/fleet-manager
GOOS="linux" GOARCH="amd64" go build  -o fleetshard-sync ./fleetshard
DOCKER_CONFIG="/Users/moritz/go/src/github.com/stackrox/acs-fleet-manager/.docker" docker build -t "quay.io/mclasmei/fleet-manager:v0.0.0-327-g69413248f7" .
[+] Building 21.9s (7/7) FINISHED …
```
=> QoL Improvement: Support configurable image refs in Makefile for building and pushing of images

fleetshard/pkg/central/reconciler/init_auth.go
Prior to this patch, if any group creation fails for whatever reason, fleetshard sync gives up and returns an error.
With this PR, fleetshard sync attempts to create all configured groups regardless of previous failures. If any attempt fails, an error is logged and returned from the reconciler.
Inspired by [ROX-12836](https://issues.redhat.com/browse/ROX-12836).
CI run.
=> Keep adding groups regardless of failures

dev/env/defaults/cluster-type-infra-openshift/00-openshift.env, dev/env/defaults/cluster-type-infra-openshift/env
Reduces configuration duplication and is more consistent with the rest.
```
```
=> Simplify deployment setup for infra openshift

docs/architecture/README.md
Add link to the load testing document
=> Add load testing document link

templates/service-template.yml
Fix an issue introduces in #456 
Local dry run `oc apply`
=> Fix labelSelector formatting

templates/service-template.yml
Another attempt to fix an issue introduces in https://github.com/stackrox/acs-fleet-manager/pull/456
Local dry run `oc apply`
=> Fix label selector

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
=> ROX-13017: Deploy a static version of observability resources to prod.

docs/architecture/README.md
- Adjust architecture document according to AppSRE requirements. Add `Service Description`, `Components`, `Routes`, `Dependencies`, `Service Diagram`, `Application Success Criteria`, `State`, `Load Testing` and `Capacity` sections.
- Add backup policy description with the link to the app-interface
- format document
No need to
=> ROX-10240: Reformat architecture document and add Backup Policy

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update fleetshard-sync to new version to test SSO on stage.
~- [ ] Documentation added if necessary~
```
```
=> bump fleetshard-sync version to fix sso

pkg/client/ocm/client.go
During triaging of https://redhat.pagerduty.com/incidents/Q07LCETZ3AASFY we figured out that the error from AMS is swallowed. Let's bring it to light.
CI run.
=> Add some logs to shed light on AMS failures.

Makefile, dev/env/defaults/00-defaults.env, dev/env/scripts/bootstrap.sh, dev/env/scripts/down.sh, dev/env/scripts/lib.sh, dev/env/scripts/reset, dev/env/scripts/up.sh, e2e/e2e_auth_test.go, e2e/e2e_suite_test.go, e2e/e2e_test.go
While debugging an e2e test failure I noticed several shortcomings. This PR does a lot of polishing related to diagnostics and ergonomics, feedback cycle improvements, etc.
https://issues.redhat.com/browse/ROX-13144
```
```
=> ROX-13144: Improve e2e diagnostics and ergonomics

pkg/client/ocm/client.go
The log statement was added for debugging purposes during the initial AMS integration.
```
```
=> Remove debug log statement

dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
To unbreak existing dev environments depending on static tokens, before we move to external configuration entirely.
```
```
=> Test Env: Support static Token

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump fleet shard sync version in the upgrade script
=> Bump fleet shard sync version

.github/pull_request_template.md, CHANGELOG.md
This PR introduces a CHANGELOG.md template inspired by the CHANGELOG.md of https://github.com/stackrox/stackrox. It also adds a checkbox to the PR template of this repo to make sure CHANGELOG.md is updated on each PR. This should help us to know what changes were made since the last release and if we need to take specific steps in order to release a new version of the ACS Cloud Service successfully.
~- [ ] Discussed security and business related topics privately. Will move any …
=> ROX-13290: introduce CHANGELOG.md

Makefile
=> Build for machine architecture instead of amd64

.github/workflows/deploy-qa.yaml
This is the preliminary PR for testing the authentication on QA env.
It just calls `chamber` and lists the available services.
The result proves that AWS authentication works correctly.
QA environment was also introduced as part of this change. 
~- [] Evaluated and added CHANGELOG.md entry if required~
1. Added feature branch to the action trigger branch list (`on.push.branches`)
2. Changed the environment to `porridge-test`
3. Verified the output.
```
```
=> ROX-13220: Test Github OIDC provider on AWS 

.github/workflows/deploy-stage.yaml
Renaming QA environment to stage since there are a lot of `stage` occurrences in our codebase and `QA` may cause a confusion
Configuration changes, can't be tested before merge
```
```
=> Rename QA environment to stage

dev/env/manifests/crds/01-platform.stackrox.io_centrals.yaml, dev/env/manifests/crds/02-platform.stackrox.io_securedclusters.yaml
External managed DBs will require the latest versions of the CRDs. This PR syncs the CRDs with the latest version from the Stackrox repo.
-~~ [ ] Documentation added if necessary (i.e. changes to dev setup, test execution, ...)~~
```
```
=> ROX-13004: Sync CRDs with the stackrox repo

.github/workflows/deploy-stage.yaml
The script is already [tested in a previous PR](https://github.com/stackrox/acs-fleet-manager/pull/505), but no good way to test the integration before the actual push.
=> ROX-12480: run terraform script from a github action

Dockerfile
This PR fixes the build in app-interface by using standard UBI images from quay.
Tested locally. But it should be tested on the app interface after merge.
=> Fix app-interface docker build

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump fleet-manager image version for the DP terraforming
Configuration change - no tests done
=> Bump fleet-manager image version for the DP terraforming

.github/dependabot.yaml
Add image in probe directory to dependabot config.
=> Add probe directory to depenabot config

.github/workflows/ci.yaml, build_deploy.sh
Typo in ci action :(. Currently breaks the CI on main.
=> fix quay user typo in ci action

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Simplify the script and elliminate the need to update it with every new cluster creation.
Ran the script with `echo` prepended to the `helm` invocation to make sure it runs and fails as expected.
=> Simplify the script a little.

internal/dinosaur/pkg/handlers/data_plane_dinosaur.go, internal/dinosaur/pkg/routes/route_loader.go, internal/dinosaur/pkg/services/data_plane_dinosaur.go, internal/dinosaur/providers.go
Decrease dinosaur count one piece at a time.
The approach is to focus on renaming methods and parameter names within one file. That will allow to avoid big merge conflicts, as well as to iterate on the review quickly.
```
```
=> Remove dinosaur references in data_plane_dinosaur.go

dp-terraform/helm/rhacs-terraform/charts/observability/README.md, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update the observability resources reference to https://github.com/stackrox/rhacs-observability-resources/commit/b864d5f155b5455bba78eb7b82bc4bf4190852c7. The diff to the current deployed version adds dashboard improvements and a probe service alert.
Revision is already deployed to staging.
=> update observability resources to b864d5f

build_deploy.sh
Can be removed once https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/52332/diffs is merged
```
[mowsiany@mowsiany acs-fleet-manager]$ ./build_deploy.sh help
The quay.io push user name hasn't been provided.
Make sure to set the QUAY_USER environment variable.
```
=> ROX-13607: Temporary transitional script.

.github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml
Basically the same as the stage file, with `stage` replaced with `production` or `prod` as appropriate.
Note this will be inactive until we create a production environment and branch in GitHub.
No good way to test this beforehand. The stage one works, FWIW.
=> ROX-12480: Add a deploy workflow file for production.

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
=> bump fleetshard-sync image for stage environment

dp-terraform/helm/rhacs-terraform/check_image_exists.sh, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Approach stolen from [the stackrox repo](https://github.com/stackrox/stackrox/blob/8c9ebc89ea81029fdfb613eaeef866bfaef0e9e5/scripts/ci/lib.sh#L552-L570).
Ran the new script manually with existing and absent tag.
Relying on the CD push to verify the rest.
=> ROX-13450: Wait for docker image to appear before terraforming.

deploy/helm/probe/deploy.sh
`CLUSTER_URL_INFIX` env var was removed from the Parameter Store.
```
```
=> Fix probe deployment

pkg/client/redhatsso/dynamicclients/client.go
=> ROX-13408: Comment to clarify usage of api.iam.acs/api.iam.clients scope

dev/env/defaults/00-defaults.env, dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
=> Bump stackrox version to 3.73.0

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Uncomment the related section and add quay read only user token on condition
```
```
=> Add quay user token when installing Operator from the upstream

.github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml, .openshift-ci/e2e-runtime/docker_run_e2e.sh
$USE_AWS_VAULT was replaced with $AWS_AUTH_HELPER a while ago but some uses remained.
None, relying on CI.
=> ROX-13396: Replace remaining occurrences of USE_AWS_VAULT.

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
It didn't work during release, hence rolling back.
```
```
=> Rollback automatic tag resolution on prod

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
=> Rollback automatic tag resolution on prod (#645)

CHANGELOG.md, dp-terraform/helm/rhacs-terraform/Chart.yaml, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml
This PR adds Managed DB specific parameters and enables them for Staging.
```
export HELM_PRINT_ONLY=true
./dp-terraform/helm/rhacs-terraform/terraform_cluster.sh stage acs-stage-dp-02
./dp-terraform/helm/rhacs-terraform/terraform_cluster.sh prod acs-prod-dp-01
```
=> ROX-13756: Add managed DB parameters to the Helm chart

dp-terraform/helm/rhacs-terraform/Chart.yaml, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml
Add AWS_ROLE_ARN parameter to the Helm chart
```
```
=> Add AWS role arn parameter to the Helm chart

.github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml
This will cause to wait for any in-progress rollout to complete (which I think is better than canceling it mid-way) but cancel any other pending workflow.
See [docs](https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions#using-concurrency) for more info.
N/A.
=> ROX-13737: Use built-in concurrency control.

.github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml
=> ROX-13737: remove stale dependencies

CHANGELOG.md
Prepare CHANGELOG for the next relese
N/A
=> Prepare CHANGELOG for the next release

dev/env/scripts/bootstrap.sh
=> Increase operator container wait timeout on Openshift CI

.openshift-ci/e2e-runtime/Dockerfile
=> Fix dnf metadata download errors on Openshift CI

internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go, pkg/client/aws/client.go
Debugging incident-acscs-dec-18.
=> Fix: avoid panic on nil pointer

README.md, docs/architecture/README.md
See https://github.com/stackrox/acs-fleet-manager/pull/346
I also updated the jenkins icon and link in toplevel README.
N/A
=> ROX-11993: Followup from review.

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
We want to start testing phone home telemetry on stage environment. This updates the Central version to one which includes telemetry changes.
```
```
=> Update ACS operator to a Central version that includes Telemetry

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update stage environment to include latest Central version. In particular, we want to test the telemetry feature, which requires a fix not included in the currently deployed version (see https://github.com/stackrox/stackrox/pull/4245).
=> Bump stage Central version to nightly-2023-01-09 build

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump the stage Central version to include a fix for the Telemetry service (see https://github.com/stackrox/stackrox/pull/4332).
=> Bump stage Central version to nightly-2023-01-10 build

dev/env/defaults/00-defaults.env, dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
=> Bump operator to 3.73.1 in test environment

CHANGELOG.md
=> Update changelog for the 2023-01-17.1.f4e71a7 release

Makefile, internal/dinosaur/pkg/api/dbapi/central_request_types.go, internal/dinosaur/pkg/api/private/api/openapi.yaml, internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go, internal/dinosaur/pkg/handlers/cloud_accounts.go, internal/dinosaur/pkg/handlers/cloud_accounts_test.go, internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go, internal/dinosaur/pkg/migrations/migrations.go, internal/dinosaur/pkg/presenters/managedcentral.go, internal/dinosaur/pkg/services/dinosaur.go, internal/dinosaur/pkg/services/quota/ams_quota_service.go, internal/dinosaur/pkg/services/quota/ams_quota_service_test.go, openapi/fleet-manager-private.yaml, pkg/client/ocm/client.go, pkg/client/ocm/client_moq.go, pkg/errors/errors.go, templates/service-template.yml
Reverts stackrox/acs-fleet-manager#736
=> Revert "Revert "ROX-12344: Add organisation name to central request""

internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
This makes the org name migration more robust, in particular when run in dev environments.
* Don't try to parse ocm files if mock is enabled.
* Check for presence of column before attempting to create/delete it, to make the migration idempotent if an error occurs.
* Only build ocm client if records actually need to be migrated.
Error scenarios that might occur during migrations, like missing credentials.
=> Make org name migration more robust

internal/dinosaur/pkg/api/dbapi/central_request_types.go
Part of the effort to improve documentation of Central Request started by @SimonBaeumer here:
https://github.com/stackrox/acs-fleet-manager/pull/743
-~~ [ ] Unit and integration tests added~~
CI is enough
=> Add documentation to AuthConfig fields.

.github/workflows/rds.yaml, dev/env/scripts/exec_fleetshard_sync.sh, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, fleetshard/README.md
Switch managed DB params from application specific to cluster specific
```
export HELM_PRINT_ONLY=true
./terraform_cluster.sh stage acs-stage-dp-02
```
=> ROX-14522: Switch managed DB params from application specific to cluster specific

Makefile, README.md
Add Makefile targets to build binaries and images faster. Increase feedback cycle.
Run Makefile targets and see image gets re-deployed.
=> Add dev build and deploy Make targets

Makefile
=> Add namespace to kubectl calls

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update the Central version to include the latest telemetry features. In particular, we want to test the Central UI telemetry.
=> Update ACS operator to include latest telemetry features

fleetshard/pkg/central/cloudprovider/awsclient/rds.go
This PR changes the CA certificate type of provisioned RDS DBs.
CI is sufficient.
=> ROX-13913: change RDS CA certificate type

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Update to latest Central nightly. This includes more Telemetry fixes to make the events more robust.
=> stage central: v3.73.0-nightly-20230203 -> v3.74.0-nightly-20230213

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
No impact on `main` branch.
This needs to be cherry picked onto the release branch once merged to `master`.
=> Use the same operator version in prod as stage.

Makefile
A [recent MR](https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/59262) added support for building `production` branch images.
However we need another commit to trigger the build and push, since the GHA pipeline is currently ignoring merge commits (and the tip of the production branch is a merge commit right now).
None needed.
=> ROX-14540: Dummy change to force building a new image.

.github/workflows/ci.yaml, .github/workflows/probe.yaml
This is a cherrypick of #840 that actually makes probe build work for the `production` branch.
N/A
=> Build and push probe separately, and on production branch too. (#840)

fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
This PR introduces 2 changes:
* end test when DB cluster status is "deleting", which stops the test earlier and so reduces the chance of test failure if the context expires
* make sure that AWS resources are cleaned up in case of test failure 
CI only
=> Fix RDS tests CI flake

Makefile
This is a cherrypick of #839 to keep main and production as similar as possible and avoid conflicts in the future.
None needed.
=> ROX-14540: Cherrypick a dummy `production` change onto `main`

deploy/helm/probe/deploy.sh
otherwise they are interpreted as named args
=> unquote the optional debug flags in probe deployment

go.mod, go.sum, internal/dinosaur/pkg/services/telemetry.go, pkg/client/telemetry/config.go, pkg/client/telemetry/telemeter_moq.go
* Bump the `stackrox/stackrox` revision;
* Update the use of the `Group` method;
* Set the max batch size to 1 to ensure Group and Track go in different batches.
```
```
=> Telemetry: set max batch size to 1

dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Reverts stackrox/acs-fleet-manager#886
=> Revert "Set ACS Operator CPU request and limit to 2"

dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
This PR updates requests and limits for the operator containers.
Note that due to how OLM behaves this will modify the limits for _both_ the `manager` container (the one we actually want to modify) and `kube-rbac-proxy` (and therefore over provisioning the latter).
These new values will override the default ones (not visible in this PR), which are currently the following:
```yaml
- name: manager
resources:
limits:
cpu: 200m
memory: 1Gi
requests:
cpu: 100m
memory: 200Mi
- name: kube-rbac-proxy
resources:
limits:
cpu: 500m
memory: 128Mi
requests:
cpu: 5m
memory: 64Mi
```
~~- [ ] CI and all relevant tests …
=> ROX-15922: update operator requests and limits

dp-terraform/osd-cluster-idp-setup.sh
The `osd-cluster-idp-setup.sh` script now unifies the logic of identity providers setup for stage and prod data plane clusters.
The credentials for the new prod IDP client are stored in BitWarden.
Tested the script on stage.
=> ROX-13952: Setup OIDC provider for the prod data plane cluster

fleetshard/pkg/central/reconciler/reconciler.go
Add organisation name as label to namespace and Central CR for easier selections.
- CI
=> Add org name as label to namespace and Central CR

fleetshard/pkg/central/reconciler/reconciler.go
Fleetshard-sync tries to create central and centrals namespace with the ocm org name as a label. The ocm org name sometimes does not match the regexp defined for kubernetes label values, thus we have to use an annotations instead. This PR should fix the current issue with creating centrals in ACSCS stage environment.
```
```
=> use annotation for org name instead of label

deploy/helm/probe/deploy.sh
=> use HEAD as tag for probe image

.github/workflows/ci.yaml, .github/workflows/pre-commit.yaml, .github/workflows/rds.yaml
This PR includes the following changes:
- Use a dummy password for postgres in CI
- Run RDS tests only on the main branch (access to AWS should remain restricted)
- Remove the obsolete `release` branch (just a clean up)
```
```
=> ROX-16355: Fix github action issues for contributors

deploy/helm/probe/deploy.sh
* Cherry-pick #931 to fix probe deployment on prod.
=> Bugfix-release 2023-04-04.3.2d936a1

docs/development/secret-management.md, fleetshard/README.md
=> Help future generations with BitWarden CLI errors.

.github/workflows/deploy-stage.yaml
Adds acs-stage-eu-02 terraforming to the CD pipeline.
No manual testing performed.
=> ROX-16280: Terraform acs-stage-eu-02 on CI

dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Forgot to migrate one of the availability panels in #949.
=> use new SLI recording rule also in history panel

.github/workflows/deploy-data-plane.yaml, .github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml, deploy/helm/probe/deploy.sh, deploy/helm/probe/templates/01-operator-04-deployment.yaml, deploy/helm/probe/values.yaml
Additional probes are deployed to EU data plane clusters. As a result, each region will run a dedicated probe, which requests Central instances from its region.
```
```
=> ROX-15354: deploy probe service to EU data plane clusters

.github/workflows/deploy-data-plane.yaml, .github/workflows/deploy-dev.yaml, .github/workflows/deploy-production.yaml, .github/workflows/deploy-stage.yaml
=> ROX-15354: fix probe deployment to multiple US/EU clusters

cmd/fleet-manager/main.go
Remove unsupported CLI commands
- build fleet-manager
- run CI
=> Remove unsupported CLI commands

probe/pkg/probe/probe.go
Add logging of the HTTP response body in case of errors to the probe service.
Previously, if an error occurred, we only saw the HTTP status code within the log message:
```log
5536 probe.go:195] central instance id-42 not reachable: : 500
```
While this may hint to a problem, we can also add the HTTP response body and the error code + reason to the log statement, thus making triaging issues a bit easier.
```
```
=> Add response logging to probe service

pkg/environments/environment.go
Remove development environment log message to make the CLI output clean.
- CI
=> Remove development environment log message

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Bump ACS Operator to 4.0.0 upstream version
No need to. It will be tested against stage env
=> Bump operator to v4.0.0 on stage

dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
that the latest channel is deprecated and is not updated after RHACS version 3.74. Newer versions are published to the stable channel.
=> Use stable subscription channel

dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Reverts stackrox/acs-fleet-manager#982
=> Revert "Use stable subscription channel"

dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Follow up of #948 . Now for prod.
=> update prod observability operator to v4.2.1

dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-05-subscription.yaml, dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Bumped up resources for the observability operator
=> ROX-16769 add resources for observability operator

.github/workflows/rds.yaml, Makefile, fleetshard/pkg/central/cloudprovider/awsclient/rds.go, fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
This reverts commit 06e11f6d4e0c6ec0589f3d16146ee0804322b4f0.
```
```
=> Revert "ROX-13692: create final snapshot for tenant db (#994)"

.github/pull_request_template.md
Add additional checks to the PR template, to help catch problems with AWS resource provisioning.
```
```
=> add AWS pr checks

fleetshard/pkg/central/cloudprovider/awsclient/rds.go
The check `if clusterStatus != dbDeletingStatus && clusterStatus != dbBackingUpStatus` was written with the assumption that the `dbBackingUpStatus` would be `true` due to the final DB backup being in progress. However, it can randomly happen that this is `true` due to an automatic backup started by AWS exactly when we try to delete an instance. This happens with Probe service every week or so (see the Jira ticket for more).
By removing this condition, we'll have the side-effect of requesting the DB deletion to AWS several times, until the snapshot is taken:
```
I0612 20:06:11.225715       1 reconciler.go:123] Start reconcile central rhacs-ci3nf33dabr001r63lu0/test-central-1
I0612 20:06:11.246662       1 reconciler.go:768] Marking Central CR rhacs-ci3nf33dabr001r63lu0/test-central-1 for …
```
=> ROX-17690: Fix cluster deletion when auto-backup is in progress

dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
AWS_REGION is needed to initialize the RDS client.
Tested locally with: 
```
INSTALL_OPERATOR=NO MANAGED_DB_ENABLED=TRUE make deploy/dev
```
```
```
=> Fix local dev env with managed DB enabled

fleetshard/pkg/central/reconciler/reconciler.go
=> Prefactor: extract auth provider reconciliation to dedicated function in fleetshard central reconciler

dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml
This PR should fix the Downstream operator channel.
We had some changes with the channel introduced with version 4.0:
`latest` - will stay on `3.74`
`stable` - will be used for new `4.x` versions
- ~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
- ~[ ] Add secret to app-interface Vault or Secrets Manager if necessary~
- ~[ ] RDS changes were e2e tested [manually](../docs/development/howto-e2e-test-rds.md)~
- ~[ ] Check …
=> Fix downstream operator channel

fleetshard/pkg/central/operator/upgrade.go, fleetshard/pkg/fleetshardmetrics/metrics.go, fleetshard/pkg/runtime/runtime.go
Add metrics to report operator health status based on number of deployment ready replicas
```
make deploy/dev-fast
```
=> ROX-17797: Add metric for operator health status

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This PR should fix CI on the `main` branch.
With PR: https://github.com/stackrox/acs-fleet-manager/pull/1038 - we have added the use of a secret that does not exist in AWS. This PR removes using of this secret.
- ~[ ] Add the ticket number to the PR title if available, i.e. `ROX-12345: ...`~
- ~[ ] Add secret to app-interface Vault or Secrets Manager if necessary~
- ~[ ] RDS changes were e2e tested …
=> Remove using of non existing secret

dp-terraform/helm/rhacs-terraform/templates/_helpers.tpl
This fix stage deployment
```
HELM_DRY_RUN=true HELM_DEBUG=true AWS_SAML_ROLE=<stage user> ./terraform_cluster.sh stage <stage_cluster>
```
=> ROX-17723: Fix imagePullSecret value source

dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-namespace.yaml
Add a dedicated namespace for the secured cluster. Fixes stage deployment
```
HELM_DRY_RUN=true HELM_DEBUG=true AWS_SAML_ROLE=stage_user ./terraform_cluster.sh stage stage_cluster
```
=> ROX-18445: Create a namespace for secured cluster

Dockerfile, probe/Dockerfile
Run FM, FSS and Probe as non-root user
```
Check that containers run normally
```
=> Use unprivileged user in Dockerfile

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
ACS dogfooding secured cluster is ready to be deployed on every env
=> ROX-15791: Enable secured cluster by default

templates/service-template.yml
Add recommended security headers to Fleet Manger envoy config
Most important:
- HTTP Strict Transport Security (HSTS)
- Content-Security-Policy
See: https://wiki.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers 
~~- [ ] RDS changes were e2e tested …
=> Enforce security headers in Fleet Manager API

templates/service-template.yml
FM envoy envoy sidecar uses old version and response headers handler should use different extension
Validate config via online tool against version which is used by FM sidecar
=> Fix envoy response headers FM

dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/values.yaml
=> Make SkipTLSVerify helm-configurable for the audit log notifier

dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml, dp-terraform/helm/rhacs-terraform/Chart.lock, dp-terraform/helm/rhacs-terraform/charts/audit-logs/.helmignore, dp-terraform/helm/rhacs-terraform/charts/audit-logs/Chart.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/README.md, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/01-namespace.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/02-configmap.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/03-secret.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/04-serviceaccount.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/05-service.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/06-statefulset.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/_helpers.tpl, dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml
Demo PR for https://issues.redhat.com/browse/ROX-18593
=> Emergency frobnicator fixes

fleetshard/pkg/central/reconciler/reconciler.go
Creating a cherry-pick release [based on the comment here](https://issues.redhat.com/browse/ROX-18593?focusedId=22701366&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22701366).
```
```
=> Release 2023-08-16.1.26e46dd

.github/workflows/deploy-integration.yaml, deploy/helm/probe/deploy.sh, docs/development/setup-osd-cluster-idp.md, dp-terraform/cd-robot-account-setup.sh, dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/terraform_cluster.sh, dp-terraform/helm/rhacs-terraform/values.yaml, dp-terraform/osd-cluster-idp-setup.sh, fleetshard/config/config.go, fleetshard/pkg/central/reconciler/reconciler.go, fleetshard/pkg/central/reconciler/reconciler_test.go, fleetshard/pkg/cipher/cipher.go, fleetshard/pkg/cipher/local_base64_cipher.go, fleetshard/pkg/cipher/local_base64_cipher_test.go, fleetshard/pkg/k8s/route.go, fleetshard/pkg/k8s/secret.go, fleetshard/pkg/runtime/runtime.go, internal/dinosaur/pkg/api/dbapi/central_request_types.go, internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go, internal/dinosaur/pkg/api/private/api/openapi.yaml, internal/dinosaur/pkg/api/private/model_data_plane_central_status.go, internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go, internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go, internal/dinosaur/pkg/migrations/migrations.go, internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go, internal/dinosaur/pkg/presenters/managedcentral.go, internal/dinosaur/pkg/services/data_plane_dinosaur.go, internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go, openapi/fleet-manager-private.yaml
=> Release 2023-08-29.1.63189b2

dev/env/scripts/lib.sh, dev/env/scripts/up.sh, e2e/e2e_auth_test.go, e2e/e2e_test.go, fleetshard/config/config.go, fleetshard/main.go, fleetshard/pkg/runtime/runtime.go, internal/dinosaur/pkg/cmd/admin/centrals/list.go, internal/dinosaur/pkg/cmd/centrals/create.go, internal/dinosaur/pkg/cmd/centrals/delete.go, internal/dinosaur/pkg/cmd/centrals/get.go, internal/dinosaur/pkg/cmd/centrals/list.go, internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go, pkg/client/fleetmanager/auth.go, pkg/client/fleetmanager/auth_ocm.go, pkg/client/fleetmanager/auth_rhsso.go, pkg/client/fleetmanager/auth_static_token.go, probe/cmd/probe/main.go, probe/internal/cli/cli.go, probe/pkg/fleetmanager/client.go, scripts/lib/log.sh
Hopefully this will help us catch the culprit that causes timeouts described in the ticket.
I also added:
- a few info statements for a good measure
- timestamps to the e2e script messages
Ci should be sufficient.
=> ROX-19494: Bump wait time and provide context for initialization.

probe/pkg/probe/probe.go, probe/pkg/runtime/runtime.go
Couple of small fixes for the probe logging.
=> fix(probe): improve probe logging

dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml, dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
=> ROX-16085: Support integration env in grafana dashboard.

Makefile
Remove image/build/local target because it is not used
=> Remove unsued  `image/build/local` Makefile target

docs/architecture/images/egress_diagram.md, fleetshard/pkg/central/charts/data/values.yaml
Add egress diagram to docs
```
```
=> Add egress diagram to docs

build_push_probe.sh
=> Fix probe build env vars

build_push_probe.sh
Fix probe build sourcing the script
=> Fix probe build sourcing the script - round 3

internal/dinosaur/pkg/gitops/provider.go, internal/dinosaur/pkg/gitops/provider_test.go, pkg/metrics/metrics.go
=> ROX-19480: Add GitOps provider alert

dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Make creating latency chart to gather data for the currently selected time range so data is not reset after each deployment.
~~- [ ] Add secret to app-interface Vault or Secrets Manager if necessary~~~
Tested on stage grafana (see picture above)
=> ROX=19699: Combine data for creating latency SLO chart

dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml, dev/env/manifests/fleet-manager/03-fleet-manager-service.yaml, pkg/metrics/metrics.go
Fixed absence of prometheus gitops error counter
=> ROX-19480: Fix GitOps provider alert

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
This is so that we can control which observability artifacts changes go into the stage environment, similar to all other repos.
N/A
=> ROX-19725: Push observability stage branch to stage env

.github/workflows/deploy-stage.yaml
=> ROX-19690: Push to stage environment from stage branch, not main

.github/workflows/create-prod-pr.yaml
Once we push to stage, the chances are high we will want to merge `stage` to production. This workflow will prepare a PR to do so automatically.
Works [fine in my clone](https://github.com/porridge/acs-fleet-manager/pull/10).
=> ROX-19692: New workflow to auto-create production merge PRs.

internal/dinosaur/pkg/services/quota/ams_quota_service.go, pkg/client/ocm/client.go, pkg/client/ocm/client_moq.go
Log result of `current_account` call execution so that we can be sure the call is actually happening
1. CI is sufficient
=> Log result of current_account call execution

probe/pkg/probe/probe.go
I think having these messages would have made my life a bit easier when troubleshooting probe on the then-not-quite-ready integration environment.
Build and CI should be sufficient.
=> Add a few messages about probe progress.

Makefile
Load image into kind automatically. Accidentially deleted it.
- Restore changes.
=> Load image into kind automatically

Makefile
We no longer use this target in the release process.
CI is sufficient.
=> ROX-19841: Remove unused target

docs/development/setup-test-environment.md
=> Fix path typo in e2e documentation

fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
Fixing invalid egress-proxy manifest
=> ROX-20147: Fix invalid egress-proxy manifest

dp-terraform/ocm/install_addon.sh
Add addon version and fleetshardImageTag parameter
```
```
=> ROX-19904: Add addon version and fleetshardImageTag parameter

OWNERS
Moritz' GitHub handle has changed...
=> Update GitHub handle in OWNERS file

.openshift-ci/tests/e2e.sh
=> Fix precommit for flag fitops

.github/workflows/create-prod-pr.yaml, .github/workflows/start-release.yaml
This way the checks on PRs should trigger automatically.
Not really testable before merge :-/
=> ROX-19846: Use roxbot account to create PRs.

internal/dinosaur/pkg/gitops/config.go, internal/dinosaur/pkg/gitops/config_test.go, internal/dinosaur/pkg/gitops/service.go
Add better validation for central patches
=> Validate central patch better

e2e/e2e_test.go
This PR adds an e2e tests case that deletes a tenant namespace once it is created to verify fleetshard-sync is able to restore the namespace and secrets from backup in case of deletion.
Only CI changes so CI is sufficient
```
```
=> add e2e test for secret restore

dp-terraform/ocm/install_addon.sh
For deploying the addon to a dev osd cluster it is convenient to use `acs-dev-dp-01` config, but it has a dummy cluster id that doesn't match real ocm cluster id. This change allows to load `acs-dev-dp-01` config and override the cluster id with the environment variable `OVERRIDE_CLUSTER_ID`
```
./dp-terraform/ocm/install_addon.sh dev acs-dev-dp-01
```
=> ROX-19904: Add OCM cluster id override

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Removing the rhacs-operator subscription in integration environment
=> ROX-20146: Remove rhacs-operator subscription in integration

dp-terraform/ocm/install_addon.sh
Replace all newlines with '\n' symbol as the line breaks are not supported in JSON
```
```
=> Escape linebreaks in json

internal/dinosaur/pkg/gitops/config.go, internal/dinosaur/pkg/gitops/default_central.yaml, internal/dinosaur/pkg/gitops/default_central_test.go
Also add missing labels and annotations in the customize section
=> Add tests for default central template

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
Update cloudwatch exporter image to latest version. See https://github.com/nerdswords/yet-another-cloudwatch-exporter/tags for changelogs, I skimmed them and did not find anything noteworthy for our setup. Will keep an eye on integration in case there are problems.
=> chore: bump cloudwatch exporter to v0.55.0

scripts/lib/helm.sh
Install new CRDs if the previous chart revision didn't contain them. 
Tested locally with dry run flag
=> ROX-19905: Install new CRDs if the previous chart revision didn't contain them

dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
=> ROX-20685: Bump prometheus memory

pkg/features/list.go
Enables the feature flags for GitOps by default
- CI
=> Enable GitOps and TragetedUpgrade feature flags

dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml, dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml, dp-terraform/helm/rhacs-terraform/values.yaml, pkg/features/list.go, pkg/server/profiler/profiler_server.go, pkg/server/profiler/profiler_server_test.go
sync-branches: New code has just landed in rc-2023-11-16.2, so let's bring stage up to speed!
=> sync: rc-2023-11-16.2 to stage

dp-terraform/helm/rhacs-terraform/templates/secret-store.yaml
Fix the values reference to fix the integration deployment.
```
Error: UPGRADE FAILED: Unable to continue with update: could not get information about the resource ClusterSecretStore "" in namespace "": resource name may not be empty
```
https://github.com/stackrox/acs-fleet-manager/actions/runs/6928419633/job/18844187027
```
```
=> Fix ClusterSecretStore name

.openshift-ci/README.md
=> Add openshift-ci debug doc

pkg/server/profiler/profiler_server_test.go
=> Skip flaky test

internal/dinosaur/pkg/services/dinosaur.go, internal/dinosaur/pkg/services/dinosaur_test.go, internal/dinosaur/pkg/services/dinosaurservice_moq.go, internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_mgr.go
Adjust query to mark disgraced centrals to deprovision.
=> ROX-13838: deprovision disgraced centrals

e2e/e2e_test.go, fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml, fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
Bumped the memory of egress proxy
Reduced from 3 to 2 replicas
=> Adjust egress proxy resources and replicas

README.md, docs/development/gitops-configure-central-and-operator.md
Add a small overview for the gitops approach
=> ROX-20025: Add Gitops dev doc

internal/dinosaur/pkg/routes/route_loader.go
Fixing copy-paste typo: change Post to Patch, as in the API spec.
```
```
=> fix: central expired-at method

.secrets.baseline, templates/service-template.yml
- Added permissions to fleet-manager so that it can manage its pod labels
=> ROX-20479: fix pod permissions

templates/service-template.yml
Fixing misplaced sni config in envoy config
=> ROX-20479: fleet-manager-active certs

templates/service-template.yml
This reverts commit e3761af4c7c8925255759d897d668ad425c24421.
=> Revert "ROX-20479: fleet-manager-active certs (#1579)"

templates/service-template.yml
Add tls transport socket to backend cluster envoy
=> ROX-18694: Add tls to backend cluster

templates/service-template.yml
re-add the active-tls cert after envoy is up again
=> ROX-20479: re-add active tls cert

templates/service-template.yml
Try setting `full_scan_certs_on_sni_mismatch` on envoy config
=> ROX-20479: envoy config trial #1000000

.secrets.baseline, templates/service-template.yml
Setting debug log level for envoy to investigate connectivity issue
=> ROX-20479: adding envoy log level parameter

templates/service-template.yml
This reverts commit f5cd3ed4eb5f2493f8a902e921a532b224cd3272.
=> Revert "ROX-20479: only use active-tls cert (#1591)"

templates/service-template.yml
There's an app-protocol annotation that might enable HAProxy to send SNI headers. Trying it out
=> ROX-21779 Try app-protocol annotation

templates/service-template.yml
This reverts commit a332cab9d873813db1f48c7639ac89d20668ebe1.
=> Revert "ROX-21779 Try app-protocol annotation (#1603)"

dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Setting the new FM_ENDPOINT on integration to target the active fleet-manager instance
=> ROX-21779 Set new FM_ENDPOINT for integration

dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
The collector has a slightly larger memory footprint with the CO-RE BPF collection method. Since we have recently switched to this collection method on our ACSCS-secured clusters, we should adjust memory requirements for that.
This PR increases memory from 140Mi to 200Mi - more info can be found in the related JIRA ticket.
- ~[ ] CI and all relevant tests are passing~
- ~[ ] Add secret to app-interface Vault or Secrets Manager if necessary~
- ~[ ] RDS …
=> ROX-21695: Increase collector memory usage for CO-RE BPF collection method

.golangci.yml, internal/dinosaur/pkg/services/cluster_placement_strategy_test.go, internal/dinosaur/pkg/services/data_plane_cluster.go, internal/dinosaur/pkg/services/dinosaur.go, internal/dinosaur/pkg/services/util.go, internal/dinosaur/pkg/services/util_test.go
golangci-lint configuration and according fixes
=> chore: enable unused and ginkgo linters

dp-terraform/helm/Dockerfile, dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml, dp-terraform/helm/rhacs-terraform/values.yaml, dp-terraform/helm/watches.yaml
- Add a new parameter for the helm chart since there're different addon names for each env;
- Add override in the operator.
See: https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/override_values/#using-environment-variables
```
make ocm/setup
```
=> Add fleetshardSync.addonName helm value

internal/dinosaur/pkg/services/dinosaur.go, internal/dinosaur/pkg/services/telemetry.go
- Include expired-at to the list of tenant properties;
- Update Tenant group properties on central request updates.
```go
client.Group(&analytics.Group{
AnonymousId: "fleet-manager-7ddbcf4cbc-2b6xf",
GroupId: "cn0cp84dvq3t6k6t1sng",
Traits: map[string]interface{}{
"Cloud Account": "",
"Cloud Provider": "standalone",
"Expired At": "2024-04-08T00:00:00.000Z",
"Instance Type": "eval",
"Organisation ID": "11009103",
"Region": "standalone",
"Status": "failed",
"Tenant ID": "cn0cp84dvq3t6k6t1sng",
},
})
```
=> feat: expose `expired-at` via Telemetry

.github/pull_request_template.md
Add the addon step to the PR checklist
```
make ocm/setup
```
=> Add the addon step to the PR checklist

templates/service-template.yml
=> Parameterize envoy resources

templates/service-template.yml
Deletes the duplicate line from the service template
=> Delete the duplicate line from the service template

dp-terraform/helm/rhacs-terraform/values.yaml
=> ROX-22926: Fix scannerComponent

dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Expired centrals count panel on the [ACS Fleet Manager dashboard](https://grafana.app-sre.devshift.net/d/D1C839d82/acs-fleet-manager).
=> ROX-22557: Expiration central count grafana panel

.github/dependabot.yaml
This PR configure dependabot for GithHub Actions.
=> chore: dependabot upgrade gha

templates/probe-template.yml
Fixes the deployment
```
Error from server (BadRequest): error when creating "STDIN": Deployment in version "v1" cannot be handled as a Deployment: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
Caused by #1731
```
make ocm/setup
```
=> ROX-16615: Remove empty cpu limits from the probe Deployment

probe/pkg/runtime/runtime.go
We create Central for every region in a different goroutine. After the execution, the cleanup is called. The cleanup deletes all centrals created by probe, not only the one that created in this goroutine. As a result, central that is beeing provisioned in parallel gets deleted.
This change moves the cleanup function into place after all central creations have been completed.  
```
make ocm/setup
```
=> ROX-16615: run probe cleanup after all specs have been completed

build_push_app_interface.sh
Add email sender service to build and push on app-interface
N/A
=> ROX-23252: add email sender to build and push

dp-terraform/helm/rhacs-terraform/charts/vertical-pod-autoscaler/templates/03-operator-group.yaml
=> ROX-23984: install vpa operator group

dp-terraform/helm/rhacs-terraform/charts/vertical-pod-autoscaler/templates/02-subscription.yaml
=> ROX-23984: fix vpa subscription

dp-terraform/helm/rhacs-terraform/charts/vertical-pod-autoscaler/templates/03-operator-group.yaml
=> ROX-23984: fix vpa operator group

dp-terraform/helm/rhacs-terraform/charts/vertical-pod-autoscaler/templates/03-operator-group.yaml
This reverts commit 1a5aded4064a425d3eb21262708c1513e42047d9.
```
make ocm/setup
```
=> Revert "ROX-23984: fix vpa operator group (#1796)"

dp-terraform/osd-cluster-idp-setup.sh
Only the person performing the data plane setup needs to be cluster-admin, and only during the setup process itself. I will add a step in the DP turn up SOP for the user to remove themselves as cluster-admin once the DP is fully set up.
```
make ocm/setup
```
=> ROX-24259: Do not add team as cluster-admins during DP cluster IdP setup

dp-terraform/helm/rhacs-terraform/templates/emailsender-rbac.yaml, dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml, dp-terraform/helm/rhacs-terraform/values.yaml
Add deployment for Email Sender service. Make it disabled by default. `Enabled` flag will be configured via addon flow
N/A
=> ROX-23252: Add emailsender deployment

dp-terraform/helm/rhacs-terraform/values.yaml
`acscs-emailsender` is used in app-interface
```
make ocm/setup
```
=> ROX-23252: Fix default image value for email sender service

fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
=> ROX-23708: Add quay RO user to operator SA

emailsender/cmd/app/main.go, emailsender/pkg/api/emailhandler.go, emailsender/pkg/api/emailhandler_test.go, emailsender/pkg/api/handlers.go, emailsender/pkg/api/routes.go, emailsender/pkg/email/sender.go, emailsender/pkg/email/sender_test.go, emailsender/pkg/email/ses.go, emailsender/pkg/email/ses_test.go
based on #1847
```
CLUSTER_ID=test go run emailsender/cmd/app/main.go
```
=> ROX-23252: Connect email sender service to the endpoint

dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
=> ROX-22549: Add the addon metric to the grafana dashboard

emailsender/cmd/app/main.go, emailsender/pkg/api/emailhandler.go, emailsender/pkg/api/emailhandler_test.go, emailsender/pkg/email/sender.go, emailsender/pkg/email/sender_test.go
Wire Rate Limiter Service and Email Send Service
=> ROX-23260: Add Rate Limiter to Email Sender

dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml, dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
original #1879
```
make ocm/setup
```
=> ROX-23259: emailsender aws sts

dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
=> ROX-23260: Use fleetshardsync cluster values

scripts/import_init_bundle.sh
=> ROX-24844: Init bundle script fixes

emailsender/pkg/api/emailhandler.go, pkg/auth/acs_claims.go, pkg/auth/acs_claims_test.go
=> ROX-23260: Use orgID for tenantID

dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml, internal/dinosaur/pkg/services/addon.go, internal/dinosaur/pkg/services/addon_test.go, pkg/metrics/metrics.go
Refine metrics reporting. Make statuses more fine-grained and update statuses in more cases. 
Unit tests
=> ROX-22549: Refine the addon metrics reporting

emailsender/pkg/email/sender.go, emailsender/pkg/metrics/metrics.go, emailsender/pkg/metrics/metrics_test.go
Rename send email metric
Add failed send email attempt
Add throttled send email attempt
``` …
```
=> ROX-23261: Add email sender metrics

build_push_app_interface.sh
Fix probe repo name bug. Currently probe repo value is empty
=> ROX-24458: probe build fix

dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
Add namespace and label selector to watch Probe CRs on tenant namespaces.
```
make ocm/setup
```
=> ROX-25389: Add namespace and label selector for Probe CRs

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
Routine bump of the cloudwatch exporter image. See https://github.com/nerdswords/yet-another-cloudwatch-exporter/releases for changelogs. Includes various fixes and dep bumps. Didn't do a manual test, I'd suggest to test on integration for simplicity. 
```
make ocm/setup
```
=> chore(terraform): bump cloudwatch exporter

Makefile, dev/env/manifests/fleetshard-operator/51-fleetshard-cr.yaml, dp-terraform/helm/Dockerfile
Contains bug and CVE fixes
```
make ocm/setup
```
=> ROX-25605: Bump helm operator image base image

fleetshard/main.go, internal/certmonitor/certmonitor.go, internal/certmonitor/certmonitor_test.go
=> Fix certmonitor labelselector

emailsender/Dockerfile, probe/Dockerfile
Konflux demands `Red Hat, Inc.` vendor label in Dockerfile
```
make ocm/setup
```
=> ROX-25670: Fix emailsender and probe dockerfile for Konflux contract check

templates/probe-template.yml
=> ROX 26359: Switch Authentication Type in Probe Service

dp-terraform/helm/Dockerfile
Add necessary labels to the `Dockerfile` to make it possible to build on Konflux
N/A
=> ROX-26499: Make fleetshard operator dockerfile compliant with Konflux

.pre-commit-config.yaml, .secrets.baseline
Konflux bot opened pre-commit bumping deps PRs:
- #2029 
- #2060 
- #2030 
- #2031
Some of those PRs needs manual changes to fix CI so this PR provides it
make pre-commit
=> ROX-26535: Combine konflux bot pre-commit PRs

.tekton/acs-emailsender-pull-request.yaml, .tekton/acs-emailsender-push.yaml, .tekton/acs-fleet-manager-pull-request.yaml, .tekton/acs-fleet-manager-push.yaml, .tekton/acs-fleetshard-operator-pull-request.yaml, .tekton/acs-fleetshard-operator-push.yaml, .tekton/acs-probe-pull-request.yaml, .tekton/acs-probe-push.yaml
Add a required check to conform the enterprise contract and push images on merge to main. 
```
make ocm/setup
```
=> Add rpms-signature-scan to the konflux builds

README.md
Trigger pipelines
```
make ocm/setup
```
=> trigger pipelines

.tekton/acs-fleetshard-operator-push.yaml
=> chores: Make Fleetshard operator build on PR

internal/dinosaur/pkg/services/addon.go
Fix the following issues: 
1. `lastStatus` is never set
2. Enable backoff if the addon is unhealthy. OCM may return an error (Unhealthy status) right after fleet manager start. 
```
make ocm/setup
```
=> Fix addon backoff

dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
Fix invalid spacing
```
make ocm/setup
```
=> Fix tenant image pull secret

.tekton/base-acscs-pipeline.yaml
Necessary secret added to the Konflux config
N/A
=> ROX-27335: Add slack notification for failed Konflux task

dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-secrets.yaml
Fix whitespace indentation
```
make ocm/setup
```
=> Fix the secured cluster external secret

dp-terraform/osd-cluster-idp-setup.sh
Remove the cluster login and all cluster actions, such as creating a cluster role binding. The latter has been moved to the gitops configuration. 
```
make ocm/setup
```
=> Remove cluster actions from the cluster idp setup

dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml, dp-terraform/helm/rhacs-terraform/values.yaml
Workaround for the issue fixed in https://github.com/stackrox/stackrox/pull/13824 until it's released (or just leave as is).
Tested manually on an infra cluster.
=> ROX-27688: Add a transformer to vector to parse multiline json requests

dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/02-configmap.yaml, dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml
Addition to #2159 that aggregates multiline strings.
```
make ocm/setup
```
=> ROX-27688: Add JSON aggregator lua function to the audit log aggregator

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Export audit log Cloudwatch log group metric. It will be used for creating a missing audit logs alert.
~- [ ] (If applicable) Changes to the dp-terraform Helm values have been reflected in the addon on …
=> ROX-28104: Export audit logs incoming events from CloudWatch

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
=> Rox-28104: Fix dimensions for audit log metric exporter

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
=> ROX-28104: Fix period for audit log metric exporter

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
- Make SES metrics do not complain when no value exists
- tune group log metric to narrow gathering window and better filtering
```
N/A
```
=> ROX-28182: Fix cloudwatch-exporter error logs and tune loggroup metric fetch

dp-terraform/helm/rhacs-terraform/Chart.lock, dp-terraform/helm/rhacs-terraform/Chart.yaml, dp-terraform/helm/rhacs-terraform/values.yaml
=> ROX-27835: upgrade external secret operator in dp-terraform

dev/env/scripts/docker.sh, dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
Filter package operator logs in CloudWatch
Tested on an osd cluster
=> fix(openshift-logging): filter package operator logs in Cloudwatch

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Current avg statisctic for audit log events is equal to zero too often due to wide period and length. Sum can be a better alternative to check activity in the audit_logs log group
N/A
=> ROX-28183: Add Sum statistic and increase period

.secrets.baseline, Makefile, scripts/ci/central_compatibility/run_compatibility_test.sh
Pt 1. : #2255 
```
make ocm/setup
```
=> ROX-28686: External secrets cleanup pt. 2

pkg/features/list.go
This enables the cluster migration feature.
```
make ocm/setup
```
=> ROX-28814: enable cluster migration feature flag

dp-terraform/helm/Dockerfile
Upgrading ose-helm-operator
```
make ocm/setup
```
=> ROX-29034: Upgrade ose-helm-operator

.github/workflows/aws-integration.yaml, .github/workflows/ci.yaml, .github/workflows/emailsender-central-compatibility.yaml, .golangci.yml, .openshift-ci/e2e-runtime/Dockerfile, .openshift-ci/e2e-runtime/e2e_dockerized.sh, Dockerfile, Dockerfile.tools, README.md, emailsender/Dockerfile, go.mod, probe/Dockerfile, tools/go.mod
Update go version to 1.23
```
make ocm/setup
```
=> Update go version to 1.23

internal/central/pkg/config/central.go, internal/central/pkg/config/central_quota.go, internal/central/pkg/services/quota/quota_management_list_service.go, internal/central/pkg/workers/centralmgrs/expiration_date_mgr.go, internal/central/pkg/workers/centralmgrs/expiration_date_mgr_test.go
- Skip expiration worker and ignore quota check for internal orgs
- Add additional log for quota check
local run
=> ROX-29189: Exclude quota check and skip expiration worker for internal orgs

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
=> ROX-29285: Bump yet another cloudwatch exporter image

dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
The latest image for yace pushed to quay instead of ghcr
```
make ocm/setup
```
=> ROX-29285: Change image repo for yace

dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
Filter PKO audit events published to CloudWatch.
```
make ocm/setup
```
=> ROX-24629: Filter PKO audit events

dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
Follow up on #2326. Audit events are still not filtered.
```
make ocm/setup
```
=> ROX-24629: Change userGroups to users

probe/config/config.go, probe/config/config_test.go
Fixing breaking change: https://github.com/caarlos0/env/releases/tag/v9.0.0
```
make ocm/setup
```
=> fix env expand

fleetshard/pkg/central/reconciler/reconciler.go
Setting the secret owner references to the central CR in FS depends on the central name. This does not work once the central CR name is no longer equal the tenant name in the DB. This PR fixes that by using a list on the namespace grabbing the first available central and applying the owner reference.
```
make ocm/setup
```
=> ROX-21884: fix secret owner reference in FS for static CR name

fleetshard-operator/Dockerfile
=> ROX-30041: Update helm operator base image to rhel9
